### ISSUE TITLE
Add support for the split index API [DATAES-539]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1112]
**[Rick Hanton](https://jira.spring.io/secure/ViewProfile.jspa?name=rhanton)** opened **[DATAES-539](https://jira.spring.io/browse/DATAES-539?redirect=false)** and commented

Currently the Spring Data Elasticsearch project does not support setting the _number_of_routing_shards_ on an index that would allow for use of the Split Index API at a later time if needed. Ideally, this setting would be added to the `@Document` annotation and then populated into the ElasticsearchTemplate if it is set.

 

The Split Index API is available in Elasticsearch 6.1+ and documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/6.1/indices-split-index.html

---
No further details from [DATAES-539](https://jira.spring.io/browse/DATAES-539?redirect=false)

**Comment by sothawo** [comment]
Since Elasticsearch 7.0 setting the _number_of_routing_shards_ is not required anymore in order t split an index.
