### ISSUE TITLE
Add "elasticsearchTemplate" bean alias for ElasticsearchTemplate [DATAES-563]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1114]
**[Brian Clozel](https://jira.spring.io/secure/ViewProfile.jspa?name=bclozel)** opened **[DATAES-563](https://jira.spring.io/browse/DATAES-563?redirect=false)** and commented

When extending the `AbstractElasticsearchConfiguration` and configuring Elasticsearch repositories support with `@EnableElasticsearchRepositories`, I'm getting the following exception when the context starts:

```java
Error creating bean with name 'cityRepository': Cannot resolve reference to bean 'elasticsearchTemplate' while setting bean property 'elasticsearchOperations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'elasticsearchTemplate' available
```

It seems that the `AbstractElasticsearchConfiguration` class is creating the bean with the name `"elasticsearchOperations"`, whereas the configuration is expecting `"elasticsearchTemplate"`.

```java
@Bean
public ElasticsearchOperations elasticsearchOperations() {
     return new ElasticsearchRestTemplate(elasticsearchClient(), elasticsearchConverter(), resultsMapper());
}
```

Shouldn't the infrastructure get an `ElasticsearchOperations` if a single one is available and not necessarily rely on a named reference?

---

**Affects:** 3.2 M3 (Moore)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-elasticsearch/pull/271

**Comment by rcampion** [comment]
Is there any update on this.

I am using:

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.7</version>
	</parent>

**Comment by fayedyazid** [comment]
delete extends AbstractElasticsearchConfiguration
