### ISSUE TITLE
Create percolation type/mapping during index creation [DATAES-553]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1128]
**[Rad Akefirad](https://jira.spring.io/secure/ViewProfile.jspa?name=akefirad)** opened **[DATAES-553](https://jira.spring.io/browse/DATAES-553?redirect=false)** and commented

In the new version of ES, the percolators are not built-in (/my-index`/.percolator`) types anymore, but a simple type like any other types with a very specific mapping (see documentation for more information).

This means that unlike old versions of ES, to be able to use percolation, one needs to create the type with the correct mapping first and then store queries.

Having the index-auto-creation feature, it's nice to have a way to indicate that the index being created needs percolator type as well. This can be done via a simple boolean attribute in the `@Document` annotation or introducing a new annotation (e.g. `@PercolatedIndex`) which lets you control every bit of the type while creating it.

We already have some code and would be happy to prepare a PR if people are interested

---
No further details from [DATAES-553](https://jira.spring.io/browse/DATAES-553?redirect=false)

**Comment by sothawo** [comment]
`FieldType.Percolator` is available since version 4.0 now, so this seems to be an old obsolete issue.
