### ISSUE TITLE
Add Completion and Suggest support to ElasticsearchRestTemplate and Repositories [DATAES-622]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1185]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-622](https://jira.spring.io/browse/DATAES-622?redirect=false)** and commented

Currently there is the possibility to create an Elasticsearch mapping for Completion fields and to store data with completion fields. But the support for reading / searching with these fileds is implemented only in `ElasticseachTemplate`.

Support for this should be added to `ElasticsearchRestTemplate` and to the Repositories classes

---

**Affects:** 3.2 RC1 (Moore)

2 votes, 2 watchers

**Comment by sothawo** [comment]
will be done with #1302
