### ISSUE TITLE
Add missing fieldtypes and parameters to mapping [DATAES-621]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1194]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-621](https://jira.spring.io/browse/DATAES-621?redirect=false)** and commented

Currently not all [possible field types](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html) can be defined using the `@Field` annotation, for example _binary_ is missing. The missing types should be added

---

**Affects:** 3.2 RC1 (Moore), 3.2 RC2 (Moore)

**Issue Links:**
- [DATAES-399](https://jira.spring.io/browse/DATAES-399) Add term_vector mapping parameter
 (_**"supersedes"**_)
- [DATAES-501](https://jira.spring.io/browse/DATAES-501) Support the "norms" mapping parameter
 (_**"supersedes"**_)
- [DATAES-617](https://jira.spring.io/browse/DATAES-617) Spring Data Elasticsearch Problem with IP_Range Data type
 (_**"supersedes"**_)
- [DATAES-618](https://jira.spring.io/browse/DATAES-618) Support for doc_values mapping parameter
 (_**"supersedes"**_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-elasticsearch/pull/311, and commits https://github.com/spring-projects/spring-data-elasticsearch/commit/f0117e7b6a9a2df9c296f91c9c9f0107809f9a67, https://github.com/spring-projects/spring-data-elasticsearch/commit/bb9fea2b897639eba69446bc981c571543348d5f

1 votes, 2 watchers

**Comment by mdgilene** [comment]
There still seems to be some missing field types after this update. In particular I am interested in the `dense_vector` field type.

**Comment by sothawo** [comment]
This issue was closed and merged in January 2020, using version 7.5.1 of Elasticsearch. At that time the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/dense-vector.html) stated as a **warning**:

> This functionality is experimental and may be changed or removed completely in a future release. Elastic will take a best effort approach to fix any issues, but experimental features are not subject to the support SLA of official GA features.

This warning has been removed, so it could be added to Spring Data Elasticsearch now. Please create a new issue for this.
