### ISSUE TITLE
Change do/prepare methods in ElasticsearchRestTemplate to protected access [DATAES-664]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1238]
**[Chris Nelson](https://jira.spring.io/secure/ViewProfile.jspa?name=perch24@gmail.com)** opened **[DATAES-664](https://jira.spring.io/browse/DATAES-664?redirect=false)** and commented

The private "do" and "prepare" methods in ElasticsearchRestTemplate complicate extending this class for customization. For example, in our software, we would like to define default sorting for each of our entity classes. If I define a repository method findBySomeProperty(property, paging) I would like to apply this sorting in the prepareSort method of a custom subclass of ElastichsearchRestTemplate. Additionally, we use ES sorts that are not supported by the Spring Data ES implementation, i.e. geosort and nested sorts. 

There are also other places that we would like to extend to implement parent/child relationships. At least until this is supported in 4.x. In the prepareIndex method, I would like to set the routing to the parent ID instead of the ES deprecated parent ID. Looking at other template implementations like JdbcTemplate and JmsTemplate in the SpringFramework these methods generally have protected access. Would it be possible to do the same for ElasticsearchRestTemplate?    

---

**Affects:** 3.2 GA (Moore)

**Comment by sothawo** [comment]
will be addressed in the new client
