### ISSUE TITLE
Implement custom hooks in the Requestfactory to allow request modifications [DATAES-698]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1270]
**[Adi](https://jira.spring.io/secure/ViewProfile.jspa?name=adisesha)** opened **[DATAES-698](https://jira.spring.io/browse/DATAES-698?redirect=false)** and commented

First of all great work with DATES-631. This change adds new method to Elasticsearchoperations, 'org.springframework.data.elasticsearch.core.ElasticsearchOperations#getRequestFactory' but but 'org.springframework.data.elasticsearch.core.RequestFactory' has default access. This will break any custom implementations of ElasticsearchOperations.

Another request is make RequestFactory settable in 'org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate'. This opens up modifying Elasticsearch query entities. For example, in our case, setting routing key depends on the index.  

---

**Affects:** 4.0 M1 (Neumann)

**Reference URL:** https://jira.spring.io/browse/DATAES-631

**Comment by thiagohora** [comment]
Hey, I'm not sure if this is the right place, but I'm facing a similar issue. I would like to parameterize the refresh param in the delete by query call. Do we have an update on this?

**Comment by sothawo** [comment]
The solution to your problem would be to have this custom refresh option added the the `Query` from Spring Data Elasticsearch (SDE) and have it added to the Elasticsearch `DeleteByQueryRequest` by the `RequestFactory`, no need for the end user to manipulate the internal Elasticsearch objects.

The reason for this is that SDE should hide away how it communicates with Elasticsearch - although most out of historical reasons, this is not always done.

Of course it would be easier to make all the classes at least package private and let people derive from them; we have requests to do that for other classes like `AbstractElasticsearchTemplate` as well. Let me explain why this is dangerous with one of the upcoming changes:

Currently SDE uses the `TransportClient`, the `RestHighLevelClient` and our custom `ReactiveElasticsearchClient` to communicate with Elasticsearch, map the query classes to Elasticsearch classs and unwrap the answers. `RequestFactory` is used for all three clients, `AbstractElasticsearch` is the base for communicating the non-reactive way. These basically internal classes are meant to inhibit code duplication. For some parts we needed to copy and adapt code from Elasticsearch.

With version 7.12 Elasticsearch changed the licensing model, it is not possible anymore to copy and adapt new code from Elasticsearch. And the code for the Elasticsearch `RestHighLevelClient` contains many classes - especially request and response classes - that come from the core Elasticsearch libraries that don't have an Apache 2 license anymore. This makes it at least disputable if SDE could go on and use the `RestHighLevelClient`. But Elasticsearch knows this problem and they are going to release a completely new written Client which will be released under an Apache 2 licenses and that has no dependencies to any other Elasticsearch library. The first beta to have a look at might be released end of this month, I have no further information yet.

What does this mean for SDE? We have to change our code (dropping support for the `TransportClient`) and see how we can use this new client for both imperative and reactive communication. Without `TransportClient`support, the `AbstractElasticsearchTemplate` is not needed anymore. And as the request and response objects from Elasticsearch will be new ones - I don't think that they will be compatible - the `RequestFactory` will probably need to be totally rewritten.

As a summary: When using the SDE API you should not be affected by such changes, when overriding classes that are used to implement internal SDE logic, these changes will break your application.

So if you need a custom refresh option on the delete by query please add a ticket for that to have it added to SDE

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
