### ISSUE TITLE
CriteriaQueryProcessor must handle nested Criteria definitions [DATAES-706]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1278]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-706](https://jira.spring.io/browse/DATAES-706?redirect=false)** and commented

When `CriteriaQueryProcessor` is building a `QueryBuilder` from a `Criteria` it does not consider that the `Criteria` entries in the criteria chain may contain nested criteria lists.

So it is not possible to transform nested `CriteriaQuery` objects into correct Elasticsearch queries

---

**Affects:** 4.0 M1 (Neumann)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-elasticsearch/pull/505

1 votes, 3 watchers

**Comment by StanculescuDaniel** [comment]
@spring-projects-issues, @sothawo, was this feature implemented in the end?

**Comment by sothawo** [comment]
what makes you think that not? See the referenced PR.
