### ISSUE TITLE
Ignore cluster check for user without cluster monitoring permission [DATAES-712]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1284]
**[aljacinto](https://jira.spring.io/secure/ViewProfile.jspa?name=aljacinto)** opened **[DATAES-712](https://jira.spring.io/browse/DATAES-712?redirect=false)** and commented

The current implementation always check for cluster info using base URL e.g. [http://localhost:9200](http://localhost:9200/) but in our production environment it is rare that user are given cluster monitor permission.  If there is a permission to ignore the check or use the index search to check connection e.g. http://localhost:9200/my_index/_search

 

Thanks

---

**Affects:** 3.1.14 (Lovelace SR14), 3.2.3 (Moore SR3)

**Reference URL:** https://stackoverflow.com/questions/59341029/elasticsearch-spring-data-support-for-user-without-access-to-root/59342862#59342862

**Comment by sothawo** [comment]
From the next version 5 on, the reactive code does not do this call anymore. It has been rewritten, so this issue is not valid anymore.
