### ISSUE TITLE
Support elastic:http-client

### ISSUE THREAD

**Issue by keesun** [spring-projects/spring-data-elasticsearch#13]
Hi, 

I just wonder why there is no support for http client.
I can use the Spring's RestTemplate but I think there will be some boiler-plat codes to do that. Why don't you support `elastic:http-client` likes `elastic:transport-client` or `elastic:node-client`.

Thanks.

**Comment by sothawo** [comment]
http support is available since Spring Data Elasticsearch 3.2; closing this old issue
