### ISSUE TITLE
Handling of dropped connections [DATAES-760]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1334]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-760](https://jira.spring.io/browse/DATAES-760?redirect=false)** and commented

When using the REST clients (reactive and non-reactive) it can happen that the connection is lost after longer idle times.

 

This should be investigated how
* this can be detected
* what automatic recovery can be implemented

 

```
For the non-reactive part this can be integrated in the execute method to have a retry mechanism once DATAES-751 is done
```

Edit:

non-reactive code might use for example [Spring Retry](https://github.com/spring-projects/spring-retry) to catch errors and retry to do the failed operation again, for reactive code, the different flavours of `Mono.retry()` or `Flux.retry()` can be used

---

**Issue Links:**
- [DATAES-751](https://jira.spring.io/browse/DATAES-751) Introduce ClientCallbackfor the rest client
 (_**"depends on"**_)

**Comment by labedzkim** [comment]
Should it be already fixed as commented by @sothawo? I'm getting "DataAccessResourceFailureException: 60,000 milliseconds timeout on connection" with use of spring-data-elasticsearch-4.4.15.jar:

> org.springframework.dao.DataAccessResourceFailureException: 60,000 milliseconds timeout on connection http-outgoing-20 [ACTIVE]; nested exception is java.lang.RuntimeException: 60,000 milliseconds timeout on connection http-outgoing-20 [ACTIVE]
> 	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:94)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:601)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:584)
> 	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:399)
> 	at org.springframework.data.elasticsearch.repository.query.AbstractElasticsearchRepositoryQuery.execute(AbstractElasticsearchRepositoryQuery.java:95)
> 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
> 	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
> 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160)
> 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241)
> 	at jdk.proxy2/jdk.proxy2.$Proxy138.findByLoggerAndTimestampBetween(Unknown Source)
