### ISSUE TITLE
Add enabled mapping parameter to FieldType configuration [DATAES-798]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-elasticsearch#1370]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-798](https://jira.spring.io/browse/DATAES-798?redirect=false)** and commented

enabled should be added as a possible FieldType parameter

---

**Affects:** 4.0 RC1 (Neumann)

**Reference URL:** https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html

**Comment by sothawo** [comment]
Mapping can be disabled by setting `@Mapping(enabled=false)` on 
* an entity class, disabling the mapping for the whole entity
* a property of type `FieldType.Object`, disabling the mapping for this property
