### ISSUE TITLE
Implement projections to return only selected fields [DATAES-805]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1378]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-805](https://jira.spring.io/browse/DATAES-805?redirect=false)** and commented

Spring Data MongoDB supports projections (see reference URL).

Spring Data Elasticsearch should be able to do this as well

---

**Reference URL:** https://docs.spring.io/spring-data/mongodb/docs/2.2.6.RELEASE/reference/html/#projections

**Comment by sothawo** [comment]
Closed by #2254
