### ISSUE TITLE
ES Rest High Level Client throws SocketTimeoutException after being idle for sometime [DATAES-815]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1387]
**[Ori Doolman](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49526)** opened **[DATAES-815](https://jira.spring.io/browse/DATAES-815?redirect=false)** and commented

After the application (client) is idle for some time, the first request to ES always fail with a timeout error.

The following log is from SpringBoot 2.2.6, but I reproduced the same on 2.3.0.M4.

 

```java
caused by: java.net.SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE] at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:944) ~[elasticsearch-rest-client-6.8.7.jar:6.8.7] at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233) ~[elasticsearch-rest-client-6.8.7.jar:6.8.7] at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764) ~[elasticsearch-rest-high-level-client-6.8.7.jar:6.8.7] at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734) ~[elasticsearch-rest-high-level-client-6.8.7.jar:6.8.7] at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696) ~[elasticsearch-rest-high-level-client-6.8.7.jar:6.8.7] at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1092) ~[elasticsearch-rest-high-level-client-6.8.7.jar:6.8.7] at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.doSearch(ElasticsearchRestTemplate.java:1152) ~[spring-data-elasticsearch-3.2.6.RELEASE.jar:3.2.6.RELEASE] ... 152 common frames omitted Caused by: java.net.SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE] at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[httpasyncclient-4.1.4.jar:4.1.4] at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar:4.1.4] at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.13.jar:4.4.13] at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio-4.4.13.jar:4.4.13] ... 1 common frames omitted
```

 

I tried setting the connection timeout and the socket timeout to 0 in the client configuration, but it did not help. I just got a different type of exception.

Here is how I configure my client:

 

```java
clientConfiguration = ClientConfiguration.builder()
        .connectedTo(esHost + ":" + esPort)
        .usingSsl()
        //.withConnectTimeout(0)
        .build();

RestHighLevelClient client = RestClients.create(clientConfiguration).rest();
```

 

 

 

---

**Affects:** 4.0 RC2 (Neumann)

**Reference URL:** https://stackoverflow.com/questions/56815933/es-rest-high-level-client-throws-sockettimeoutexception-after-being-idle-for-som

**Comment by dfrench12** [comment]
> **[Ori Doolman](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49526)** commented
> 
> Here is my latest workaround code, in case someone will want to use it.
> 
> Updates from previous code:
> 
> * moved retryCount to be local variable
> * Only retry in case of SocketTimeoutException
> 
>  
> 
> ```java
> // code placeholder
> @Override
> public ElasticsearchOperations elasticsearchOperations(ElasticsearchConverter elasticsearchConverter) {
>     return new ElasticsearchRestTemplate(elasticsearchClient(), elasticsearchConverter) {
>         @Override
>         public <T> T execute(ClientCallback<T> callback) {
>             int retryCount = 0;
>             T t = null;
>             while (retryCount <= RestClientBuilder.DEFAULT_MAX_CONN_PER_ROUTE && t == null) {
>                 try {
>                     t = super.execute(callback);
>                 } catch (DataAccessResourceFailureException e) {
>                     // retry
>                     if (e.getCause() != null && (e.getCause().getCause() instanceof SocketTimeoutException) &&
>                             (retryCount < RestClientBuilder.DEFAULT_MAX_CONN_PER_ROUTE)) {
>                         retryCount++;
>                         log.warn("Elasticsearch client - performing retry {} after caught DataAccessResourceFailureException: {}", retryCount, e.getMessage());
>                     }
>                     else {
>                         throw e;
>                     }
>                 }
>             }
>             return t;
>         }
>     };
> }
> ```
> 
> Ori.

Thank you! We were experiencing this DataAccessResourceFailureException / SocketTimeoutException once in a while when updating an index. Our best guess is that the OpenSearch service we're using was doing garbage collection which caused this hiccup once in a while. But retrying a couple of times worked.

Minor code notes in case it's helpful for others:
- Your code uses `elasticsearchClient()` (calls the method), but in ours we decided not to call our method but let spring inject the dependency.
- Since the `AbstractElasticsearchConfiguration` base class's `elasticsearchOperations` method was annotated with `@Bean(name = { "elasticsearchOperations", "elasticsearchTemplate" })`, we added that annotation to our overridden method as well (not sure if it's necessary but just to be safe).
