### ISSUE TITLE
ElasticsearchDateConverter fails to parse dates with custom format [DATAES-833]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1406]
**[Jakob Hoeper](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49593)** opened **[DATAES-833](https://jira.spring.io/browse/DATAES-833?redirect=false)** and commented

When I create an `ElasticsearchDateConverter` of a custom date format pattern (which telling from the [Tests](https://github.com/spring-projects/spring-data-elasticsearch/blob/4.0.0.RELEASE/src/test/java/org/springframework/data/elasticsearch/core/convert/ElasticsearchDateConverterTests.java#L29) seems to be intended use), then it fails to parse strings into `java.util.Date` as well as `TemporalAccessor` subclasses.

It is hence no longer possible to do this:

```java
@Field(type = FieldType.Date, format = DateFormat.custom, pattern = "yyyy-MM-dd")
private LocalDate field; // nor private Date field;
```

Furthermore, all of the following do pass:

```java
ElasticsearchDateConverter converter = ElasticsearchDateConverter.of("yyyy-MM-dd");
assertThrows(DateTimeException.class,
    () -> converter.parse("2019-12-18")
);
assertThrows(ConversionException.class,
    () -> converter.parse("2019-12-18", LocalDate.class)
);
assertThrows(DateTimeException.class,
    () -> ElasticsearchDateConverter.of("yyyy-MM-dd HH:mm:ss").parse(
        "2020-05-19 12:53:17"
    )
);
```

Parsing fails in `ElasticsearchDateConverter` lines [109](https://github.com/spring-projects/spring-data-elasticsearch/blob/4.0.0.RELEASE/src/main/java/org/springframework/data/elasticsearch/core/convert/ElasticsearchDateConverter.java#L109) and [125](https://github.com/spring-projects/spring-data-elasticsearch/blob/4.0.0.RELEASE/src/main/java/org/springframework/data/elasticsearch/core/convert/ElasticsearchDateConverter.java#L125), respectively.

Causes are:

```java
Caused by: java.time.DateTimeException: Unable to obtain LocalDate from TemporalAccessor: {MonthOfYear=5, YearOfEra=2020, DayOfMonth=19},ISO of type java.time.format.Parsed
	at java.base/java.time.LocalDate.from(LocalDate.java:396)
```

for `LocalDate` and

```java
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.base/java.time.format.Parsed.getLong(Parsed.java:203)
```

for `Date`.

Problem seems to be that during invocation of `from(TemporalAccessor)` in line `109`, there are attempts to access `ChronoField` s that are not defined for the passed `TemporalAccessor`. When I override `from` and use only those `ChronoField` s supported by my custom date format pattern, then everything is fine

---

**Affects:** 4.0 GA (Neumann)

**Comment by tuankhoiutc260** [comment]
This is how i config:
- In Elasticsearch DTO

    @Field(type = FieldType.Date, format = DateFormat.date_hour_minute_second_millis)
    LocalDateTime createdDate;
    
- This way works fine, but if there is timezone difference then in elasticsearch and db will show different time, so i need extra configuration in mapper and i use mapstruct

    @Named("localDateTimeToDate")
    default Date localDateTimeToDate(LocalDateTime localDateTime) {
        if (localDateTime == null) {
            return null;
        }
        ZonedDateTime zonedDateTime = localDateTime.atZone(ZoneId.of("UTC+7")); 
        return Date.from(zonedDateTime.toInstant());
    }

    @Named("dateToLocalDateTime")
    default LocalDateTime dateToLocalDateTime(Date date) {
        if (date == null) {
            return null;
        }
        Instant instant = date.toInstant();
        ZonedDateTime zonedDateTime = instant.atZone(ZoneId.of("UTC+7")); 
        return zonedDateTime.toLocalDateTime();
    }

- And this is what i used:

    @Mapping(target = "createdDate", source = "createdDate", qualifiedByName = "localDateTimeToDate")
    @Mapping(target = "lastModifiedDate", source = "lastModifiedDate", qualifiedByName = "localDateTimeToDate")
    CategoryDocument toCategoryDocument(Category category);

    @Mapping(target = "createdDate", source = "createdDate", qualifiedByName = "dateToLocalDateTime")
    @Mapping(target = "lastModifiedDate", source = "lastModifiedDate", qualifiedByName = "dateToLocalDateTime")
    Category fromCategoryDocument(CategoryDocument categoryDocument);

**Comment by sothawo** [comment]
>  but if there is timezone difference 

a `LocalDateTime` has **no** time zone associated with it. From the class API documentation:

> This class does not store or represent a time-zone. Instead, it is a description of the date, as used for birthdays, combined with the local time as seen on a wall clock. It cannot represent an instant on the time-line without additional information such as an offset or time-zone.
