### ISSUE TITLE
Allow disabling TypeHints. [DATAES-881]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1454]
**[chaitanya-mittapalli](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49908)** opened **[DATAES-881](https://jira.spring.io/browse/DATAES-881?redirect=false)** and commented

I needed a Way that  i can disable TypeHints in the Document Generated for Spring Data ElasticSearch.
https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.mapping.meta-model.rules

I have the Mapping Definition for my elastic Index Dynamic Mapping Set to Strict and when i am trying to Index a Document it was created a Field _class in the Elastic Document which is failing the Document Insertion into the ElasticSearch index 7.X with Below Error
Elasticsearch exception [type=strict_dynamic_mapping_exception, reason=mapping set to strict, dynamic introduction of [_class] within [_doc] is not allowed]

---

**Affects:** 4.0.1 (Neumann SR1)

**Reference URL:** https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.mapping

**Comment by sothawo** [comment]
asked on SO as well: https://stackoverflow.com/questions/66062703/is-there-any-way-to-force-spring-not-to-use-create-class-field-in-the-mapping

**Comment by fazaza** [comment]
@sothawo any news about this issue ?

**Comment by sothawo** [comment]
no. might be one of the next issues I can do, when I find the time.

**Comment by rtakkall** [comment]
Thank you
