### ISSUE TITLE
Add support for composable index templates [DATAES-885]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1458]
**[sothawo](https://jira.spring.io/secure/ViewProfile.jspa?name=sothawo)** opened **[DATAES-885](https://jira.spring.io/browse/DATAES-885?redirect=false)** and commented

Elasticsearch 7.8 introduces composable index templates. These should be support in Spring Data Elasticsearch as well

---
No further details from [DATAES-885](https://jira.spring.io/browse/DATAES-885?redirect=false)

**Comment by sothawo** [comment]
Note: legacy index template API is deprecated as of Elasticsearch 7.13.0

**Comment by sothawo** [comment]
Started working on that, but it seems that the necessary API calls are missing from the client (https://github.com/elastic/elasticsearch-java/issues/520)
