### ISSUE TITLE
Add `matched_queries` field in SearchHit [DATAES-979]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1514]
**[Farooq Ahmad Khan](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50696)** opened **[DATAES-979](https://jira.spring.io/browse/DATAES-979?redirect=false)** and commented

`org.elasticsearch.search.SearchHit` returns a field named **`matched_queries`** but the `org.springframework.data.elasticsearch.core.SearchHit` does not hold this value. We need this value to be added in the spring data elasticsearch

---
No further details from [DATAES-979](https://jira.spring.io/browse/DATAES-979?redirect=false)

**Comment by mdgilene** [comment]
Any update on this? Our team was in the process of moving to spring data ES when I discovered we weren't able to access our named queries in the results. Pretty big blocker for us at the moment.

**Comment by sothawo** [comment]
No. There never was a PR opened to address this, so it is still an open issue.
