### ISSUE TITLE
(Reactive)ElasticsearchOperations does not have option to include request_cache path param in search request [DATAES-992]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#1564]
**[Oindrila Barik](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50757)** opened **[DATAES-992](https://jira.spring.io/browse/DATAES-992?redirect=false)** and commented

Elastic search provides an option to add a path param to any _search queries_  called _request_cache=true which enables it to cache any incoming queries and its results.

The SearchRequest class provides a way to add this param using the .requestCache(Boolean.TRUE) method. But the RequestFactory.java present in Spring DATA that converts a NativeSearchQuery into SearchRequest doesn't support this argument.

 

Thus this parameter cannot be added to any request for search using _ReactiveElasticSearchOperations_

---
No further details from [DATAES-992](https://jira.spring.io/browse/DATAES-992?redirect=false)

**Comment by sothawo** [comment]
The reactive implementation of search request under the hood uses Elasticsearch's scroll API to retrieve the documents. `request_cache`cannot be used in a scroll context.

For the imperative, non-reactive code this is done in #1797

**Comment by sothawo** [comment]
not all reactive calls use the scroll interface, paged queries and count do not. So this needs to be added to these calls. Doing imperative with this ticket as well.
