### ISSUE TITLE
Update CI jobs with Docker Login [DATAES-996]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-elasticsearch#1568]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAES-996](https://jira.spring.io/browse/DATAES-996?redirect=false)** and commented

---
No further details from [DATAES-996](https://jira.spring.io/browse/DATAES-996?redirect=false)

**Comment by sothawo** [comment]
Hi @gregturn this was done with commit a2d2a6119dbb0cfc469021f9ca0121401773d964, right? So I can close this issue?

**Comment by mp911de** [comment]
Yes, that looks like it.
