### ISSUE TITLE
MapToXXXConverter in GeoConverters [DATAES-1002]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-elasticsearch#1574]
**[pcspapa](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50790)** opened **[DATAES-1002](https://jira.spring.io/browse/DATAES-1002?redirect=false)** and commented

GeoJson Type & Elasticsearch Type

https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#input-structure

type.equalsIgnoreCase()

 

 

---
No further details from [DATAES-1002](https://jira.spring.io/browse/DATAES-1002?redirect=false)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pcspapa** [comment]
Sorry for being very late.

* GeoJsonMultiPolygon.TYPE = "MultiPolygon";

* Elasticsearch type = "multipolygon"

```
 "hits" : [
      {
        "_index" : "boundary",
        "_type" : "_doc",
        "_id" : "3nn....",
        "_score" : 1.0,
        "_source" : {
          ...
          "coordinates" : {
            "coordinates" : [
              ....
            ],
            "type" : "multipolygon"
          }
          ...
        }
      },
```

So, Assert.isTrue(type.**equalsIgnoreCase**(GeoJsonMultiPolygon.TYPE), "does not contain a type 'MultiPolygon'");

Same for other types.

**Comment by sothawo** [comment]
done with #1655
