### ISSUE TITLE
updateByQuery how to use? plz

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [spring-projects/spring-data-elasticsearch#1636]
updateByQuery how to use? plz

**Comment by sothawo** [comment]
You might check how it is done in the tests: https://github.com/spring-projects/spring-data-elasticsearch/blob/master/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchTemplateTests.java#L1504-L1558

**Comment by sothawo** [comment]
If you have an document id to use in an update query, this functionality is implemented, see the above link.

Updating with a search query and no id is an open issue (#1446).
