### ISSUE TITLE
Add function to list all indexes

### ISSUE THREAD

**Issue by jbauerrfid** [spring-projects/spring-data-elasticsearch#1646]
Please add a function to list all indexes on the Elasticsearch host to `ReactiveElasticsearchClient.indices()`.

This should do the same as running `GET /_all` on the ES host, and return a Flux of index descriptions.

**Comment by jbauerrfid** [comment]
as a work around I build a query on top of .execute to fetch the index list:

```
esClient.execute(cb -> cb.get()
                .uri("/" + indexName)
                .accept(MediaType.APPLICATION_JSON)
                .exchange())
                .flatMap(cr -> {
                    if (clientResponse.statusCode() == HttpStatus.OK) {
                        return clientResponse.bodyToMono(ObjectNode.class);
                    }
                    return Mono.empty();
                })
                .flatMapIterable(o  -> {
                   // convert results and collect them into a Flux...
                }
```

it does its job, but it feels a bit weird to do a lot of special logic for a pretty basic task

**Comment by gpopides** [comment]
I tried to look at the code in order to grasp whats going on.

spring-data-elasticsearch uses response classes from elasticsearch library, so there is not a response which can represent the response of ```"/_all"``` endpoint.

I tried to map it my self but  i have troubles reading the response body from 
```java 
RawActionResponse
```

Any hint would be welcome, and then i could open a PR

**Comment by sothawo** [comment]
__all_  is just a special case of the [get index API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-get-index.html). 

We should have a new function in `IndexOperations` like `getInformation(IndexCoordinates)` (and a corresponding function in the reactive part). The parameter could then contain a single index name, multiple names or a name like __all_ or _*_. The return value could be a list of some new `IndexInformation` class that contains the information for one specific index.

To get the result for this call it is necessary to use a `GetIndexRequest` with the `RestHighlevelClient` with the corresponding index names. The `RestHighlevelClient`then returns a `org.elasticsearch.client.indices.GetIndexResponse` object which contains (taken from the code):

```
    private Map<String, MappingMetadata> mappings;
    private Map<String, List<AliasMetadata>> aliases;
    private Map<String, Settings> settings;
    private Map<String, Settings> defaultSettings;
    private Map<String, String> dataStreams;
    private String[] indices;

```
and the needed getter functions to retrieve the information for all the indices. This information should be used to build the  `IndexInformation` instances.

Building `GetIndexRequest` instances is already present in code, the mapping from a `GetIndexResponse` to the new classes not.

And  - as Elasticsearch 7 still does support the TransportClient - this must be added to Rest, Reactive and Transport implementations.
