### ISSUE TITLE
Aggregation "SearchResponse" results are no more returned

### ISSUE THREAD

**Issue by paolodedo** [spring-projects/spring-data-elasticsearch#1656]
Hello,

I am reporting a bug on Spring Data ES 4.1.2.

I was able, on 3.x version, to call "query" method and get back a **SearchResponse**, which made me able of, as a user, manipulating hits and aggregations without executing other queries or make other custom mappings, but passing through my custom mapper, i.e. **ResultExtractor**

```
return elasticsearchOperations.query(query.build(), response -> {

    SearchHit[] hits = response.getHits().getHits();

    .....
});
```

Now, with the new version, the "search" query result returns only SearchHits<T>, so that I am only able to retrieve aggregations without passing my custom mapper.

```
return elasticsearchOperations.search(
    query.build(),
    documentType,
    IndexCoordinates.of(getIndex())
);
```

**Comment by sothawo** [comment]
There is no bug. `ResultExtractor` has been removed in version 4.0. This was a design decision we made when rewriting the whole internal mapping to and from Elasticsearch data.

As for the aggregations: The search methods of the `SearchOperations` interface - for example 

    <T> SearchHits<T> search(Query query, Class<T> clazz, IndexCoordinates index);

return an object implementing the `org.springframework.data.elasticsearch.core.SearchHits` interface. This has a method `getAggregations()` which returns the aggregations. These are the native Elasticsearch aggregations returned from the `org.elasticsearch.action.search.SearchResponse`.

what functionality or custom mapping do you need besides the information returned in the `SearchHits`?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
