### ISSUE TITLE
ReactiveElasticsearchClient should use the same request parameters as non-reactive code

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#1658]
Currently the `ReactiveElasticsearchClient` uses old request classes for these operations:

* create index
* get index
* put mapping
* get mapping

We should add variants that accept the same request classes as Elasticsearch's RestHighlevelClient and deprecate the existing ones for later removal.

**Comment by ffaoudi** [comment]
Hy @sothawo i would like to propose a PR for this issue. I have question about naming, in `ReactiveElasticsearchClient`, the new default method `default Mono<Boolean> createIndex(Consumer<org.elasticsearch.client.indices.CreateIndexRequest> consumer)`  will clash with existing method `default Mono<Boolean> createIndex(Consumer<CreateIndexRequest> consumer)`, please can provide me a suggestion about naming the new method?

**Comment by sothawo** [comment]
skip the new one. Once the existing and then deprecated method is removed we can reintroduce the Consumer based method with the new parameter.

**Comment by gaborkr** [comment]
Is there any workaround for this other than using the non-reactive client for index-related operations?

(Using the old `.admin` based classes eg. `org.elasticsearch.action.admin.indices.create.CreateIndexRequest` (also included in `DefaultReactiveIndexOperations`) doesn't work on ES 7.x (7.10.1 for sure) - so I would classify this  as a bugfix and not an "enhancement"... as I found out while migrating from an older Spring Data / ES client version.)

**Comment by sothawo** [comment]
Adapting this changes the API of `ReactiveElasticsearchClient`, thus it is an enhancement and not a bugfix. This issue is worked upon and will be addressed.

Don't forget that Spring Data Elasticsearch is a community maintained project, there is no one working full time on this - and probably not in her payed working time.
