### ISSUE TITLE
ReactiveElasticsearchOperations indexName twice endcoding

### ISSUE THREAD

**Issue by wonwoo** [spring-projects/spring-data-elasticsearch#1665]
this example request

```java
public Mono<Void> example(Foo foo) {
   return reactiveElasticsearchOperations.save(foo, IndexCoordinates.of("<foo-{now/M{yyyy.MM}}>")).then()
}
``` 
webClient Request url 

Expecting : `/%3Cfoo-%7Bnow%2FM%7Byyyy.MM%7D%7D%3E/_doc`

but : `/%253Cfoo-%257Bnow%252FM%257Byyyy.MM%257D%257D%253E/_doc`

elasticsearch error log 
`reason=Invalid index name [%3Cfoo-%7Bnow%2FM%7Byyyy.MM%7D%7D%3E], must be lowercase]`

**Comment by sothawo** [comment]
_"<foo-{now/M{yyyy.MM}}>"_ is not a valid index name. The index name must be either a lowercases String or a SpEL (Spring Expression language) template expression. What do you want to achieve with the String you prvide?

**Comment by wonwoo** [comment]
i want Date math support in index names

https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

**Comment by sothawo** [comment]
Ok; didn't know that. I will need to investigate this and to try to reproduce it.

**Comment by sothawo** [comment]
ok, I can reproduce that. That reactive client escapes the '%' with '%25'. This does not happen in the non-reactive part.

**Comment by sothawo** [comment]
implemented in the current master and backported to 4.1.x and 4.0.x

**Comment by wonwoo** [comment]
@sothawo  good! Thank you
