### ISSUE TITLE
Couldn't find PersistentEntity for type class com.example.demo.dto.Address

### ISSUE THREAD

**Issue by quickiwiki** [spring-projects/spring-data-elasticsearch#1667]
Having some trouble the past few days with the new Spring data 4 Elasticsearch, I get " Couldn't find PersistentEntity for type class com.example.demo.dto.Address"?
Before spring data 4 Jackson Object Mapping could be used but now CustomConversion should be used instead. There is the official reference https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.mapping.meta-model.conversions providing an example converting from and to Address object.

I tried the example from the official reference and run into the problem. The demo project is included.
[demo_project.zip](https://github.com/spring-projects/spring-data-elasticsearch/files/5870157/demo_project.zip)

**Comment by sothawo** [comment]
The reason for this error is that by registering the custom converters, the `Address` class is considered a simple type (no special mapping needed, as there are converters for it). And simple type are no entities.

I don't know if a entity should be mappable by a custom converter; I'll check how this is handled in other Spring Data modules.  Maybe we need to find a way to add something like a custom _EntityConverter_

**Comment by sothawo** [comment]
Using `CustomConversions` for an entity should be possible. So this is a bug in Spring Data Elasticsearch.

**Comment by sothawo** [comment]
Please note that when using such an entity for a repository as you did in your example, the entity needs to have an `@Id` annotated property.
