### ISSUE TITLE
Writing a more complex CriteriaQuery

### ISSUE THREAD

**Issue by slyoldfox** [spring-projects/spring-data-elasticsearch#1668]
Following the post and looking at the issue #1278 I am trying to write a "complex" CriteriaQuery

@sothawo
I am on spring-data-elasticsearch 4.1.2 - has #1278 been implemented there?

I am trying to write a CriteriaQuery with semantics:

(firstName = 'A' and lastName = 'B') or ( firstName = 'C' and lastName = 'D' ) - where each record is presented by their tuples, so I expect 2 records.

I have tried:

```
Criteria one = Criteria.where("firstName").is( "A" ).and( "lastName" ).is( "B" );
Criteria two = Criteria.where( "firstName" ).is( "C" ).and( "lastName" ).is( "D" );
Criteria oneOrTwo = Criteria.and().or( one ).or( two );
```
This yields me correct number of rows however the criteriaChains seems to only match on lastName (firstName seems forgotten)

I have also tried:

```
Criteria one = Criteria.where("firstName").is( "A" ).and( "lastName" ).is( "B" );
Criteria two = Criteria.where( "firstName" ).is( "C" ).and( "lastName" ).is( "D" );
Criteria oneOrTwo = one.or( two );
```

This yields only the "one" record.

I also tried:

```
Criteria.and().subCriteria(  Criteria.or().subCriteria( one ).subCriteria( two ) )
```

This yields me correct results.
However when passing an object as Date value, these subCriteria values do not get converted by `MappingElasticsearchConverter.updateCriteria()`.

This is because there is no criteriaChain - just subCriteria's and thus the following function bails out ?
```
	@Override
	public void updateCriteriaQuery(CriteriaQuery criteriaQuery, Class<?> domainClass) {
		ElasticsearchPersistentEntity<?> persistentEntity = mappingContext.getPersistentEntity(domainClass);

		if (persistentEntity != null) {
			for (Criteria chainedCriteria : criteriaQuery.getCriteria().getCriteriaChain()) {
				updateCriteria(chainedCriteria, persistentEntity);
			}
		}
	}
```

Is this possible that this case is not correctly implemented, or am I just doing it wrong.
In case this is a bug, could you/we add documentation on how more complex queries like this need to be handled with CriteriaQuery?

**Comment by sothawo** [comment]
As for the nested query:

```java
Criteria one = new Criteria("firstName").is("A").and("lastName").is("B");
Criteria two = new Criteria("firstName").is("C").and("lastName").is("D");

Criteria criteria = Criteria.or().subCriteria(one).subCriteria(two);
```

> However when passing an object as Date value…

where do you pass a date value? What does your entity class look like with what which `@Field` annotations and where do  you pass which kind of Date?

**Comment by slyoldfox** [comment]
Thank you for your suggestion, I've compiled a small test project to illustrate the situation.
[elastic.zip](https://github.com/spring-projects/spring-data-elasticsearch/files/5878748/elastic.zip)

As far as I can understand, I'm doing this as you suggested?

When starting the application with `mvn spring-boot:run` - it should fail on `search4`.

When I look at the generated bool query, the `searchRequest.source` structure (should/must) seems correct, only the date parameter value is not converted.

When the `RequestFactory.searchRequest()` is called, the `updateQuery` is indeed called. But the CriteriaQuery for `search4` does not have a filterchain on the first `Criteria.and()` and so the `updateCriteriaQuery()` method bails out and the date parameter is never converted (unless that happens somewhere else where I haven't figured it out?).

So I'm wondering if the `updateCriteriaQuery` should also contain a loop for `Criteria.getSubCriteria()`. 

This loop actually exists in the `updateCriteria` method (on the bottom) but is never reached. Maybe that should be factored up in the calling `updateCriteriaQuery` method to fix this?

**Comment by slyoldfox** [comment]
To elaborate on the example, some more findings (I am not sure how correct they are or what the default behaviour should be).

A Date object with `.is()` which is added as a .subCriteria from `Criteria.and()` as this: `Criteria.and().subCriteria( Criteria.where("createdDate").is( new Date() )` will be mapped to a `queryStringQuery()` and resort to `value.toString()` in `CriteriaQueryProcessor` - this probably shouldn't occur because I assume it should have already been converted by the `mappingElasticsearchConverter`

This is a failing test case which based on your existing unit test:
```
	@Test
	// DATAES-1668
	void shouldMapNamesAndConvertValuesInCriteriaQueryForSubCriteria() throws JSONException {

		// use POJO properties and types in the query building
		CriteriaQuery criteriaQuery = new CriteriaQuery( //
				Criteria.or()
						.subCriteria( Criteria.where("birthDate") //
						.between(LocalDate.of(1989, 11, 9), LocalDate.of(1990, 11, 9)) ) //
						.subCriteria( Criteria.where( "birthDate").is(LocalDate.of(2019, 12, 28)) ) //
		);

		// mapped field name and converted parameter
		String expected = "{\n" +
				"  \"bool\" : {\n" +
				"    \"should\" : [\n" +
				"      {\n" +
				"        \"bool\" : {\n" +
				"          \"must\" : [\n" +
				"            {\n" +
				"              \"range\" : {\n" +
				"                \"birthDate\" : {\n" +
				"                  \"from\" : \"1989-11-09\",\n" +
				"                  \"to\" : \"1990-11-09\",\n" +
				"                  \"include_lower\" : true,\n" +
				"                  \"include_upper\" : true,\n" +
				"                  \"boost\" : 1.0\n" +
				"                }\n" +
				"              }\n" +
				"            }\n" +
				"          ],\n" +
				"          \"adjust_pure_negative\" : true,\n" +
				"          \"boost\" : 1.0\n" +
				"        }\n" +
				"      },\n" +
				"      {\n" +
				"        \"bool\" : {\n" +
				"          \"must\" : [\n" +
				"            {\n" +
				"              \"match\" : {\n" +
				"                \"birthDate\" : {\n" +
				"                  \"query\" : \"2019-12-28\",\n" +
				"                  \"operator\" : \"AND\",\n" +
				"                  \"prefix_length\" : 0,\n" +
				"                  \"max_expansions\" : 50,\n" +
				"                  \"fuzzy_transpositions\" : true,\n" +
				"                  \"lenient\" : false,\n" +
				"                  \"zero_terms_query\" : \"NONE\",\n" +
				"                  \"auto_generate_synonyms_phrase_query\" : true,\n" +
				"                  \"boost\" : 1.0\n" +
				"                }\n" +
				"              }\n" +
				"            }\n" +
				"          ],\n" +
				"          \"adjust_pure_negative\" : true,\n" +
				"          \"boost\" : 1.0\n" +
				"        }\n" +
				"      }\n" +
				"    ],\n" +
				"    \"adjust_pure_negative\" : true,\n" +
				"    \"boost\" : 1.0\n" +
				"  }\n" +
				"}"; //

		mappingElasticsearchConverter.updateQuery(criteriaQuery, Person.class);
		String queryString = new CriteriaQueryProcessor().createQuery(criteriaQuery.getCriteria()).toString();

		assertEquals(expected, queryString, false);
	}
```
