### ISSUE TITLE
Consider Document as simple type

### ISSUE THREAD

**Issue by crazyjurich** [spring-projects/spring-data-elasticsearch#1675]
Adding spring-data-elasticsearch to spring project causes multiple warnings in app log, like:
`o.s.d.c.CustomConversions - Registering converter from class org.springframework.data.elasticsearch.core.geo.GeoJsonMultiPoint to interface java.util.Map as writing converter although it doesn't convert to a store-supported type! You might want to check your annotation setup at the converter implementation.`
More log lines here: [log.txt](https://github.com/spring-projects/spring-data-commons/files/5902605/log.txt)

First of all app shouldn't behave like this, especially considering these converters are not used. And secondly, error message looks irrelevant for me, looks like it was initially created for user converters.

Related classes are:
org/springframework/data/convert/CustomConversions.java
org/springframework/data/elasticsearch/core/convert/ElasticsearchCustomConversions.java

Workaround: https://stackoverflow.com/questions/60001034/how-to-remove-spring-data-customconversions-warnings-from-application-startup

Related issue: https://github.com/spring-projects/spring-data-commons/issues/2043

**Comment by mp911de** [comment]
Part of the solution is contributed by #1676.

**Comment by sothawo** [comment]
closed with #1677
