### ISSUE TITLE
Errors are silent in multiGet

### ISSUE THREAD

**Issue by efreeti** [spring-projects/spring-data-elasticsearch#1678]
When executing the multiGet request Elasticsearch client does provide a failure information per each entry. For some not very clear reason to me the implementation for ReactiveElasticsearchClient (and I think ElasticsearchClient too) is silenting those in the same way as non existing entries - https://github.com/spring-projects/spring-data-elasticsearch/blob/master/src/main/java/org/springframework/data/elasticsearch/client/reactive/DefaultReactiveElasticsearchClient.java#L352

It is not clear to me why this is a desired behaviour. This also makes it impossible to use multiGet from Spring Data layer and handle errors. It is also not very easy to override this behaviour by extending the class - a lot of used utility methods are private.

It would really be useful to not force this and either change the behaviour of client or at least add option to prevent this.

**Comment by sothawo** [comment]
Best would be to return a `Flux<MultiGetItemResponse>` and not filtering out the failed responses and let the user filter the failed responses; at least for the `ReactiveElasticsearchClient`. The `ReactiveElasticsearchTemplate` might keep filtering these invalid values as on this level we return entities. Perhaps we need to introduce something like a `GetResult<T>` to model this.

The non-reactive code returns `null` for failed documents, which is non possible in a `Flux`, I think that is the reason why they were skipped in the current implementation.
