### ISSUE TITLE
Errors are silent in delete by query in ReactiveElasticsearchTemplate

### ISSUE THREAD

**Issue by efreeti** [spring-projects/spring-data-elasticsearch#1679]
One the level of ReactiveElasticsearchClient the deleteBy method returns BulkByScrollResponse which in itself contains a list of failures during the search or delete phase. On the level of ReactiveElasticsearchTemplate though those failures are ignored and only totals are extracted - https://github.com/spring-projects/spring-data-elasticsearch/blob/master/src/main/java/org/springframework/data/elasticsearch/core/ReactiveElasticsearchTemplate.java#L535

This makes it impossible to catch failures during the delete phase on the level of ReactiveElasticsearchOperations unless you extend that class and override that behaviour. The affected count on it's own is not enough to make conclusions if there are errors so it's pretty leaky abstraction. I combination with multiGet giving no possibility to detect errors it makes automation of bulk updates/removals quite unstable.

**Comment by sothawo** [comment]
Seems to make more sense to return the information from the `BulkByScrollResponse` in a new return type instead of a `Mono<Long>`.
