### ISSUE TITLE
Add support for point_in_time search API

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#1684]
Spring Data Elasticsearch should support the [point in time (PIT) API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/point-in-time-api.html). 

This is needed together with search_after (#1143) to redesign paging through large result sets, which currently is done with the scroll API, but Elasticsearch recommends using search_after and pit.

**Comment by mateuszwinnicki** [comment]
As search_after is already in repo, can you tell when PIT will be also supported?

**Comment by sothawo** [comment]
No. I'm currently working on a different issue. This will probably be one of the next issues to address.

Keep in mind that Spring Data Elasticsearch is a community maintained project, I am doing this as well in my private time after work, and so the resources are limited.

**Comment by mateuszwinnicki** [comment]
Sure, I know that :) thanks

**Comment by sothawo** [comment]
The Elasticsearch `RestHighLevelClient` does not yet (version 7.12.1) support the calls to open or close point in time. This was just recently merged into Elasticsearch master (https://github.com/elastic/elasticsearch/issues/70593). 
We have to wait for this to be available in the libraries.

**Comment by xhaggi** [comment]
This is supported since version 7.14 of the Java client.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.14/java-rest-high-point-in-time.html

**Comment by mateuszwinnicki** [comment]
When 7.14 will be released? I can't find any dates unfortunately

**Comment by sothawo** [comment]
7.14 is not released yet. When it will be, I don't know, only Elasticsearch knows that.

**Comment by xhaggi** [comment]
My comment was only meant as an indication of when this problem might be resolved.

**Comment by AntonLGVS** [comment]
Version 7.15 has been released. What do you think can unlock the issue? [ElasticSearch releases](https://github.com/elastic/elasticsearch/releases)

**Comment by sothawo** [comment]
I am currently working on integrating the new Elasticsearch client (which is not released yet from Elasticsearch ) as an alternative to the current `RestHighLevelClient`. This will be the main change in 4.4.  Adding new features will be done after this change/migratin, so it might take some more time.
