### ISSUE TITLE
Add missing "Document ranking types"

### ISSUE THREAD

**Issue by mdgilene** [spring-projects/spring-data-elasticsearch#1700]
As of ES 7.11 these types are now finalized and should be added.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html#document-ranking-types

Missing types include:
- dense_vector
- sparse_vector
- rank_feature
- rank_features

**Comment by sothawo** [comment]
Note: _rank_feature types_ already were implemented and _spares_vector_ is deprecated, so only _dense_vector_ is added,
