### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by kinsey-jian** [spring-projects/spring-data-elasticsearch#1706]
Spring data elasticsearch occasionally an error is reported

Caused by: java.io.IOException: Connection reset by peer
at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:964)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1765)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1735)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1697)
at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:999)
at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.update(ElasticsearchRestTemplate.java:718)

I found this class  org.springframework.data.elasticsearch.client.RestClients

builder.setHttpClientConfigCallback((clientBuilder) -> {
            Optional<SSLContext> sslContext = clientConfiguration.getSslContext();
            Optional<HostnameVerifier> hostNameVerifier = clientConfiguration.getHostNameVerifier();
            sslContext.ifPresent(clientBuilder::setSSLContext);
            hostNameVerifier.ifPresent(clientBuilder::setSSLHostnameVerifier);
            if (ClientLogger.isEnabled()) {
                RestClients.HttpLoggingInterceptor interceptor = new RestClients.HttpLoggingInterceptor();
                clientBuilder.addInterceptorLast(interceptor);
                clientBuilder.addInterceptorLast(interceptor);
            }

            Duration connectTimeout = clientConfiguration.getConnectTimeout();
            Duration timeout = clientConfiguration.getSocketTimeout();
            Builder requestConfigBuilder = RequestConfig.custom();
            if (!connectTimeout.isNegative()) {
                requestConfigBuilder.setConnectTimeout(Math.toIntExact(connectTimeout.toMillis()));
                requestConfigBuilder.setConnectionRequestTimeout(Math.toIntExact(connectTimeout.toMillis()));
            }

            if (!timeout.isNegative()) {
                requestConfigBuilder.setSocketTimeout(Math.toIntExact(timeout.toMillis()));
            }

            clientBuilder.setDefaultRequestConfig(requestConfigBuilder.build());
            clientConfiguration.getProxy().map(HttpHost::create).ifPresent(clientBuilder::setProxy);

           **// I need to add this line of code here
            clientConfiguration.setKeepAliveStrategy(CustomConnectionKeepAliveStrategy.INSTANCE);**

            return clientBuilder;
        });

This class is missing KeepAliveStrategy setting,I hope you can add it

**Comment by sothawo** [comment]
From version 4.2 on (currently available as milestone release 4.2.0-M4, planned to be released mid April 2021) there is a configuration hook available (see [the documentation](https://docs.spring.io/spring-data/elasticsearch/docs/4.2.0-M4/reference/html/#elasticsearch.clients.configuration))

```java
@Configuration
public class RestClientConfig extends AbstractElasticsearchConfiguration {

    @Override
    @Bean
    public RestHighLevelClient elasticsearchClient() {

        HttpHeaders defaultHeaders = new HttpHeaders();
        defaultHeaders.add("header-name", "header-value");
        ClientConfiguration clientConfiguration = ClientConfiguration.builder() //
            .connectedTo("localhost:9200") //
            .withHttpClientConfigurer(clientBuilder -> {
                clientBuilder.setKeepAliveStrategy(CustomConnectionKeepAliveStrategy.INSTANCE);
                return clientBuilder;
            })
            .build();

        return RestClients.create(clientConfiguration).rest();
    }
}
```

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
