### ISSUE TITLE
Creating an Elasticseearch index with index sorting via Spring annotation

### ISSUE THREAD

**Issue by strokine** [spring-projects/spring-data-elasticsearch#1716]
I'm using Spring Data for Elasticsearch. I need to create an index with an index sorting as it is [described here](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/index-modules-index-sorting.html)

There is no way to define a POJO field to be used as [a sorting field during indexing](https://stackoverflow.com/questions/66432489)

Reply from P.J.Meisch:
_Currently this is not possible. Index sorting must be defined when the index is created, and as it is currently possible to define a json file with index settings and add that with @Setting to the entity, this fails in this case. The reason is, that when an index sorting is defined, the corresponding field must be defined in the mappings definition on index creation as well. Spring Data Elasticsearch first creates the index with the settings and after that it writes the mappings - which then is too late._

**Comment by sothawo** [comment]
Note.: This is basically a two step thing:
1. add a method `IndexOperations.createWithMapping()` (different variants for providing mapping and settings) that will create an index with settings and mappings in one single call. This is needed for being able to have index sorting and would rely on the setting being provided as a json file (like it is actually already possible).
2. Extend the existing `@Setting` annotation to take settings parameters, for example the index sorting values. We could also move the existing index settings parameters from the `@Document` annotation. This would allow for a configuration without using json files.

**Comment by sothawo** [comment]
~#1718~ and ~#1719~ are implemented, it now is possible to define the settings like this:

```java 
@Document(indexName = "entities")
@Setting(
  sortFields = { "secondField", "firstField" },
  sortModes = { Setting.SortMode.max, Setting.SortMode.min },
  sortOrders = { Setting.SortOrder.desc, Setting.SortOrder.asc },
  sortMissingValues = { Setting.SortMissing._last, Setting.SortMissing._first })
class Entity {
    @Nullable
    @Id private String id;

    @Nullable
    @Field(type = FieldType.Keyword)
    private String firstField;

    @Nullable @Field(type = FieldType.Keyword)
    private String secondField;

    // getter and setter...
}

```

will be contained in the next release 4.2.0.RC1
