### ISSUE TITLE
i use elasticsearchRestTemplate for query,but mucket a type problem

### ISSUE THREAD

**Issue by yclnycl** [spring-projects/spring-data-elasticsearch#1720]
my workspace:
elastsearch: 7.11
java: open jdk 11
springboot: 2.4.x

i use terms for query, return string key, example 

```    "aggregations": {
        "path_group": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "pages/activity/activePage/activePage",
                    "doc_count": 10187,
                    "uv": {
                        "value": 4896
                    }
                }]}}
```

no problem in elasticsearch, but use java api throw an exception "For input string", i see source code,

```
        public Number getKeyAsNumber() {
            if (key != null) {
                return Double.parseDouble(key.utf8ToString());
            }
            return null;
        }
```
the key is directly converted,how to solve this problem

**Comment by sothawo** [comment]
How is this related to Spring Data Elasticsearch?

But it seems that you have a key _"pages/activity/activePage/activePage"_  which is a `String`and want to convert this to a `Number`?

**Comment by yclnycl** [comment]
> How is this related to Spring Data Elasticsearch?
> 
> But it seems that you have a key _"pages/activity/activePage/activePage"_ which is a `String`and want to convert this to a `Number`?

sorry is not Spring Data Elasticsearch, I have found the right way feedback
