### ISSUE TITLE
Add support for SearchTemplate for reactive client

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-data-elasticsearch#1725]
Hello,
it would be nice to be able to extend `DefaultReactiveElasticsearchClient` when it's needed to write some custom queries. For example now I'd like to implement [search template](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html) however it's not that easy because of private methods `sendRequest`. Could we change those to protected instead of private?

Or is there any other extension point that I've missed? I'd like to use search templates.

Thanks

**Comment by sothawo** [comment]
I think we could make the three `sendRequest()` method protected. Although the better solution would be to add _search template_ support by submitting a PR ;-)
