### ISSUE TITLE
Support naming strategy between ES index mapping and Java object

### ISSUE THREAD

**Issue by weweibuy** [spring-projects/spring-data-elasticsearch#1729]
Sometimes ES index mapping naming strategy is SNAKE_CASE like: 
    `{
      "mapping": {
        "properties": {
          "customer_id": {
            "type": "long"
          },
          "order_no": {
            "type": "keyword"
          }
        }
      }
    }`
but Java object is LOWER_CAMEL_CASE like: 

    `public class Order {
    
            private Long customerId;
    
            private String orderNo;
        }`
In spring-data-elasticsearch 3x,  we  can use `@JsonNaming`  or  replace implements  of  `org.springframework.data.elasticsearch.core.EntityMapper`  with SNAKE_CASE naming strategy ObjectMapper  to map or read Java object;

In future spring-data-elasticsearch , Can it support: 

-  config  global  naming strategy between ES index mapping and Java object
-  customized config  for each ES index, like `@JsonNaming` in spring-data-elasticsearch 3x

**Comment by sothawo** [comment]
Implemented with ~#1565~, available since version 4.2.0.M3

**Comment by sothawo** [comment]
additional info: this is an application wide configuration currently. To have it configurable for individual entites would be something new.
