### ISSUE TITLE
Pass field naming strategy trough parameters

### ISSUE THREAD

**Issue by reket** [spring-projects/spring-data-elasticsearch#1732]
Hi!

I saw some updates regarding naming strategy configuration here https://github.com/spring-projects/spring-data-elasticsearch/commit/e311df98c0807d62c90b96a450a93ac7b90d5bbd 

It's grate update that I was waiting for a long time.

In Spring Data Mongo you can simply pass parameter and value in application.properties or application.yml 

`spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy`

I think this would be very useful to have same functionality in Spring Data Elastisearch. Thanks!

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not consider or use configuration files. These are used by Spring Boot to configure Spring Data Elasticsearch when doing autoconfiguration. So this is a request to address at Spring Boot (https://github.com/spring-projects/spring-boot)
