### ISSUE TITLE
Readme lists artifacts with .RELEASE and .BUILD-SNAPSHOT suffixes

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-elasticsearch#1738]

**Comment by sothawo** [comment]
Do you mean the section about how to use SNAPSHOT and RC builds?

**Comment by mp911de** [comment]
Yes, see https://github.com/spring-projects/spring-data-commons/commit/912d89f40d234f5b1c5fa9257771576442c6d941 for the fix in commons.
