### ISSUE TITLE
SearchTemplateResponse 

### ISSUE THREAD

**Issue by wanglong1992** [spring-projects/spring-data-elasticsearch#1742]
org.elasticsearch.script.mustache.SearchTemplateResponse , 
I found that 'spring-data-elasticsearch' did not support this function, how can I to handle this Responce.
[java-rest-high-search-template](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-search-template.html)

**Comment by sothawo** [comment]
Support for SearchTemplates is not yet supported in Spring Data Elasticsearch. For non-reactive code you need to use the `RestHighLevelClient` directly. For the reactive code, the `ReactiveElasticsearchClient` supports issuing a search template request for a search, but not managing search templates.

**Comment by wanglong1992** [comment]
OK,thank you



> Support for SearchTemplates is not yet supported in Spring Data Elasticsearch. For non-reactive code you need to use the `RestHighLevelClient` directly. For the reactive code, the `ReactiveElasticsearchClient` supports issuing a search template request for a search, but not managing search templates.
