### ISSUE TITLE
spring data elasticsearch how to create text field with child keyword field

### ISSUE THREAD

**Issue by fageiguanbing** [spring-projects/spring-data-elasticsearch#1743]
spring data elasticsearch version: 2.4.1

when I use `@Field(type = FieldType.Text)`, spring data will create a text field, but I also want to create a child keyword field. Like this:
```json
{
    "text_field":{
        "type":"text",
        "fields":{
            "keyword":{
                "type":"keyword"
            }
        }
    }
}
```

**Comment by sothawo** [comment]
Same answer as in the StackOverflow question:

There never was a version 2.4.1 of Spring Data Elasticsearch, I assume you mean Spring Boot 2.4.1? If so, that would use Spring Data Elasticsearch 4.1.2

What you'd need define would be

```java
@MultiField(mainField = @Field(type = FieldType.Text),
   otherFields = { @InnerField(suffix = "keyword", type = FieldType.Keyword) })
private String text_field;
```

**Comment by fageiguanbing** [comment]
> Same answer as in the StackOverflow question:
> 
> There never was a version 2.4.1 of Spring Data Elasticsearch, I assume you mean Spring Boot 2.4.1? If so, that would use Spring Data Elasticsearch 4.1.2
> 
> What you'd need define would be
> 
> ```java
> @MultiField(mainField = @Field(type = FieldType.Text),
>    otherFields = { @InnerField(suffix = "keyword", type = FieldType.Keyword) })
> private String text_field;
> ```

Thank you!!! Because I haven't seen any introduction in [Spring Data Elastisearch document](https://docs.spring.io/spring-data/elasticsearch/docs/4.1.6/reference/html/#reference), you could think about adding it.
