### ISSUE TITLE
error while mapping _source.id

### ISSUE THREAD

**Issue by lemosintelipost** [spring-projects/spring-data-elasticsearch#1764]
I need to map the `id` field inside the elasticsearch `_source` field. 
However, in all my attempts, the JPA parse returns the `_id` field to me.
as I have tens of millions of records in ES and it is not possible to arrive and go through all the docs correcting the name of the `id` field by another. So I need an option to map it, as it differs from the `_id` field.

**Comment by sothawo** [comment]
can you provide an example Elasticsearch document and an entity class showing which fields you want to map to which property, and what should be the id for the entity?

btw, Spring Data Elasticsearch has nothing to do with JPA.

**Comment by lemosintelipost** [comment]
public class Quote extends QuotationInput implements Serializable { 
        private String originZipCode;
        private String destinationZipCode;
        private String platform;
        private QuoteAdditionalInformation additionalInformation;
        private QuoteIdentification identification;

        @Id
        private String _id;

        // id inside _source
        @Field("id")
        private Long quoteId;
        private Integer clientId;
        private String clientName;

        private DateTime created;
        private List<QuoteDeliveryOption> deliveryOptions;
        private List<QuoteVolume> volumes;

        private Set<Integer> skuGroupIds;
        private double costOfGoods;
        private double totalWeight;
        private double cubicVolume;
        private boolean cached;

        @JsonProperty("@timestamp")
        private LocalDateTime timestamp;

        //não consta no payload de exemplo
        private String calculationLog;
        @JsonIgnore private List<QuoteDeliveryOption> originalDeliveryOptions;
    }

**Comment by sothawo** [comment]
please check https://github.com/spring-projects/spring-data-elasticsearch/issues/1680#issuecomment-772787473

**Comment by lemosintelipost** [comment]
I implemented it this way, and I had this error:

`nested exception is org.springframework.data.mapping.MappingException: Attempt to add id property private java.lang.String br.com.intelipost.ipquoteservices.infra.repository.Quote.documentId but already have property private java.lang.String br.com.intelipost.ipquoteservices.infra.repository.Quote.elasticId registered as id`

I'm using version 4.1.7

**Comment by sothawo** [comment]
The change from ~#1680~ is in the _main_ (4.2) branch which will be released this month.

**Comment by sothawo** [comment]
version 4.2.0 was released a couple of days ago, with this version you can use the definitions from above.
