### ISSUE TITLE
How to transfer CriteriaQuery to QueryBuilder

### ISSUE THREAD

**Issue by fageiguanbing** [spring-projects/spring-data-elasticsearch#1765]
There are some problems to use CriteriaQuery API.
Such as nested query.

So, I found `org.springframework.data.elasticsearch.core.convert.MappingElasticsearchConverter#updateCriteria`. Are there any other APIs for me to use?

Thanks!

**Comment by sothawo** [comment]
What problems? We recently had some fixes for building (nested) queries for entities containing object or nested properties (~#1753~, ~#1758~ and ~#1768~)

There is no method to convert a `CriteriaQuery` - or any other `Query` implementation to a `QueryBuilder`, why should there be one?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by fageiguanbing** [comment]
> What problems? We recently had some fixes for building (nested) queries for entities containing object or nested properties (~#1753~, ~#1758~ and ~#1768~)
> 
> There is no method to convert a `CriteriaQuery` - or any other `Query` implementation to a `QueryBuilder`, why should there be one?

Thanks for your reply.

I got the solution of the nested query from [#1753](https://github.com/spring-projects/spring-data-elasticsearch/issues/1753).

But how do I create a nested sort? I used `org.springframework.data.domain.PageRequest` to try to solve this problem but only creates a simple sort.

**Comment by sothawo** [comment]
Nested sorts are not yet supported by Spring Data Elasticsearch. Please create a new issue for this.

**Comment by fageiguanbing** [comment]
OK, I will.

That's why I asked about the issue. In the future, Elasticsearch will be updated with many new APIs, but Spring-Data-Elasticsearch was not upgraded in time, if I can get QueryBuilder(or SourceBuilder), this will have better applicability.

Some scenarios can be implemented with Spring-Data-Elasticsearch, and some unsupported scenarios can be implemented with QueryBuilder.

**Comment by sothawo** [comment]
There are `NativeSearchQuery`and `NativeSearchQueryBuilder` where you can set query, filter and sort by using the original Elasticsearch query and sort builder and then create a `Query` that can be given to `ElasticsearchOperations` - for all those cases where `CriteriaQuery`or `StringQuery` are not enough.
