### ISSUE TITLE
Blocking call using ReactiveElasticsearchClient

### ISSUE THREAD

**Issue by Leuteris** [spring-projects/spring-data-elasticsearch#1769]
Blocking calls are reported by Reactor BlockHound in the following `ReactiveElasticsearchClient` methods:
```
ReactiveElasticsearchClient::search(SearchRequest searchRequest)
ReactiveElasticsearchClient::count(SearchRequest searchRequest)
ReactiveElasticsearchClient::update(UpdateRequest updateRequest)
```

**Query documents using `ReactiveElasticsearchClient`:**
```
                QueryBuilder queryBuilder = ...
	        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
		searchSourceBuilder.query(queryBuilder);

		SearchRequest searchRequest = new SearchRequest();
		searchRequest.indices(INDEX);
		searchRequest.source(searchSourceBuilder);

		return client.search(searchRequest)
				.map(searchHit -> new ProfileResponse(searchHit.getId(), UserIdentifierType.MSISDN,
						searchHit.getSourceAsMap()));
```

**Client configuration:**
```
	@Bean
	public ReactiveElasticsearchClient reactiveElasticsearchClient() {
		ClientConfiguration clientConfiguration = ClientConfiguration.builder()
				.connectedTo(elasticsearchEndpoints)
				.withWebClientConfigurer(webClient -> {
					ExchangeStrategies exchangeStrategies = ExchangeStrategies.builder()
							.codecs(configurer -> configurer.defaultCodecs()
									.maxInMemorySize(-1))
							.build();
					return webClient.mutate().exchangeStrategies(exchangeStrategies).build();
				})
				.build();

		return ReactiveRestClients.create(clientConfiguration);
	}
```
**Stacktrace:**

> reactor.blockhound.BlockingOperationError: Blocking call! java.io.RandomAccessFile#readBytes
> 	at java.base/java.io.RandomAccessFile.readBytes(RandomAccessFile.java)
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
> 	reactor.core.publisher.Mono.flatMap
> 	org.springframework.web.reactive.result.method.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:137)
> Error has been observed at the following site(s):
> 	|_           Mono.flatMap ⇢ at org.springframework.web.reactive.result.method.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:137)
> 	|_                        ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.lambda$handle$1(RequestMappingHandlerAdapter.java:199)
> 	|_             Mono.defer ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:199)
> 	|_              Mono.then ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:199)
> 	|_          Mono.doOnNext ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:200)
> 	|_          Mono.doOnNext ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:201)
> 	|_             Mono.error ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handleException(RequestMappingHandlerAdapter.java:235)
> 	|_                        ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.lambda$handle$0(RequestMappingHandlerAdapter.java:195)
> 	|_     Mono.onErrorResume ⇢ at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerAdapter.handle(RequestMappingHandlerAdapter.java:202)
> 	|_                        ⇢ at org.springframework.web.reactive.DispatcherHandler.lambda$handle$1(DispatcherHandler.java:153)
> 	|_           Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:153)
> 	|_           Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_     Mono.switchIfEmpty ⇢ at org.springframework.security.web.server.authorization.AuthorizationWebFilter.filter(AuthorizationWebFilter.java:55)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_     Mono.onErrorResume ⇢ at org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter.filter(ExceptionTranslationWebFilter.java:44)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_              Mono.then ⇢ at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
> 	|_     Mono.switchIfEmpty ⇢ at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
> 	|_               Mono.map ⇢ at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:62)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.authentication.logout.LogoutWebFilter.filter(LogoutWebFilter.java:63)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter.lambda$filter$1(ServerRequestCacheWebFilter.java:39)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter.filter(ServerRequestCacheWebFilter.java:39)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter.filter(SecurityContextServerWebExchangeWebFilter.java:38)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_              Mono.then ⇢ at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:113)
> 	|_     Mono.switchIfEmpty ⇢ at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:113)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:114)
> 	|_     Mono.onErrorResume ⇢ at org.springframework.security.web.server.authentication.AuthenticationWebFilter.filter(AuthenticationWebFilter.java:115)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_ Mono.subscriberContext ⇢ at org.springframework.security.web.server.context.ReactorContextWebFilter.filter(ReactorContextWebFilter.java:47)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.security.web.server.header.HttpHeaderWriterWebFilter.filter(HttpHeaderWriterWebFilter.java:44)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_ Mono.subscriberContext ⇢ at org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter.filter(ServerHttpSecurity.java:2859)
> 	|_             checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.web.server.handler.FilteringWebHandler.handle(FilteringWebHandler.java:59)
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.security.web.server.WebFilterChainProxy.lambda$filter$4(WebFilterChainProxy.java:56)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:56)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_       Mono.doOnSuccess ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:78)
> 	|_         Mono.doOnError ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:79)
> 	|_ Mono.transformDeferred ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:73)
> 	|_             checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
> 	|_                        ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:120)
> 	|_             Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:119)
> 	|_                        ⇢ at org.springframework.web.server.handler.FilteringWebHandler.handle(FilteringWebHandler.java:59)
> 	|_                        ⇢ at org.springframework.web.server.handler.WebHandlerDecorator.handle(WebHandlerDecorator.java:56)
> 	|_             Mono.error ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
> 	|_             checkpoint ⇢ HTTP POST "/profiles/api/v1/profile/query" [ExceptionHandlingWebHandler]
> 	|_                        ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler.lambda$handle$0(ExceptionHandlingWebHandler.java:77)
> 	|_     Mono.onErrorResume ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
> Stack trace:
> 		at java.base/java.io.RandomAccessFile.readBytes(RandomAccessFile.java)
> 		at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:408)
> 		at java.base/java.io.RandomAccessFile.readFully(RandomAccessFile.java:472)
> 		at java.base/java.util.zip.ZipFile$Source.readFullyAt(ZipFile.java:1281)
> 		at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:907)
> 		at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:923)
> 		at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:445)
> 		at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
> 		at java.base/java.io.InputStream.readNBytes(InputStream.java:503)
> 		at java.base/java.util.jar.JarFile.getBytes(JarFile.java:795)
> 		at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:985)
> 		at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:389)
> 		at java.base/java.util.jar.JarFile.getEntry(JarFile.java:503)
> 		at java.base/sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:131)
> 		at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:137)
> 		at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
> 		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1166)
> 		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1207)
> 		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1222)
> 		at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1266)
> 		at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1301)
> 		at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1386)
> 		at org.elasticsearch.common.xcontent.XContentBuilder.<clinit>(XContentBuilder.java:118)
> 		at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:362)
> 		at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:352)
> 		at org.springframework.data.elasticsearch.client.util.RequestConverters.createEntity(RequestConverters.java:897)
> 		at org.springframework.data.elasticsearch.client.util.RequestConverters.search(RequestConverters.java:407)
> 		at org.springframework.data.elasticsearch.client.reactive.DefaultReactiveElasticsearchClient.sendRequest(DefaultReactiveElasticsearchClient.java:568)
> 		at org.springframework.data.elasticsearch.client.reactive.DefaultReactiveElasticsearchClient.search(DefaultReactiveElasticsearchClient.java:423)
> 		at org.springframework.data.elasticsearch.client.reactive.ReactiveElasticsearchClient.search(ReactiveElasticsearchClient.java:416)
> 		at com.upstreamsystems.profiled.profiles.service.demo.DemoElasticService.queryUsers(DemoElasticService.java:201)
> 		at com.upstreamsystems.profiled.profiles.controller.v1.web.ProfileWebController.getUsersByQuery(ProfileWebController.java:77)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:146)
> 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
> 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
> 		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251)
> 		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336)
> 		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
> 		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:100)
> 		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
> 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
> 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
> 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
> 		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:295)
> 		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
> 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
> 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
> 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
> 		at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:469)
> 		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:261)
> 		at reactor.netty.channel.FluxReceive.request(FluxReceive.java:130)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
> 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
> 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onSubscribe(MonoCollect.java:103)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
> 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
> 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
> 		at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:168)
> 		at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:147)
> 		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
> 		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
> 		at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source)
> 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 		at java.base/java.lang.Thread.run(Unknown Source)

Is it safe to ignore the BlockHound? 
Version: 4.1.6
Java version: 15

**Comment by sothawo** [comment]
The `XContentBuilder` from Elasticsearch is used to convert between JSON and the Elasticsearch client classes. In it's initialization it scans for additional pluggable extensions - in the default Elasticsearch library it finds one, `XContentElasticsearchExtension`. This search uses the blocking code.

This is done in the class initialization exactly once. I think this could be ignored by BlockHound, @mp911de what do you think?

In my test applicaiton I end up with this setup:

```java
    static {
        BlockHound.install(
            builder -> builder.allowBlockingCallsInside("org.springframework.data.elasticsearch.support.VersionInfo", "logVersions"),
            builder -> builder.allowBlockingCallsInside("org.elasticsearch.Build", "<clinit>"),
            builder -> builder.allowBlockingCallsInside("org.elasticsearch.common.xcontent.XContentBuilder", "<clinit>")
        );
    }
```

Our own `VersionInfo` reads from a resource property; I will need to fix that for the reactive case.

**Comment by mp911de** [comment]
The calling root is `ServiceLoader`. I think that falls into the category of allowed calls since BlockHound doesn't report class loaders when reading class files from a Jar file so to me these two categories of calls seem the same. 

For reference, Blockhound excludes `ClassLoader` operations here: https://github.com/reactor/BlockHound/blob/6af0675c0ac221d5fc05c7aa4b9e6fa020bee539/agent/src/main/java/reactor/blockhound/BlockHound.java#L213-L228

So I think the issue should be addressed in BlockHound itself.
