### ISSUE TITLE
DefaultIndexOperations customization

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-data-elasticsearch#1784]
Please declare `org.springframework.data.elasticsearch.core.DefaultIndexOperations` as public, currently it's package protected and doesn't allow  to inherit and customize (rather than having custom class within `org.springframework.data.elasticsearch.core` which smells )

**Comment by sothawo** [comment]
What is the problem you have with the default implementation? What do you want to achieve that is not possible? 

It might be a problem which can be solved with the current implementation. If not, it might be something that is worth to be implemented in the `DefaultIndexOperations`.

Spring Data Elasticsearch is defined by its interfaces, and the provided implementations are to be considered internal.
I know that many other default implementations of interfaces in Spring Data Elasticsearch are public, but they should have never made public in the first place. 

The problem with making implementations public is, that with this visibility they are kind of belonging to the API and thus cannot be easily developed further and adapted or refactored without breaking classes that inherit from these implementations. 

So I think we will surely find a better solution than opening the visibility of this implementation class

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jvmlet** [comment]
We have some external preprocessor  that generates  the Documents and corresponding repositories classes.
Our requirements are :
1. Be able  to customize the mapping  definition and add **field aliases** based on some external configuration, achieved by overriding  the `buildMapping` method :

```java
@Override
    protected Document buildMapping(Class<?> clazz) {
        final Document document = super.buildMapping(clazz);
        addFieldAliases(document);
        return document;
    }
```

2.  Be able to specify index settings as runtime parameter, I'm aware about `@Mapping` annotation, but we also need to **validate** the settings at runtime. Achieved by :

```java
@Override
    protected boolean doCreate(IndexCoordinates index, @Nullable Document settings) {
//validate runtime parameters/properties and tweak the settings
}
```

**Comment by jvmlet** [comment]
Providing `Forwarding` implementation of  `IndexOperations`  interface on top of `DefaultIndexOperations` delegate might be the solution I think

**Comment by sothawo** [comment]
hm, `buildMapping(Class<?>)` has no derived implementations and is only called from `createMapping(Class<?>)`. Could be removed/moved into that method.

You could handle the mapping customization with a delegate like this:

```java
public class CustomIndexOperations implements IndexOperations {

    private final IndexOperations delegate;

    public CustomIndexOperations(IndexOperations delegate) {
        this.delegate = delegate;
    }

    // use the IDE to create all the delegating function implementations

    @Override
    public Document createMapping(Class<?> clazz) {
        var mapping = delegate.createMapping(clazz);
        // do something with mapping
        return mapping;
    }

    // many other delegating implementations
}
```

There further  are `IndexOperation.createMapping(Class<?>)` and `IndexOperations.createSetting(Class<?>)` which will return the corresponding data which could be modified and verified before passing them to `IndexOperations.create(settings, mapping)`.  I still do not see where it is necessary to make the implementation class public.

**Comment by sothawo** [comment]
what for? I we would provide a forwarding implementation that does nothing than call the delegate's methods, this adds nothing at all. If you would want to use this you would have to derive from that and reimplement methods from this delegating implementation. The you can just as easily implement such a delegator by yourself and directly add the functionality you need.

**Comment by jvmlet** [comment]
I would override only the methods I need to override, which makes my code cleaner. The maintainers of the interface usually provide the empty forwarding implementation, this is the approach followed in `guava` library

**Comment by sothawo** [comment]
If you need such a forwarding implementation it is easily created in any modern IDE with a couple of clicks. It might be a pattern that guava provides, but I am not aware of any Spring Data module or Spring itself where forwarding implementations are provided. And it probably makes sense in a library that provides many abstract classes like lists, maps, collections, etc. 
But I don't see an additional value adding it to Spring Data Elasticsearch.

**Comment by jvmlet** [comment]
On the other hand, spring and spring boot are flexible enough to allow to customize the interface implementation by inheriting default implementations. 
Anyway, thanks for your support and patience , I'll close this
