### ISSUE TITLE
Add support for automatic nodes detection in ReactiveElasticsearchClient 

### ISSUE THREAD

**Issue by zulk666** [spring-projects/spring-data-elasticsearch#1804]
Add functionality similar to elastic low level nodes sniffing.
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.12/_usage.html

When cluster have many nodes is difficult to provide right nodes list in application configuration, easier will be have automatic nodes detection.

**Comment by sothawo** [comment]
In the next version of Spring Data Elasticsearch  (5.0), the new Elasticsearch Client will be the default and a new Reactive Client is introduced. Both of these use the Elasticsearch low level `RestClient` under the hood and so for bot the imperative and the reactive style a Sniffer can be attached to the `RestClient`.
