### ISSUE TITLE
How to convert CriteriaQuery and NativeSearchQuery to raw ES query JSON?

### ISSUE THREAD

**Issue by ToffeeLu** [spring-projects/spring-data-elasticsearch#1808]
My requirement is serviceA->serviceB->ES.

service-A a building a query by the JSON of `CriteriaQuery or NativeSearchQuery` and send this query request by HTTP to service-B, then service-B will query ElasticSearch by the received request.

So what I want is service-A build query by `CriteriaQuery or NativeSearchQuery` which is more user-friendly than raw ES query.
On service-B, we receive the request then query ES by `StringQuery`

I only find this but it doesn't help. https://discuss.elastic.co/t/convert-searchsourcebuilder-to-json/156118

**Comment by sothawo** [comment]
Neither `CriteriaQuery` nor `NativeSearchQuery` have methods to directly create the Elasticsearch JSON representation of the query. This is built internally by Elasticsearch's `ReactiveElasticsearchClient`.

Even if you manage to create the ES query, sending this to a different service and then processing it with a `StringQuery` would be wrong as a `StringQuery` contains only the _query_ part, no filters or whatever might be contained JSON.

Why do you need your service B? Is this a proxy in front of Elasticsearch or does this have functionality of its own?

**Comment by ToffeeLu** [comment]
Or is there any function that could convert to `SearchSourceBuilder`?
I found `SearchSourceBuilder` can convert to raw ES JSON

**Comment by sothawo** [comment]
Even if you get the JSON from a `SearchSourceBuilder`: A `NativeSearchQuery` may contain a query, filters, highlight builders, aggregation, sort information, fields to retrieve, paging information;  all stuff that is not contained in the JSON the SearchSource which Spring Data Elasticsearch uses to build a `org.elasticsearch.action.search.SearchRequest` that is then passed on to the `RestHighLevelClient`. The `RestHighLevelClient` then builds the concrete HTTP request body together with the necessary parameters to pass in the URL (you would need to pass these as well from _A_ to _B_.

And if you manage to get all this information into _B_, you would then need to sent this with a plain HTTP client; where should the answer be parsed and converted into an entity? That could only be done on _A_.

So you should think about the design of your services again, Either you have one service which not only does the request and response setu togethe rwith auditing stuff, or your service _B_ should be just a http intercepting proxy operating on the plain http requests/responses.

**Comment by ToffeeLu** [comment]
Hi @sothawo , thanks for replying.
Our use case for service A is easy, only combination of filters, sort and pagination.
We want to provide a easy-level of query builder for service A, then B translate it to raw ES query and send to ES.
The blocker here is if A use a easy-level of query builder, how can B get it? serialization and deserialization is a problem.

**Comment by sothawo** [comment]
As I wrote Spring Data Elasticsearch does not create the JSON sent to Elasticsearch, it builds a `org.elasticsearch.action.search.SearchRequest` that is passed to the `org.elasticsearch.client.RestHighLevelClient.RestHighLevelClient`. The conversion to an HTTP request body is done by the Elasticsearch client library. And even if you convert a SourceBuilder to JSON, that would not contain filters, paging and sorting.

So it seems that Spring Data Elasticsearch is not the tool that might help you with your task.

**Comment by ToffeeLu** [comment]
So what spring did is `CriteriaQuery` -> `SearchRequest` -> ES lib -> ES service

We decide to create a customized simple query API contract for service A to use, and we convert it to `NativeSearchQuery` then send it to ES through Spring lib.

Thanks again. If I found more thing on serialization or deserialization about ES raw query, I will discuss with you and may contribute for converting in future.

**Comment by sothawo** [comment]
We won't expose ES raw queries, even if we would build them which we don't. Spring Data is about hiding away store specific implementation details, not exposing them.
