### ISSUE TITLE
InetSocketAddressParser fails to parse bracketed hosts with port

### ISSUE THREAD

**Issue by tarjanik** [spring-projects/spring-data-elasticsearch#1818]
Input address `[something:9200]` errorously gets parsed to host = `something:9200` port = `""`

This will cause the parsed address to have duplicated ports like `something:9200:9200` that will cause connection problems.

I guess in `InetSocketAddressParser.getHostAndPortFromBracketedHost(...)` 

`String host = hostPortString.substring(1, closeBracketIndex);` was meant to be `colonIndex`.

**Comment by sothawo** [comment]
A bracketed host is used to specify an IPV6 address. It is bracketed to prevent a part of the IP being interpreted as port number.

The host `2001:db8:0:8d3:0:8a2e:70:7344` for example must be bracketed in a URL to prevent the 7344 to be interpreted as port. With this host the correct syntax for an Elasticsearch running on that host would be `[2001:db8:0:8d3:0:8a2e:70:7344]:9200`

So the code to parse `[something:9200]` correctly returns `something:9200` as host and an empty port. Later 9200 is added as default port. 
To solve your problem you should check why the address to parse is put into brackets at all if it is no IPV6 address.

**Comment by tarjanik** [comment]
Thanks for the reply, then this is really the intended behavior.
