### ISSUE TITLE
Mapping for keyword field generated differently (randomly?)

### ISSUE THREAD

**Issue by rpieniazek** [spring-projects/spring-data-elasticsearch#1833]
Hi, 

I develop an application based on spring data elasticsearch (SDE). I use SDE for creating indices (mappings) and saving documents. For query I use HighLeveRestClient from elasticsearch client. 
Now, I am facing an issue on production, as the mapping generated is different than generated on local, or devs environment. Both production and other env use the same elastic version, the same number of nodes, the same configuration.

```
@Document(indexName = "region")
public class RegionDocument {
	@Id
	private String id;

	@Field(type = FieldType.Keyword, name = SearchFields.COUNTRIES)
	private Set<String> countries;
}
```

This code generated following mapping on my local and on devs env. This is what I expect.

```
{
  "properties": {
    "_class": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    },
    "countries": {
      "type": "keyword"
    },
    "id": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    }
  }
}
```

On production, mapping for field `countries` differes. It is generated as elasticsearch multifield property. I do not expect that : 

```
{
  "properties": {
    "_class": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    },
    "countries": {
      "type": "text",

      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    },
    "id": {
      "type": "text",
      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    }
  }
}

```

Versions used:
- spring boot 2.3.1.RELEASE
- elasticsearch spring data 4.0.1.RELEASE
- elasticsearch on AWS 7.10

**Comment by sothawo** [comment]
which processes are writing to the index? And when and by which application is the index created? This looks like an automatically mapped field.

**Comment by rpieniazek** [comment]
Hi @sothawo, Thank you for the reply

> which processes are writing to the index? 

My application - it consumes events and puts the data to elasticsearch.

>when and by which application is the index created?

The index is created if not exists by the SDE at the application startup.  It is the same application that writes to ES.

>This looks like an automatically mapped field. 

What do you mean? This field is annotated as
 `@Field(type = FieldType.Keyword, name = SearchFields.COUNTRIES)
	private Set<String> countries;` 
Please, see whole mapping in the post above.


>And was the index created by the application or did it exist already?

Index has been created by the application.

**Comment by sothawo** [comment]
with "automatically mapped" I meant that
```
{
      "type": "text",

      "fields": {
        "keyword": {
          "ignore_above": 256,
          "type": "keyword"
        }
      }
    }
```
is what Elasticsearch wirtes to the mapping when it encounters a string value in a field and no mapping was provided for that field.

The only reason for this behaviour would be that the index already existed when the application started or there was an error when the application tried to create the index and later the fields were automatically mapped by Elastcisearch. In versions prior to SDE 4.2 such an error was only logged but not passed to the application and might have gone unnoticed. If the application would then store an entity the index and the mapping would be created automatically by Elasticsearch and this would then look like the mapping you have.

Can you somehow reproduce this behaviour?

**Comment by rpieniazek** [comment]
Hi @sothawo,

We use AWS messaging to keep elasticsearch up to date with the main database. We listen for events, map it to SDE @Document objects and store in elastic. Would it be possible that with this solution there were race condition - mapping was not ready yet, but application started to save data? 
If so, is there a mechanism to be notified when mapping is ready? I could pause listener  and run it after application starts.

I am not able to reproduce it behaviour. 

There is only one instance of the application, but 3 elasticsearch nodes on cluster.

**Comment by sothawo** [comment]
I could imagine this when you are storing the entities to Elasticsearch by using `ElasticsearchOperations.save()` method and not a `ElasticsearchRepository.save()`. The index and mapping is created by the `ElasticsearchRepository` which uses the `ElasticsearchOperations` for that. And if the index is not yet created, but data is already written with the methods of `ElasticsearchOperations`, then the fields would be automatically mapped. The repository would then get an error when createing the index or mapping, but as I wrote, that would have been logged only.

If you are using the `save` methods of the repository this could not happen, as the index would be created on creation of the repository instance.

You might be using the operations method in order to not do the refresh that the repository does by default? In that case, you could overwrite the save method for the repository in a custom implementation that does not do the refresh - If that's the case and you need help just ask

**Comment by rpieniazek** [comment]
@sothawo 

Idd, you are right. We are using custom save operation to avoid refresh operations. It's a workaround for authentication issues with elasticsearch hosted by AWS. I wrote few words about it [here](https://medium.com/@rkpieniazek/aws-authentication-with-elasticsearch-spring-data-3bb2322b5463 ) This is probably root cause for initial issue. 



> In that case, you could overwrite the save method for the repository in a custom implementation that does not do the refresh - If that's the case and you need help just ask

I belived that I already did that, but maybe there is something with my implementation. May I kindly ask you to review if this is correct? 

Here is the class diagram for my current approach. 

![RegionRepositoryImpl](https://user-images.githubusercontent.com/9202403/120377078-f01f0f00-c31c-11eb-93b0-125d467bcd02.png)


In some service class I inject `RegionRepository` and use `saveWithoutRefresh(...)` method

The implementation only invokes `operations.save(...)`

```
    @Override
    public RegionDocument saveWithoutRefresh(RegionDocument region) {
        return operations.save(region);
    }

```


What did I miss?

**Comment by sothawo** [comment]
This all seems correct to me. And if this is the only way that the entities are stored into Elasticsearch, I do not see where this mapping came from - and have no more ideas.

One thing - that has nothing to do with your problem: in your custom repository you can use the same signatures for methods as in the base implementation like `<S> save(S)`, you need to make your custom repository generic, but then the call to `save(S)` will use the custom method and not the base one.

**Comment by rpieniazek** [comment]
I am wondering what other options do I have.

Is there a way to programatically check if mapping is ok? Save operations are rare in my application - I could check if mapping is there before document is saved.

**Comment by sothawo** [comment]
You can use the `IndexOperations.getMapping()` method to retrieve the mapping for an index

**Comment by rpieniazek** [comment]
@sothawo Thank you for your attention and support. I'll close the issue.
