### ISSUE TITLE
Missing hashCode and equals methods in JoinField

### ISSUE THREAD

**Issue by xhaggi** [spring-projects/spring-data-elasticsearch#1846]
The class `JoinField` is missing the `hashCode` and `equals` methods.

**Comment by sothawo** [comment]
backported to 4.2.x and 4.1.x

**Comment by xhaggi** [comment]
Thank you 👍

**Comment by tuomoa** [comment]
@sothawo is there a reason that not all the classes implement equals (and hashCode)? I think all the classes under `org.springframework.data.elasticsearch.core.query` do not implement these. This makes it harder to compare queries for example in unit tests with argument matches and equality assertions.

**Comment by sothawo** [comment]
What would `equals` mean for queries? 

A `NativeQuery` for example contains original Elasticsearch classes like `co.elastic.clients.elasticsearch.core.search.Suggester` which do not offer equality information, so a `NativeQuery` would have to use object identity.

Should these queries be the same:
```java
		Query query1 = CriteriaQuery.builder(
						new Criteria("firstName").is("James").and("lastName").is("Bond"))
				.build();
		Query query2 = CriteriaQuery.builder(
						new Criteria("lastName").is("Bond").and("firstName").is("James"))
				.build();
```

And should a `CriteriaQuery` and a `StringQuery` that in the end produce the same query that is sent to Elasticsearch be equal?

It might make sense to have `equals/hashcode` for some classes, feel free to create an issue for that an provide a PR.

**Comment by tuomoa** [comment]
Hmm yeah it might not be feasible to handle equality in all cases. I suppose that the example case might be interpreted as not equal and that's all right but it might be nice to be able to compare simple case such as `CriteriaQuery.builder(new Criteria("firstName").is("James").and("lastName").is("Bond")).build()`with `CriteriaQuery.builder(new Criteria("firstName").is("James").and("lastName").is("Bond")).build()` and see that they are equal. But all right 👍
