### ISSUE TITLE
How do I change to configure my connection string in application.properites， when my elasticsearch contains a username and password

### ISSUE THREAD

**Issue by zqw961025** [spring-projects/spring-data-elasticsearch#1851]

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not use or read _application.properties_. If you are using spring Boot, check the Spring Boot documentation what properties they support for Spring Data Elasticsearch.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
