### ISSUE TITLE
How can I use join in 3.2.x

### ISSUE THREAD

**Issue by andrelive** [spring-projects/spring-data-elasticsearch#1852]
The elasticsearch version I am using is 6.7.1, but there is no “join” type in 3.2.x. 

If I use 4.1.X, the "include_type_name" parameter cannot be set to false... 

What should I do to solve this problem?

**Comment by sothawo** [comment]
3.2 does not have support for join type, you will need at least 4.1. In version 4.1 the `include_type_name` parameter is per default set to false - what's the problem here?

**Comment by andrelive** [comment]
> 3.2 does not have support for join type, you will need at least 4.1. In version 4.1 the `include_type_name` parameter is per default set to false - what's the problem here?

In fact, there is no include_type_name parameter in the putmapping api of elasticsearch client 7.x. And there are other compatibility issues. So we can't work with 4.1.x and elasticsearch 6.7.x.
Well, I know they are not compatible anymore. thank you for your reply.
