### ISSUE TITLE
Improve NativeSearchQueryBuilder by adding convenience methods and modifying existing ones.

### ISSUE THREAD

**Issue by xhaggi** [spring-projects/spring-data-elasticsearch#1854]
The `NativeSearchQueryBuilder` is missing some convenience methods and it contains some methods that are not in line with the other `withXXX` methods.

**Comment by sothawo** [comment]
please note that the whole client-integration will get a major rewrite in the next time, as we need to integrate the new Elasticsearch client, and the existing `NativeSearchQueryBuilder` will have to be replaced with something new; see #1853

**Comment by xhaggi** [comment]
IMO the changes I made to the `NativeSearchQueryBuilder` are minor. I have just opened a PR.
