### ISSUE TITLE
Ask a question about the use of @Field in spring-data-elasticsearch 3.2.1 version

### ISSUE THREAD

**Issue by EndaLin** [spring-projects/spring-data-elasticsearch#1857]
### Problem Description
First, show the business code
```
@Document(indexName = "#{esResource.questionIndex}", type = "_doc", createIndex = false)
data class QuestionEntity(

        @Id
        @Field(name = "uid")
        var uid: String = "",

        @Field(type = FieldType.Keyword, name = "app_code")
        var appCode: String = "",
......
```
And then, the template I am using is ElasticsearchRestTemplate.

I used the @Field of @Document which value is false. When I use this entity class to query, I found that the JSON data queried by ES cannot be mapped to the values of QuestionEntity

So, I start to debug the source code of spring-data-elasticsearch 3.2.1 version, and I found the mapping relationship of @Filed is carried out in the method org.springframework.data.elasticsearch.core.MappingBuilder#buildPropertyMapping

```
	private void buildPropertyMapping(XContentBuilder builder, boolean isRootObject,
			ElasticsearchPersistentProperty property) throws IOException {

		if (property.isAnnotationPresent(Mapping.class)) {

			String mappingPath = property.getRequiredAnnotation(Mapping.class).mappingPath();
			if (!StringUtils.isEmpty(mappingPath)) {

				ClassPathResource mappings = new ClassPathResource(mappingPath);
				if (mappings.exists()) {
					builder.rawField(property.getFieldName(), mappings.getInputStream(), XContentType.JSON);
					return;
				}
			}
		}

		boolean isGeoPointProperty = isGeoPointProperty(property);
		boolean isCompletionProperty = isCompletionProperty(property);
		boolean isNestedOrObjectProperty = isNestedOrObjectProperty(property);

                 // this
		Field fieldAnnotation = property.findAnnotation(Field.class);
```

In the ElasticsearchRestTemplate class, only the org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate#putMapping method can have the opportunity to call this method, but the call of the org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate#putMapping method depends on whether the **creatIndex** in @Document need true，and the reason why my mapping failed is here, because I set the createIndex in @Document to false, because I only need to query through the entity class without creating an index

In this regard, I am puzzled, let me show the relevant source code

```
	public AbstractElasticsearchRepository(ElasticsearchEntityInformation<T, ID> metadata,
			ElasticsearchOperations elasticsearchOperations) {

		this(elasticsearchOperations);

		Assert.notNull(metadata, "ElasticsearchEntityInformation must not be null!");

		this.entityInformation = metadata;
		setEntityClass(this.entityInformation.getJavaType());
		try {
			if (createIndexAndMapping()) {
				createIndex();
				putMapping();
			}
		} catch (ElasticsearchException exception) {
			LOGGER.error("failed to load elasticsearch nodes : {}", exception.getDetailedMessage());
		}
	}
```
```
	public SimpleElasticsearchPersistentEntity(TypeInformation<T> typeInformation) {

		super(typeInformation);
		this.context = new StandardEvaluationContext();
		this.parser = new SpelExpressionParser();

		Class<T> clazz = typeInformation.getType();
		if (clazz.isAnnotationPresent(Document.class)) {
			Document document = clazz.getAnnotation(Document.class);
			Assert.hasText(document.indexName(),
					" Unknown indexName. Make sure the indexName is defined. e.g @Document(indexName=\"foo\")");
			this.indexName = document.indexName();
			this.indexType = hasText(document.type()) ? document.type() : clazz.getSimpleName().toLowerCase(Locale.ENGLISH);
			this.useServerConfiguration = document.useServerConfiguration();
			this.shards = document.shards();
			this.replicas = document.replicas();
			this.refreshInterval = document.refreshInterval();
			this.indexStoreType = document.indexStoreType();
			this.versionType = document.versionType();
			this.createIndexAndMapping = document.createIndex();
		}
		if (clazz.isAnnotationPresent(Setting.class)) {
			this.settingPath = typeInformation.getType().getAnnotation(Setting.class).settingPath();
		}
	}
```

I set the value of createIndex in @Document to **false**, because I only need to use it to query without creating an index

May I use the wrong createIndex in @Document, or is there another way to deal with this mapping problem?

**Comment by EndaLin** [comment]
I really look forward to hearing about effective solutions！

**Comment by sothawo** [comment]
> When I use this entity class to query, I found that the JSON data queried by ES cannot be mapped to the values of QuestionEntity

How do you build the query? And how does the actual mapping in Elasticsearch look like (`GET /indexname/_mapping`)?
The code you look at is only relevant when SDE creates the index and writes the mapping. If the index exists and the mapping of the index matches has the field `app_code` of type `keyword` then the query should work. "should" because 3.2.1 is an old version, this would need further investigation.

**Comment by EndaLin** [comment]
> > When I use this entity class to query, I found that the JSON data queried by ES cannot be mapped to the values of QuestionEntity
> 
> How do you build the query? And how does the actual mapping in Elasticsearch look like (`GET /indexname/_mapping`)?
> The code you look at is only relevant when SDE creates the index and writes the mapping. If the index exists and the mapping of the index matches has the field `app_code` of type `keyword` then the query should work. "should" because 3.2.1 is an old version, this would need further investigation.

My usage scenario is query. I hope that after spring-data-elasticsearch obtains the query result in JSON format, it maps the result to the entity class. The current question is how to construct this mapping relationship.

By reading the documentation, I know that Meta Model Object Mapping can use @Field, this is not working, because its role in the source code is as you said SDE creates the index and writes the mapping, so I want to know how to create The mapping relationship between query results and entity classes

**Comment by EndaLin** [comment]
> > When I use this entity class to query, I found that the JSON data queried by ES cannot be mapped to the values of QuestionEntity
> 
> How do you build the query? And how does the actual mapping in Elasticsearch look like (`GET /indexname/_mapping`)?
> The code you look at is only relevant when SDE creates the index and writes the mapping. If the index exists and the mapping of the index matches has the field `app_code` of type `keyword` then the query should work. "should" because 3.2.1 is an old version, this would need further investigation.

The field name of the index and the field name of the entity class are not the same, so an association relationship needs to be established to ensure that the result of the query can be mapped to the entity class

**Comment by sothawo** [comment]
Can you please show the following:
* The mapping in the index which you can geth wit a call to `{elasticsearchhost}:{port}/{indexname}/_mapping`
* The actual code you use to build a query for searching.

The `@Field` annotation is not only used when creating the mapping for the index, it is considered when mapping query parameters and response data.

>The field name of the index and the field name of the entity class are not the same,
Of course they are not, but SDE knows what fields are in an entity.

About writing the mapping: when the index is **not** created by SDE but somehow else, you must make sure that the field names are written correctly to the mapping. So is the field named really `app_code` in the index?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
