### ISSUE TITLE
fix uri encode bug when url path start with '/'

### ISSUE THREAD

**Issue by frnandu** [spring-projects/spring-data-elasticsearch#1870]
Please take a look at this fix in original elasticsearch client code:

https://github.com/elastic/elasticsearch/pull/34436

please update spring data's RequestConverters#encodePart to reflect the fix in this issue, since the implementation in spring-data  seems to be a copy of an older (pre-fix) version of encodePart, specifically building the URI.
Is there a strong reason to have this duplicated in spring-data, couldn't it use same code from original ES high level client?
Thanks

**Comment by sothawo** [comment]
We cannot use the class from the Elasticsearch library, as it is not accessible outside the package. So we needed to copy and adapt it for the reactive client.
