### ISSUE TITLE
Avoid overloading default search type to dfs_query_then_fetch?

### ISSUE THREAD

**Issue by jtibshirani** [spring-projects/spring-data-elasticsearch#1884]
Unless it's specified, the search type is set to `dfs_query_then_fetch`: https://github.com/spring-projects/spring-data-elasticsearch/blob/d80d920a575b97b74d634cad3ed1b8b6034cd1ad/src/main/java/org/springframework/data/elasticsearch/core/query/AbstractQuery.java#L55

The default search type in Elasticsearch itself is `query_then_fetch`. Compared to this Elasticsearch default, `dfs_query_then_fetch` performs an extra round trip to the nodes before starting the main search to gather term frequency information. In general, the `dfs_query_then_fetch` type is only used in special situations where exact text scoring is important.

To avoid adding the extra roundtrip, `AbstractQuery` could fall back to the Elasticsearch default instead of setting `dfs_query_then_fetch`.

**Comment by sothawo** [comment]
Thanks for finding this. That value has been in there since this property was added in Spring Data Elasticsearch back in march 2014 - nowadays nobody knows why it was set to this value then.

This will be cleaned up together with the changes of #1885
