### ISSUE TITLE
Does the 3. X version support High Level REST Client

### ISSUE THREAD

**Issue by ChasingInTheWind** [spring-projects/spring-data-elasticsearch#1886]
Does the 3. X version support High Level REST Client

**Comment by sothawo** [comment]
Accessing Elasticsearch's REST interface by using the `RestHighLevelClient` from Elasticsearch was introduced in Spring Data Elasticsearch 3.2.0 (which by now is a version that is out of support).

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
