### ISSUE TITLE
Setting an offset is not supported by pageable.

### ISSUE THREAD

**Issue by tiagu-sh** [spring-projects/spring-data-elasticsearch#1889]
Hi,
I want to use nativeSearchQuery with Pageable, however setting an offset is not supported.
In ElasticSearch this requirement can be achieved by from parameter.
`GET /_search
{
  "from": 5,
  "size": 20,
  "query": {
    "match": {
      "user.id": "kimchy"
    }
  }
}`
I am wondering setOffset could be useful as getOffset.

Kind regards,
Tianfeng

**Comment by sothawo** [comment]
You can accomplish this by providing a custom implementation of `Pageable`, like in this code taken from Spring Data Elasticsearch`s tests (https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchTemplateTests.java#L2816-L2825):

```java
Pageable pageable = new PageRequest(1, 10, Sort.unsorted()) {
	@Override
	public long getOffset() {
		return 30;
	}
};

NativeSearchQuery query = new NativeSearchQueryBuilder() //
		.withPageable(pageable) //
		.build();
```

**Comment by tiagu-sh** [comment]
Great, thanks for your information!
