### ISSUE TITLE
3.2.6.RELEASE ElasticsearchRestTemplate.index method Cannot save field pId

### ISSUE THREAD

**Issue by HejinkeGitHub** [spring-projects/spring-data-elasticsearch#1890]
![image](https://user-images.githubusercontent.com/43699641/127865243-cb1cfe25-4838-473d-8e0b-a22c359d50df.png)

**Comment by sothawo** [comment]
What is the error? Spring Data Elasticsearch 3.2 is out of support since October 2020. Does this error occur with an actual version of Spring Data Elasticsearch  as well?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
