### ISSUE TITLE
Sorting an empty result should not fail.

### ISSUE THREAD

**Issue by KOSSOKO** [spring-projects/spring-data-elasticsearch#1908]
I have this method

`ebookReviewRepository.findByEbookIdOrderByCommentDateDesc(ebookId, PageRequest.of(page, size));`

I noticed that when the index is empty, I get the error `Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]`. This error is due to the fact that elastic search tries to sort and empty result.

They added  `"ignore_unmapped": true` to ignore it:

```
{
    "from": 0,
    "size": "15",
    "sort": {
        "title": {
            "order": "asc",
            "ignore_unmapped": true
        }
    }
}

```
https://github.com/elastic/elasticsearch/issues/1558

But it how could i use the ignore_unmapped option in Spring Data elastic search ? There are no traces in the documentation.
I added a check in my services workaround, but for large data, making count each time is not a solution. 

// We have to check first if we have data, in order to avoid issues about sorting when empty
```
		if(this.ebookReviewRepository.count() != 0) {
			
			Page<EbookReview> ebookReviewPage =  ebookReviewRepository.findByEbookIdOrderByCommentDateDesc(ebookId, PageRequest.of(page, size));
			// We add app user name to the review
			for(EbookReview review : ebookReviewPage) {
				EbookReviewDto ebookReviewDto = createCompleteEbookReviewDto(review, appUserId);
				if(ebookReviewDto.getAppUserId() != null) {
					rewiewsDtoResult.add(ebookReviewDto);
				}
			}
			isHasNext = ebookReviewPage.hasNext();
		}
```

How could I handle it correctly ? Thanks ?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by KOSSOKO** [comment]
@spring-projects-issues wich requested information do you need ?

**Comment by sothawo** [comment]
I just don't want to close an issue without giving the chance of further feedback, so I set the waiting-for-feedback which will close the issue if no further feedback comes from the OP. So I'll close this one now ;-)
