### ISSUE TITLE
EXISTS, NOT_EMPTY query filters for the repository

### ISSUE THREAD

**Issue by emirUlken** [spring-projects/spring-data-elasticsearch#1909]
Currently, EXISTS and NOT_EMPTY & NOT_NULL query filters don't work for our repository. It should work the same as in JpaRepository. Can we add this feature?

**Comment by emirUlken** [comment]
Any updates on this issue? I really need to filter my search based on non-empty fields such as "".

**Comment by sothawo** [comment]
No. Spring Data Elasticsearch is a community driven project, so when issues are implemented depends on someone taking the time to implement it. But there are no dedicated persons working on the project. I am maintaining and coordinating this in my spare time as well. 

Current my main focus is on preparing Spring Data Elasticsearch for the new Elasticsearch client and to additionally enable access to OpenSearch as well. After that I will go on and work on the existing issues, but as I wrote, it's in my spare time, so I can not say when this issue will be handled.
