### ISSUE TITLE
What's the best way of searching a text in all of the fields, get all matches?

### ISSUE THREAD

**Issue by emirUlken** [spring-projects/spring-data-elasticsearch#1914]
I need to search a text in all of the fields. It would probably look something like findAll(String searchtext) but it's not supported. Any ideas on best way to achieve this?

**Comment by sothawo** [comment]
You'd need to use a `NativeSearchQuery`with a multimatch query for this. You can have a look at how it's used in this test: https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/test/java/org/springframework/data/elasticsearch/core/SearchAsYouTypeTests.java#L96-L103

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
