### ISSUE TITLE
How to use @CountQuery?

### ISSUE THREAD

**Issue by emirUlken** [spring-projects/spring-data-elasticsearch#1915]
I couldn't find any examples online. How do I extract count from this? Can I make the return type as List in my repo and get count at the same time?

**Comment by emirUlken** [comment]
Here is my query

@Query("{\"bool\": {\"must\": [{\"regexp\": {\"id\": \".*?0.*\"}}, {\"regexp\": {\"categoryname\": \".*?1.*\"}}]}}")
List<Feedback> getFeedbacks(String id, String categoryName);

How do I get count from this query?

**Comment by emirUlken** [comment]
I tried to get the size of the returning list but it's limited to 10 because of aggregation. I need the full count amount.

**Comment by sothawo** [comment]
```java
@CountQuery("{"bool": {"must": [{"regexp": {"id": ".?0."}}, {"regexp": {"categoryname": ".?1."}}]}}")
Long getFeedbacks(String id, String categoryName);
```

what aggregation?

**Comment by emirUlken** [comment]
> ```java
> @CountQuery("{"bool": {"must": [{"regexp": {"id": ".?0."}}, {"regexp": {"categoryname": ".?1."}}]}}")
> Long getFeedbacks(String id, String categoryName);
> ```
> 
> what aggregation?

Well idk if it's aggregation or not but the result size is always 10. It's like it has a limiter for the count. Is there any way I can get the result size for the correct total amount instead of 10?

**Comment by sothawo** [comment]
I just ran a test in a local program and a `@CountQuery` returns more than 10 there.

I found an issue with the execution of `@Query` method, this returns only the first 10 documents (Elasticsearch's default page size); that explains the list size of 10 you see. I created #1917 for this bug.

**Comment by emirUlken** [comment]
> I just ran a test in a local program and a `@CountQuery` returns more than 10 there.
> 
> I found an issue with the execution of `@Query` method, this returns only the first 10 documents (Elasticsearch's default page size); that explains the list size of 10 you see. I created #1917 for this bug.

How did you put the annotation? Because when I replace @Query with @CountQuery there, I get an error saying "No column found for type GetFeedbacks".

**Comment by sothawo** [comment]
```java
    @CountQuery("{\"fuzzy\":{\"last-name\":\"?0\"}}")
    long countByLastNameFuzzy(final String lastName);
```

I just use `@CountQuery` instead of `@Query` and of course the return type of the method has to somethign a long value can be assigned to.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
