### ISSUE TITLE
Double encoding 

### ISSUE THREAD

**Issue by berendhard** [spring-projects/spring-data-elasticsearch#1922]
So, I'm using ReactiveElasticsearchClient with GetRequest.
I'm creating GetRequest with index and id.

Id looks like this:
`cbfa144f-1def-eb11-8354-005056901fa2/VS_Regular10/2021-07`
but client is encoding to
`cbfa144f-1def-eb11-8354-005056901fa2%252FVS_Regular10%252F2021-07`

So, I'm getting double encoded, where / is changed to **%252F** instead of **%2F** and because of that I'm not able to get that doc from elastic, bc elastic is returning 404 not found.

I tried to encode / by my self, replacing that before creating GetRequest - but client still was changing it to **%252F**

I'm using SpringDataElasticsearch 4.0.3.RELEASE

**Comment by sothawo** [comment]
This bug was fixed with #1666 (doc id is handled like the index name in the requests) and released with version 4.0.7
