### ISSUE TITLE
parent-child search in spring-data-es

### ISSUE THREAD

**Issue by stoneLee81** [spring-projects/spring-data-elasticsearch#1949]
is there a demo to show parent-child using in spring-data-es? It’s a bit difficult to understand, I don’t know how to implement it in spring-data-es

**Comment by sothawo** [comment]
There is the Elasticsearch documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html for the join-type and the Spring Data Elasticsearch documentation https://docs.spring.io/spring-data/elasticsearch/docs/4.2.5/reference/html/#elasticsearch.jointype using the same example.
