### ISSUE TITLE
searchForStream ignoring Query.scrolltime setting. defaults to 60 seconds

### ISSUE THREAD

**Issue by Stexxen** [spring-projects/spring-data-elasticsearch#1950]
When using searchForStream in ElasticSearchOperations the scroll time is always set to 60 seconds, ignoring any setting made in the Query

i.e.
```
  NativeSearchQuery query = ....
  query.setScrollTime(Duration.of(120, ChronoUnit.SECONDS));

  try (SearchHitsIterator<Thing> searchHitsIterator = opTemplate.searchForStream(query, Thing.class)) {

```

Will always set `scroll=60000ms` in the initial and subsequent queries to elastic even though a different scroll time has been specified.

**Comment by sothawo** [comment]
thank you for your contribution!
