### ISSUE TITLE
ES v7.10.2 

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-data-elasticsearch#1952]
Would you please upgrade ES to  `7.10.2` (which is the latest version with `oss` license ) in upcoming `4.1.14` release.

**Comment by sothawo** [comment]
In Spring Data for released versions dependency updates are only adapted on patch level and not on minor versions. That means that Spring Data Elasticsearch 4.1.x will use the latest version of  Elasticsearch 7.9 which currently is 7.9.3. So no update to 7.10.x here.

**Comment by jvmlet** [comment]
And `4.2.x` already uses `7.13.x` ? Is there any chance to get ES `7.10.2` to be able to deploy  AWS open distro plugins, last one is for `7.10.2`

**Comment by sothawo** [comment]
what plugins in relation to the used client library?

**Comment by jvmlet** [comment]
Open distro for ES plugins, like ilm and security(both Kibana and ES) They are compatible with 7.10.2. I'm not sure if rest client 7.9.3 will work with ES 7.10.2

**Comment by jvmlet** [comment]
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/
