### ISSUE TITLE
Change ElasticSearch FieldType class type from enum to class with String constants

### ISSUE THREAD

**Issue by mcamak** [spring-projects/spring-data-elasticsearch#1961]
For ElasticSearch mapping there is an annotation `org.springframework.data.elasticsearch.annotations.Field` with attribute `type` of type `org.springframework.data.elasticsearch.annotations.FieldType`, which is an enum:
```java
public enum FieldType {
	Auto, //
	Text, //
	Keyword, //
	Long, //
         ...
```

This approach has one disadvantage - it is not possible to use custom defined field types in ElasticSearch, only predefined types in this enum are allowed.

Would it be possible to change this enum class to a class with String constants? (and naturally change the type of `type` property on annotation `Field` from `FieldType` to `String`). For example:
```java
public class FieldType {
	public static final String Auto = "Auto";
	public static final String Text = "Text";
	public static final String Keyword = "Keyword";
	public static final String Long = "Long";
	public static final String Integer = "Integer";
        ...
}
```

This way it would be possible to use custom fields defined in ElasticSearch.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
