### ISSUE TITLE
Add new Elasticsearch client as an alternative to the existing REST-clients

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#1973]
As a first step before switching to new new client it should be added as an alternative to using the `RestHighLevelClient` and the existing reactive client.

**Comment by hartmut-co-uk** [comment]
this is about moving to https://github.com/elastic/elasticsearch-java?

**Comment by sothawo** [comment]
sure. I am currently working on adding the new client as an optional alternative for the next minor version (4.4).

**Comment by hartmut-co-uk** [comment]
thanks, I guess this also would be brought forward to an ~M2/RC of v5? 
(`org.springframework.data:spring-data-elasticsearch:5.0.0-M1`)

**Comment by sothawo** [comment]
when it's in the main branch, it then will also be in the next v5 version.
