### ISSUE TITLE
How to get more information on failed bulk requests using IndexedObjectInformation?

### ISSUE THREAD

**Issue by amitga** [spring-projects/spring-data-elasticsearch#1981]
Hi.
I have searched high and low, but could not find information on how to get information on failed bulk operations using `elasticsearchOperations.bulkIndex()`.
All it returns is a list of `IndexedObjectInformation` which has some odd members, but nothing about the indexing errors.

Your help would be greatly appreciated.

**Comment by sothawo** [comment]
When a bulk operation fails it throws a `BulkFailureException`. This exception has a method `public Map<String, String> getFailedDocuments()`. This maps from the id of the document to the failure message.

**Comment by amitga** [comment]
Cool, thanks!
I must have missed that somehow.
Maybe an example in the Spring Docs would prevent future confusion for other developers too.

**Comment by sothawo** [comment]
I added the information to the JavaDoc of the relevant methods.

**Comment by amitga** [comment]
Thanks!
