### ISSUE TITLE
NativeSearchQuery withPageable or setPageable return empty

### ISSUE THREAD

**Issue by ollowp** [spring-projects/spring-data-elasticsearch#1983]
NativeSearchQuery query = new NativeSearchQueryBuilder()
                .withQuery(simpleQueryStringBuilder)
                .build();
        query.setHighlightQuery(new HighlightQuery(commonService.createHighlightBuilder("title","resume","tags")));
        query.setPageable(PageRequest.of(1,10));
reactiveElasticsearchTemplate.search(query,LinkResource.class);

when  quering ,it retrun empty ,while cancell setPageable ,it has values.
how can it work when i want to query with pageable.

**Comment by sothawo** [comment]
Which version of Spring Data Elasticsearch do you use?
How many results are returned when you do not add a `Pageable` to the request?

**Comment by ollowp** [comment]
Spring Data Elasticsearch version is 4.0.9.RELEASE
without Pageable ,all of matched results  are retruned.

**Comment by ztomic** [comment]
@ollowp This is normal if you have less than 10 documents indexed. You are requesting **second page**. Paging (`PageRequest`) is zero-based, so first page is `0` and not `1`.

**Comment by ztomic** [comment]
@ollowp See [PageRequest.java#L59](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/domain/PageRequest.java#L59)

**Comment by sothawo** [comment]
Yes, that's why I asked "how many" results. I have just tried sample code with version 4.0.x and the `Flux`es I get back always contain 10 elements, making up to the total entity collection. 

btw. 4.0.x is out of maintenance since May 2021, you should upgrade to the recent version.

**Comment by ollowp** [comment]
thanks ,that's my problem without show the document

**Comment by sothawo** [comment]
I interpret this so that this issue can be closed.
