### ISSUE TITLE
NativeSearchQueryBuilder withIndices removed 

### ISSUE THREAD

**Issue by yasinasama** [spring-projects/spring-data-elasticsearch#2006]
How can I specify indices by NativeSearchQueryBuilder in the latest version

Ths!

**Comment by sothawo** [comment]
`NativeSearchQueryBuilder.withIndices`was removed with Spring Data Elasticsearch 4.0 in May 2020. You do not specify the indices on the `Query` object, but as a parameter on the `ElasticsearchOperations.search()` method that gets the query object passed in.

**Comment by yasinasama** [comment]
its work for me ths !
