### ISSUE TITLE
Add AfterLoad lifecycle callback

### ISSUE THREAD

**Issue by goldami1** [spring-projects/spring-data-elasticsearch#2009]
Hi,

Following #1159 , I suggest to add additionally to the afterSave, afterConvert and beforeSave callbacks, also the beforeLoad.
Similarly to MongoTemplate which emits AfterLoadEvent before the reader is used to read the document (in ReadDocumentCallback).
Thus, Similar functionality would be apprepciated at the Spring Data EntityCallbacks level for both ES and MONGO.

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not use events, only callbacks. See https://docs.spring.io/spring-data/elasticsearch/docs/4.3.0/reference/html/#entity-callbacks for information about the events and callbacks. Spring Data MongoDB has both, as there the events were already implemented when the callbacks were introduced.

When adding the callbacks we deliberately did not add the events as well.

**Comment by goldami1** [comment]
@sothawo that's clear. however, I suggest to add a "beforeLoad" callback invocation right before the Document is read into a domain object. (both for spring-data-mongodb and spring-data-elasticsearch projects)

![image](https://user-images.githubusercontent.com/33942741/143081727-c98fe911-d3b1-4cd5-aeb9-decec70e007c.png)
![image](https://user-images.githubusercontent.com/33942741/143081913-2ec58bc6-9f2f-441c-b280-7a68b486b258.png)

**Comment by sothawo** [comment]
If it's only the additional callback, that's fine. I can't speak for Spring DataMongo though, you'll need to add an issue there.

**Comment by goldami1** [comment]
@sothawo sounds great, will do!
However for spring dataElastic it sounds like a good addition. would appreciate your feedback.

**Comment by sothawo** [comment]
don't forget to add it to the reactive part as well.

**Comment by goldami1** [comment]
@sothawo Can I contribute with implementation?

**Comment by sothawo** [comment]
Sure. Fork the repo, create a branch - or use the _main_ branch of your fork, add the necessary tests and implementation (see https://github.com/spring-projects/spring-data-elasticsearch/blob/main/CONTRIBUTING.adoc) and then submit a pull request to have your forked branch be merged into this repo's _main_.

**Comment by sothawo** [comment]
@goldami1 are you working on that? This callback could be used to solve the problem of #2029.
