### ISSUE TITLE
Javadoc of code repackaged in 4.4.0 snapshots states that it has been available since earlier major versions

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-data-elasticsearch#2010]
For example, `org.springframework.data.elasticsearch.backend.elasticsearch7.client.reactive. ReactiveElasticsearchClient ` is documented as `@since 3.2` but it's new in 5.0.

**Comment by sothawo** [comment]
It's not new, it's existing code moved to a different package. Should that change the `@since`?

**Comment by wilkinsona** [comment]
If someone looks for `org.springframework.data.elasticsearch.backend.elasticsearch7.client.reactive. ReactiveElasticsearchClient` in 3.2 it won't be there, but the javadoc currently tells them that it will be. From a compatibility perspective, all of the repackaged code is new in 5.0 and I think each class's `@since` javadoc should reflect that.

**Comment by sothawo** [comment]
ok, I'll change that to be consistent to what Spring does.

**Comment by sothawo** [comment]
nitpick: the change will be from 4.4 on 😜
