### ISSUE TITLE
Expose a public method to add logging Interceptor

### ISSUE THREAD

**Issue by vdisk-group** [spring-projects/spring-data-elasticsearch#2012]
The logging interceptor class `org.springframework.data.elasticsearch.backend.elasticsearch7.client.RestClients.HttpLoggingInterceptor` is private and only can be used in the `org.springframework.data.elasticsearch.backend.elasticsearch7.client.RestClients#create`  at present.  
Expose a public method can make it easier to reuse useful logging util

**Comment by sothawo** [comment]
There is no need to add something to or expose the existing classes.

If you need to add an interceptor to the underlying client - either imperative or reactive - the Spring Data 
Elasticsearch configuration has the needed callback hooks for that. Check the configuration documentation at 
https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.configuration, 
especially the lines marked (11) and (12). You can add any interceptor to the client in these callbacks, especially 
one that does some logging according to your needs.

**Comment by vdisk-group** [comment]
> There is no need to add something to or expose the existing classes.
> 
> If you need to add an interceptor to the underlying client - either imperative or reactive - the Spring Data Elasticsearch configuration has the needed callback hooks for that. Check the configuration documentation at https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.configuration, especially the lines marked (11) and (12). You can add any interceptor to the client in these callbacks, especially one that does some logging according to your needs.

The method method I want to expose is just used in the callback
```
  . // ... other options
  .withClientConfigurer(                                                
    RestClients.RestClientConfigurationCallback.from(clientBuilder -> {
  	  // the new method use case
          RestClients.addLoggingInterceptor(clientBuilder);
      return clientBuilder;
  	}))
  . // ... other options
```

**Comment by sothawo** [comment]
The change you suppose changes the behaviour so that *every* call is passing through the  interceptor and the log level check. This internal trace logging is not needed in nearly all cases and therefore we leave it even out of the interceptor chain if the level is not configured accordingly.

If that does not meet your requirements, you can leave the internal logging disabled and add your own logger interceptor in the configuration callback.

**Comment by vdisk-group** [comment]
> The change you suppose changes the behaviour so that _every_ call is passing through the interceptor and the log level check. This internal trace logging is not needed in nearly all cases and therefore we leave it even out of the interceptor chain if the level is not configured accordingly.
> 
> If that does not meet your requirements, you can leave the internal logging disabled and add your own logger interceptor in the configuration callback.

move back the log enable check to the `RestClients#create`

**Comment by sothawo** [comment]
I still do not see why adding a public method to add the logging interceptor is necessary. 

`RestClients` is a class to create the `ElasticsearchRestClient` that is used in Spring Data Elasticsearch  from a `ClientConfiguration`. The `ElasticsearchRestClient`internally uses a `RestClient` which can be additionally configured by the user. If you need additional logging features in the client you'll need to provide an interceptor that does the logging in the client configuration.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
