### ISSUE TITLE
Totalhits support for ReactiveSearchOperations

### ISSUE THREAD

**Issue by aleksanderlech** [spring-projects/spring-data-elasticsearch#2015]
Hello,

I need to have total count while searching and would like to avoid making two searches in Elasticsearch.
For non-reactive version of `SearchOperations` I could use the following method:

`<T> SearchHits<T> search(Query query, Class<T> clazz);`

But I miss the corresponding method in `ReactiveSearchOperations`.  It would be very convenient  to have something similar in `ReactiveSearchOperations` like:

`<T> ReactiveSearchHits<T> search(Query query, Class<T> clazz);`

where the `ReactiveSearchHits` is a reactive version of `SearchHits` returning `Flux` instead of `List`.

Is this possible to deliver such an API or are there any alternative ways for doing that in the reactive world?

I am using Spring Boot 2.5.6 with Spring Data ElasticSearch 4.0.4. Thank you in advance for your help!

**Comment by sothawo** [comment]
I thought I had left a comment on this issue a couple last Friday, sorry if I didn't do.

We need a new name for the search method, because we cannot use the same name/arguments with a different return type.

What I have in a branch is:

```java
public interface ReactiveSearchHits<T> {

	Mono<AggregationsContainer<?>> getAggregations();

	float getMaxScore();

	Flux<SearchHit<T>> getSearchHits();

	long getTotalHits();

	TotalHitsRelation getTotalHitsRelation();

	boolean hasAggregations();

	boolean hasSearchHits();

	@Nullable
	Suggest getSuggest();

	boolean hasSuggest();
}
```

and the additional methods in `ReactiveSearchOperations` like: 
```java
<T> Mono<ReactiveSearchHits<T>> searchForHits(Query query, Class<T> entityType)
```

Usage example:

```java
public Flux<SearchHit<Person>> test() {
	
       Query query = new CriteriaQuery(new Criteria("lastName").is("Moeller")).setPageable(PageRequest.of(0, 5));

	return operations.searchForHits(query, Person.class)
		.flatMapMany(reactiveSearchHits -> {
			LOGGER.info("total number of hits: {}", reactiveSearchHits.getTotalHits());
			return reactiveSearchHits.getSearchHits();
		});
}
```

I used a pageable here to see the difference in the total number of hits and the count of the flux.

Would that be what you had in mind?

**Comment by aleksanderlech** [comment]
Hello @sothawo,

First of all many thanks for the super fast reaction! I am impressed. And yes, that would be something that would definitely work for me.
