### ISSUE TITLE
The TokenCount in the FieldType seems to be misspelled.

### ISSUE THREAD

**Issue by oni7uka** [spring-projects/spring-data-elasticsearch#2024]
Hi, guys
   `Datatype.TokenCount` is mapped to `tokencount`, resulting in elasticsearch mapper_parsing_exception:
```
"type":"mapper_parsing_exception","reason":"no handler for type [tokencount] declared on field [length]"
```
 The correct mapping should be token_count

**Comment by sothawo** [comment]
_Note:_ `FieldType` values are mapped by lowercasing their name. We should add the names explicitly to the enum to prevent such  mistakes in the future.

**Comment by sothawo** [comment]
added in _main_ and backported to _4.3.x_ and _4.2.x_.
