### ISSUE TITLE
log4j vulnerability in transport 

### ISSUE THREAD

**Issue by hariraogotit** [spring-projects/spring-data-elasticsearch#2028]
Team,

  I see transport client is using log4j 2.11.1

[INFO] +- org.springframework.data:spring-data-elasticsearch:jar:4.2.2:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.8:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.5.2:compile
[INFO] |  +- org.elasticsearch.client:transport:jar:7.12.1:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch:jar:7.12.1:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-core:jar:7.12.1:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-secure-sm:jar:7.12.1:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-x-content:jar:7.12.1:compile
[INFO] |  |  |  |  +- org.yaml:snakeyaml:jar:1.26:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.10.4:compile
[INFO] |  |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.4:compile
[INFO] |  |  |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.10.4:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-geo:jar:7.12.1:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-core:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-analyzers-common:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-backward-codecs:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-grouping:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-highlighter:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-join:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-memory:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-misc:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queries:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-queryparser:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-sandbox:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-spatial-extras:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-spatial3d:jar:8.8.0:compile
[INFO] |  |  |  +- org.apache.lucene:lucene-suggest:jar:8.8.0:compile
[INFO] |  |  |  +- org.elasticsearch:elasticsearch-cli:jar:7.12.1:compile
[INFO] |  |  |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[INFO] |  |  |  +- com.carrotsearch:hppc:jar:0.8.1:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.10.4:compile
[INFO] |  |  |  +- com.tdunning:t-digest:jar:3.2:compile
[INFO] |  |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
**[INFO] |  |  |  +- org.apache.logging.log4j:log4j-api:jar:2.11.1:compile**

I will use log4j2.formatMsgNoLookups flag for now but would like to know how this will be addressed.

**Comment by sothawo** [comment]
This is a dependency on the log4j-**api**.jar. The log4j vulnerability is in the log4j-**core**.jar which is not in the compile dependencies.

So it depends if you are using log4j as a logging backend, then you should force/pin the 2.15 (or 2.16) version in your dependancy management.

**Comment by hariraogotit** [comment]
> This is a dependency on the log4j-**api**.jar. The log4j vulnerability is in the log4j-**core**.jar which is not in the compile dependencies.
> 
> So it depends if you are using log4j as a logging backend, then you should force/pin the 2.15 (or 2.16) version in your dependancy management.

Okay thanks for the quick response.
