### ISSUE TITLE
repository search by list problem 

### ISSUE THREAD

**Issue by feng996** [spring-projects/spring-data-elasticsearch#2031]
When i have a list filed 
like 
```
"hits" : [
      {
        "_index" : "xxxx",
        "_type" : "_doc",
        "_id" : "897055",
        "_score" : 1.0,
        "_source" : {
          "id" : 897055,
          "tags" : [
            1234,
            33535
          ]
        }
      },
      {
        "_index" : "xxxx",
        "_type" : "_doc",
        "_id" : "897056",
        "_score" : 1.0,
        "_source" : {
          "id" : 897056
          "tags" : [
            1234,
            33535,
            33538989
          ]
        }
      },
      {
        "_index" : "xxxx",
        "_type" : "_doc",
        "_id" : "897057",
        "_score" : 1.0,
        "_source" : {
          "id" : 897057
          "tags" : [
            1234
          ]
        }
      }
    ]
  }
```
i want search tags = [1234, 33535], then return  two document.
but if i use findByTagsIn(List)，it will return three.

i know custom can do like
```
Criteria criteria = new Criteria()
                .and(new Criteria("tags").is(1234))
                .and(new Criteria("tags").is(33535));
```
if i want use repository, what can i do?

**Comment by AntonLGVS** [comment]
Does this request work for you?
``` java
Criteria criteria = new Criteria("tags").in(1234, 33535);
```

**Comment by feng996** [comment]
not in
 `in` if one match then hit. like `or` , use in will return three for above example
but i want mean `and `, will return two (id = [897055, 897056])

**Comment by AntonLGVS** [comment]
Criterion `IN` means that the `array A` contains any element of the `array B` --- `A ∋ B`.
And you need strict compliance - the `array A` contains the `array B` - `A ⊇ B`.
In my opinion, the repository does not have this operator.

**Comment by sothawo** [comment]
You'll need to write a custom repository fragment (https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#repositories.custom-implementations) in which you can build the query using `Criteria` and pass it to an injected `ElasticsearchOperations` instance.

As an example how to write such a repository fragment you might check my blog post at https://www.sothawo.com/2020/09/search-entities-within-a-geographic-distance-with-spring-data-elasticsearch-4/ where I do something similar: create a custom repository method that will build a `Criteria` query and execute that.

**Comment by feng996** [comment]
Thanks，it is very helpful to me.
