### ISSUE TITLE
Define the script in the @ScriptedField annotation

### ISSUE THREAD

**Issue by AntonLGVS** [spring-projects/spring-data-elasticsearch#2035]
How about integration of the **@ScriptedField** annotation and the **ScriptedField/RuntimeField** inside query factories?
For example:
``` java
@ScriptedField(script = "doc['other'].value + 'text'")
private String field;
```
From my opinion, it is better to use the **RuntimeField** instead of the **ScriptedField** because it is part of the ElasticSearch library.

**Comment by sothawo** [comment]
runtime fields and scripted fields are different things. In Spring Data Elasticsearch scripted fields are currently only available via the `NativeSearchQuery`, this is something that we should change in the future, after the client switch. We then should introduce a `ScriptedField` in a Spring Data Elasticsearch package, not  using an Elasticsearch class and only when building the concrete query, use this.

But not before we have changed or at least added the internal client implementation to the new Elasticsearch Client, which is what I am currently working on.

**Comment by AntonLGVS** [comment]
Yes, many issue depend on the new ES client. Most issue can be blocked. Is there anything I can do to help you with your the new client?
