### ISSUE TITLE
ElasticsearchOperations.save  cannot return successful entities

### ISSUE THREAD

**Issue by chinaccj** [spring-projects/spring-data-elasticsearch#2040]
i am using   <T> Iterable<T>   DocumentOperations.save(Iterable<T> entities);
save 10 entities, one of entity's version is lower than in es, exception throw. I don't which entities successful save!

  org.springframework.data.elasticsearch.BulkFailureException: Bulk operation has failures. Use ElasticsearchException.getFailedDocuments() for detailed messages [{1=[item/-9p_OzfjRmusFog_c7VCbg][[item][0]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[1]: version conflict, current version [1640510918443] is higher or equal to the one provided [1]]], 2=[item/-9p_OzfjRmusFog_c7VCbg][[item][0]] ElasticsearchException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[2]: version conflict, current version [1640510918443] is higher or equal to the one provided [1]]]}]

	at org.springframework.data.elasticsearch.core.AbstractElasticsearchRestTransportTemplate.checkForBulkOperationFailure(AbstractElasticsearchRestTransportTemplate.java:70)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.doBulkOperation(ElasticsearchRestTemplate.java:271)

**Comment by sothawo** [comment]
The `BulkFailureException` contains a list of the documents for which the operation failed. (The message _Use ElasticsearchException.getFailedDocuments()_ should be _Use BulkFailureException.getFailedDocuments()_). 

So any entity which you sent in that is not in that list was saved successful.

**Comment by chinaccj** [comment]
thanks !

**Comment by chinaccj** [comment]
hope have more explain in api comment，It's best to attach some example。
