### ISSUE TITLE
multiGet java.lang.IllegalArgumentException: No Id define for Query

### ISSUE THREAD

**Issue by chinaccj** [spring-projects/spring-data-elasticsearch#2041]
I migrate from queryForList to multiGet, 
java.lang.IllegalArgumentException: No Id define for Query

	at org.springframework.util.Assert.notEmpty(Assert.java:470)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.multiGet(ElasticsearchRestTemplate.java:169)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.multiGet(AbstractElasticsearchTemplate.java:224)

i don't understand why set ids in each query mandatory?   

code use queryForList as below:
SearchQuery searchQuery = new NativeSearchQueryBuilder().withQuery(QueryBuilders.termQuery("name", name)).withPageable(pageable).build();
    return elasticsearchTemplate.queryForList(searchQuery, User.class);

**Comment by sothawo** [comment]
A `get` or `multiGet` returns objects based on their id value, not based on some query. So when doing a `search`you do not provide the ids, when doing a get you have to provide them.

It surely is not good that both call types have a `Query` as input parameter, with `get`and `multiget` using the ids set in that query and ignoring the rest, while `search`ignores the ids and uses the other values. But that was a design decision of the people that originally designed this API.

**Comment by chinaccj** [comment]
thanks,i got it.
