### ISSUE TITLE
How to transfer WKT to GeoJson

### ISSUE THREAD

**Issue by muchmeat** [spring-projects/spring-data-elasticsearch#2045]
Here I am hava a WKT  string，how to transfer itto GeoJson.Thanks

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not have any methods for that.
You might check out a library like [spatial4j](https://projects.eclipse.org/projects/locationtech.spatial4j)

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
