### ISSUE TITLE
BulkProcessor in Spring Data Elasticsearch

### ISSUE THREAD

**Issue by siddeshbb** [spring-projects/spring-data-elasticsearch#2067]
In one of our application we are trying to migrate from [elasticsearch-rest-high-level-client](https://mvnrepository.com/artifact/org.elasticsearch.client/elasticsearch-rest-high-level-client/7.12.0) to Spring Data Elasticsearch but found that we don't have [BulkProcessor][1] equivalent implementation in Spring data elastic search.

The BulkProcessor simplifies the usage of the Bulk API by providing a utility class that allows index/update/delete operations to be transparently executed as they are added to the processor and this feature has helped us a lot in bulk indexing documents efficiently.

Is there a plan to implement this feature in Spring data elastic search? or are we missing something here?

Any help on this is highly appreciated.

  [1]: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-document-bulk.html#java-rest-high-document-bulk-processor

**Comment by sothawo** [comment]
Currently in imperative code Spring Data Elasticsearch supports bulk-indexing and bulk-updating but not mixed bulk-requests, delete request are currently not supported. The reactive code support bulk-updating only.

You can create an issue with a feature request for that, when that will be implemented depends on when someone contribute this to the project. Spring Data Elasticsearch is a community driven project, so it depends on contributions.

**Comment by siddeshbb** [comment]
@sothawo Thank you for the reply.

I have created a feature request [2071](https://github.com/spring-projects/spring-data-elasticsearch/issues/2071) for this issue. So closing this issue.
