### ISSUE TITLE
Query interface cannot set size to 0.

### ISSUE THREAD

**Issue by oni7uka** [spring-projects/spring-data-elasticsearch#2082]
Currently, the Query interface can only set Pageable, but Pageable required page size must not be less than one. In some aggregation queries, there should be cases where hits do not need to be returned.

**Comment by sothawo** [comment]
Every `Query` implementation we have derives from `BaseQuery` which has a `setMaxResults()` method for this purpose

**Comment by oni7uka** [comment]
Oh Yes, I missed this, Maybe there should have `withMaxResults`  in `NativeSearchQueryBuilder` . cuz it is the builder pattern, Query should be immutable.
