### ISSUE TITLE
Mismatch versions Client and Cluster

### ISSUE THREAD

**Issue by franrolando** [spring-projects/spring-data-elasticsearch#2084]
I'm using spring-data-elasticsearch v4.2.7 with a ES Cluster v8.0 and I got the next response:

Unable to parse response body for Response{requestLine=POST /_bulk?timeout=1m HTTP/1.1, host=http://cluster:9243, response=HTTP/1.1 200 OK}

I read that is due incompatible version. There is someone with the same issue?

**Comment by pruidong** [comment]
I also encountered the same problem and haven't dealt with it yet. I am waiting for the release of the new version.

**Comment by sothawo** [comment]
Spring Data Elasticsearch currently is not built to use Elasticsearch by default.

Please read the [Elasticsearch's documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/rest-api-compatibility.html) about REST API compatibility.

You need to have the compatibility headers set. You can do this in two ways:

1. Set the environment variable `ELASTIC_CLIENT_APIVERSIONING=true`. This will only work when using the imperative client in Spring Data Elasticsearch. I have just tested this with Elasticsearch client 7.16.2. 

2. Set the headers programmatically in the configuration:
```java
HttpHeaders defaultHeaders = new HttpHeaders();
defaultHeaders.add("Accept", "application/vnd.elasticsearch+json;compatible-with=7");
defaultHeaders.add("Content-Type", "application/vnd.elasticsearch+json;compatible-with=7");

ClientConfiguration clientConfiguration = ClientConfiguration.builder()
	.connectedTo("localhost:9200")
        .withDefaultHeaders(defaultHeaders)
	.build();
```

This works with the imperative client, it does not (yet) work with the reactive client, as this one currently adds the default `Content-Type: application/json` header in addition to the custom one, and that produces an error when calling Elasticsearch . I'll add an issue to fix that.

As for waiting for the next version: It is planned that Elasticsearch 4.4 will contain the possibility to **optionally** use the new Java Client as an alternative to the current one that is based on the `RestHighLevelClient` / maybe using the Elasticsearch client in version 8, if that poses errors then 7.17.

A complete switch to the new client and Elasticsearch 8 will come with the next major version (5). This cannot be done earlier, as switching to the new Elasticsearch client forces the user to change from using `javax` packages to `jakarta` packages, and this will only come with Spring 6 (Spring Data Elasticsearch 5)

**Comment by franrolando** [comment]
I tried both the EV and the default headers, I'm using the RestHighLevelClient:

```
HttpHeaders defaultHeaders = new HttpHeaders();
defaultHeaders.add("Accept", "application/vnd.elasticsearch+json;compatible-with=7");
defaultHeaders.add("Content-Type", "application/vnd.elasticsearch+json;compatible-with=7");
ClientConfiguration clientConfiguration = ClientConfiguration.builder()
		.connectedToLocalhost()
		.withDefaultHeaders(defaultHeaders).build();
return RestClients.create(clientConfiguration).rest();
```

And the console give me the warning:
Version Spring Data Elasticsearch: 4.2.7
Version Elasticsearch Client in build: 7.12.1
Version Elasticsearch Client used: 7.12.1
Version Elasticsearch cluster: 8.0.0
Version mismatch in between Elasticsearch Client and Cluster: 7.12.1 - 8.0.0

After that I upgraded the Spring Data ElasticSearch version to 4.3.1 and the error persist

After looking through forums I saw this post:
https://stackoverflow.com/questions/54981698/what-elasticsearch-client-does-spring-data-elasticsearch-use-under-the-hood/55481682
And you answered 

> when using ElasticsearchTemplate, you are using the TransportClient.
when using ElasticsearchRestTemplate you are using the RestClient (available in 3.2.0).
when using a default ElasticsearchRepository you are using the TransportClient.
when using a custom repository extending for example SimpleElasticsearchRepository like shown below you are using the RestClient.

I'm using ElasticsearchRepository and here is the problem, so I think I need to migrate my code to ElasticSearchClient instead of  RestHighLevelClient and modify the way that I use the repositories to save. Am I right?

**Comment by sothawo** [comment]
The answer you refer to is some years old.

The warnings you see are just that: warnings or even just some information about the versions in use. But do you still get the error that the response from Elasticsearch cannot be read? Can you provide a minimal compilable and runnable example on GitHub that reproduces the error? When I tested that I was using a normal repository to save or retrieve some data. I succeed when setting the headers with the following versions:

```
Running with Spring Boot v2.6.1, Spring v5.3.13
Version Spring Data Elasticsearch: 4.3.0
Version Elasticsearch client in build: 7.15.2
Version runtime client used: Elasticsearch - 7.15.2
Version cluster: Elasticsearch - 8.0.0
Version mismatch in between  Client and Cluster: Elasticsearch - 7.15.2 - 8.0.0
```

You cannot just migrate your code to the new ElasticsearchClient. In order to do that, the whole Spring Data Elasticsearch library needs to have large parts adapted; I am currently working on that.

**Comment by franrolando** [comment]
Sorry for answering late but I had troubles setting up the ES v8.0 locally so I created one in the cloud. Here is the example:

```
@Configuration
@EnableElasticsearchRepositories(basePackages = "com.mypackage")
public class HealthcaseESConfig extends AbstractElasticsearchConfiguration {

	@Override
	public RestHighLevelClient elasticsearchClient() {
		HttpHeaders defaultHeaders = new HttpHeaders();
		defaultHeaders.add("Accept", "application/vnd.elasticsearch+json;compatible-with=7");
		defaultHeaders.add("Content-Type", "application/vnd.elasticsearch+json;"
				+ "compatible-with=7");
		ClientConfiguration clientConfiguration = ClientConfiguration.builder()
				.connectedTo("myCluster").usingSsl()
				.withDefaultHeaders(defaultHeaders).withBasicAuth("username", "password")
				.build();
		return RestClients.create(clientConfiguration).rest();
	}

}

@Document(indexName = "country-covid-report")
public class CountryCovidReportES extends BaseEntity {

	@Id
	private String id;
	private String name;

//	getters,setters

}

public interface ICovidReportESRepository extends ElasticsearchRepository<CountryCovidReportES, String> {

}

@Autowired
ICovidReportESRepository repository;

public void myMethod(){
	CountryCovidReportES report = new CountryCovidReportES();
	report.setId("testId");
	report.setName("Franco");
	repository.save(report); 
}
```

**Comment by sothawo** [comment]
I am running ES in a docker container, but that should make no difference. And you still get the error or only the verison warnings. Because that's basically the same setup that I have.

**Comment by franrolando** [comment]
I'm still having the same issue. Can you send me your example?

**Comment by sothawo** [comment]
In order for the reactive client to get the headers correct, it is necessary to add them to the headers provider:
```
ClientConfigurationBuilder configurationBuilder = new ClientConfigurationBuilder();
    configurationBuilder //
		// ...
		.withHeaders(() -> {
			HttpHeaders defaultCompatibilityHeaders = new HttpHeaders();
			defaultCompatibilityHeaders.add("Accept", "application/vnd.elasticsearch+json;compatible-with=7");
			defaultCompatibilityHeaders.add("Content-Type", "application/vnd.elasticsearch+json;compatible-with=7");
			return defaultCompatibilityHeaders;
		});
```

**Comment by sothawo** [comment]
@franrolando I have a [demo](https://github.com/sothawo/sde-demo-es-compatibility) here.

But I noticed, that bulk requests fail, as the returned answer does not seem to be compatible. I will create an in Elasticsearch.

**Comment by sothawo** [comment]
ES issue> https://github.com/elastic/elasticsearch/issues/84173

**Comment by franrolando** [comment]
Hi Peter, yes! I forgot to add the bulk test to my example. Sorry for that and thank you for creating the issue! I will follow that. 
Do you want to close this issue?

**Comment by sothawo** [comment]
I think this can be closed, setting the headers works, but the bulk issue is an Elasticsearch  problem where we can't do anything but wait.

**Comment by anmol8118** [comment]
Hi all,
I tried setting compatible headers in my existing rest high-level client, but unfortunately, I'm still getting the following error:

"java.lang.IllegalStateException: Unsupported Content-Type: application/vnd.elasticsearch+json;compatible-with=7"

Can you please help me here?

Elastic Search cluster: 8.5.3v
HLRC: 7.6.2v
