### ISSUE TITLE
Deprecate `o.s.d.elasticsearch.core.Range` in favor of `o.s.d.domain.Range`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-elasticsearch#2098]

**Comment by sothawo** [comment]
Just had a short look, the ` o.s.d.domain.Range`  requires the ranged type to implement `Comparable`, we need to have ranges of `TemporalAccessor`s as well. I need to take a deeper look in this though.

**Comment by mp911de** [comment]
The `contains(T value)` doesn't seem to be called from the core code. The Range type in commons is designed to pass on the value to the data store so it can make sense out of it which can include serialization as a pre-processing step.

**Comment by sothawo** [comment]
The problem is that spring data common's `Range` requires a `Comparable`, so this is not possible:

```java
@Document(indexName = "vacations")
public class Vacation {
	@Id
	private String id;

	@Field(type=FieldType.Text) private String description;

	@Field(type = FieldType.Date_Range, format = DateFormat.date)
	Range<LocalDate> date;

       // ...
}
```
We can switch if Spring Data Commons `Range`  drops the requirement  of the type being a `Comparable`.

**Comment by mp911de** [comment]
What does `Range` do in the domain model? Is it https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html?

If the purpose is a different one, then it would make sense to have a clear distinction between these two. I'm going to take this topic to the team.

**Comment by sothawo** [comment]
Yes, ranges are a field type in Elasticsearch. In the document you store the range and in the query you just specify one value and Elasticsearch returns the matching documents.

In my example you add a document for each of the vacations like Easter, Summer, Christmas holidays and then  with this repository method
```
Searchhits<Vacation> queryByDate(LocalDate date);
```
you pass in one date and get the vacations that include it; Elasticsearch does the range checks internally.

**Comment by mp911de** [comment]
Hum, in Redis we have also an own `Range` type that we could replace with the one from Commons if we drop the `Comparable` requirement. Only the `contains` method would require additional guarding (similar behavior to `TreeMap` where a `Comparable` type or `Comparator` is required for operations).
