### ISSUE TITLE
[ignore_throttled] parameter is deprecated because frozen indices have been deprecated

### ISSUE THREAD

**Issue by SeanAda** [spring-projects/spring-data-elasticsearch#2111]
Hello,

we are running Spring Boot Data Elasticsearch on Version 4.3.0 (starter version 2.6.2) in combination with an Elastisearch Cluster version 7.16.1.

Right now we are getting warnings saying `\[ignore_throttled\] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices."\]`. 

If we update the underlying elasticsearch client version to 7.16.1, we are getting an `java.lang.NoSuchFieldError: INDEX_CONTENT_TYPE` exception. 

Is there any solution for this warning?

Thank you!

**Comment by sothawo** [comment]
Elasticsearch moved some classes to different packages and jars in 7.16 (maybe 7.15?) so the code built in Spring Data Elasticsearch 4.3.0 expects that at places where it is not found anymore. Until 4.4 is out, you'll have to ignore these warnings.

**Comment by SeanAda** [comment]
Okay, thank you for your quick response!

**Comment by lijileiGood** [comment]
I didn‘t, but now I’m done.
You'are welcome.

logging:
  level:
    org.elasticsearch.client.RestClient: error
