### ISSUE TITLE
spring-data-elasticsearch 4.0.4  search with index alias, but can't get real indexName from the result, so how I update ?

### ISSUE THREAD

**Issue by songxiao-hui** [spring-projects/spring-data-elasticsearch#2113]
version: spring-data-elasticsearch 4.0.4
I search data with index alias, but SearchHit not contains real indexName,  but the data must be updated with index???

**Comment by sothawo** [comment]
The index name as part of the  `SearchHit<T>` was introduced with Spring Data Elasticsearch  4.1.

Spring Data Elasticsearch 4.0 is an old version and is out of maintenance since May 2021.

**Comment by songxiao-hui** [comment]
tks, then I will try to upgrade the version
