### ISSUE TITLE
Reference documentation mentions 'searchForPage' method that does not exist in ElasticsearchOperations

### ISSUE THREAD

**Issue by haroldlbrown** [spring-projects/spring-data-elasticsearch#2132]
In the Spring Data Elasticsearch Reference Documentation [an operation called `searchForPage` is mentioned](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.misc.filter).

However, [there seems to be no `searchForPage` method in `ElasticsearchOperations`](https://docs.spring.io/spring-data/elasticsearch/docs/current/api/org/springframework/data/elasticsearch/core/ElasticsearchOperations.html).

Please adapt the reference documentation.

**Comment by lcs-felix** [comment]
Hi, what's the alternative to this in the moment? I'm building a custom query using QueryBuilder and not being able to return a Page element. thanks

**Comment by sothawo** [comment]
You can get a `Page` with this:

```java
NativeSearchQuery query = new NativeSearchQueryBuilder()
	.withQuery(QueryBuilders.matchAllQuery())
	.build();
query.setPageable(PageRequest.of(0, 20));
SearchHits<Foo> searchHits = operations.search(query, Foo.class);
SearchPage<Foo> searchPage = SearchHitSupport.searchPageFor(searchHits, query.getPageable());
```

**Comment by sothawo** [comment]
This was updated in #2208
