### ISSUE TITLE
Cannot specify the attribut scrollTime with Stream Request

### ISSUE THREAD

**Issue by AnthonyDasse** [spring-projects/spring-data-elasticsearch#2133]
Hello,

In my project i use spring data elasticsearch  ( version 4.3.1 ) to request an elasticsearch cluster.
In the documentation ( https://docs.spring.io/spring-data/elasticsearch/docs/4.3.1/reference/html/#repositories ),
I see that I can use the Java Streams to return my results and this method uses the Scroll API functionality behind.

But I don't see anywhere the possibility to customize the scroll time whereas directly with the Scroll API I can do it : 
`Scroll scroll = new Scroll(TimeValue.timeValueMinutes(20L));`

Exemple of one method of my repository : 
`
public interface MyRepository extends ElasticsearchRepository<MyModel, String> {

@Query{".................."}
Stream<MyModel> findAllIWithStream(String fromTimestamp, String toTimestamp);

}
`

can you help me ?

if i should add more details, please get back to me.

Anthony

**Comment by sothawo** [comment]
You cannot specify the scroll time when using repositories. To customize this you need to use the lower level `ElasticsearchOperations.searchForStream(...)` methods and pass in a `Query`. A `Query` can have a scrolltime set.

Might be something to consider when #2062 is worked upon.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
