### ISSUE TITLE
Make the new client the default, deprecate the RestHighLevelClient and make it optional

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#2159]

**Comment by ztomic** [comment]
Hi, with new client IndicesTemplate is missing `getAliases` and `getAliasesForIndex` implementations. Is it by mistake or user of library must implement that calls on their own since new client is now default?

**Comment by sothawo** [comment]
@ztomic thanks for pointing this out. I missed that, created #2209 for that

**Comment by ztomic** [comment]
No problems, I spotted that while trying to test new version on product running on Spring Boot 2.7
