### ISSUE TITLE
When will the version 4.4.x be released?

### ISSUE THREAD

**Issue by nftscan2022** [spring-projects/spring-data-elasticsearch#2161]
@sothawo Hi, when will you plan to release the version 4.4.x，since we just need the search_after for elasticsearch operations.

**Comment by sothawo** [comment]
hm, support for _search_after_ was added with #1143 in April 2019

**Comment by sothawo** [comment]
and to answer the question> Version 4.4.0 was released today.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
