### ISSUE TITLE
How to set timezone

### ISSUE THREAD

**Issue by zhaoyunxing92** [spring-projects/spring-data-elasticsearch#2173]
I want to use the `Asia/Shanghai` timezone format date, or use the default timezone of my system, I need a place where I can set it.

**Comment by sothawo** [comment]
Can you please elaborate with a runnable example what the problem is? 

If you need to use temporal information with a time zone, use `java.time.ZonedDateTime` as the type for your data and set the timezone when creating such an object.

From having a look at your PR it seems that you still use `java.util.Date`. An instance of this class does not have a timezone associated with it, it is defined to be in the UTC timezone (or UT) see https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Date.html

The classes in the ` java.time` package were introduced in Java 8 in 2014, 8 years ago.

If you want to use `java.util.Date`  it is your responsiblility to set an object of this to the instant in UTC that corresponds to the point in time that represents your time zone.

**Comment by sothawo** [comment]
btw, I just checked out your code; I breaks 4 existing tests. 

When adding functionality, do not change existing tests. Add new one supporting additions you make. Don't remove existing functionality until it identified as a bug. And there I don't see a bug here.

**Comment by zhaoyunxing92** [comment]
> I still see no issue or need to change something in Spring Data Elasticsearch .

I also agree, but I think it would be better if Sping Data Elasticserch can provide this capability.Just like jackson's format, users can set the timezone themselves. Of course, I know that replacing java.util.Date is the best solution, but this Changing business is hard to bear

**Comment by sothawo** [comment]
You can set the timezone yourself in your application. Spring Data Elasticsearch adheres toi the specifications, and for `java.util.Date` this is that it is a point in time in the UTC timezone, I linked the Javadoc in a previous comment.

And anyhow, what good would it be to set a timezone to the system's value? If I run an application on my machine that would be UTC+1. If I run it in AWS or Google cloud that might be UTC or any pother timezoe. Spring Data Elasticsearch is a library that cannot make assumptions about what the user of the library intends.

So use property data types that support the use of timezones (there were reasons why these data types were introduced back in Java 8). And yes, converting an application to that is work that probably should have been done already years ago.

**Comment by zhaoyunxing92** [comment]
> You can set the timezone yourself in your application. Spring Data Elasticsearch adheres toi the specifications, and for `java.util.Date` this is that it is a point in time in the UTC timezone, I linked the Javadoc in a previous comment.
> 
> And anyhow, what good would it be to set a timezone to the system's value? If I run an application on my machine that would be UTC+1. If I run it in AWS or Google cloud that might be UTC or any pother timezoe. Spring Data Elasticsearch is a library that cannot make assumptions about what the user of the library intends.
> 
> So use property data types that support the use of timezones (there were reasons why these data types were introduced back in Java 8). And yes, converting an application to that is work that probably should have been done already years ago.

I have done this.I just want to do a backward compatibility on the framework instead of asking the business to modify it.Many frameworks support custom timezones,It also supports when I use es api.

Programs in UTC+1 timezone should run on UTC+1 systems,At least I need to ensure these when deploying the program.

[L90-L94](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/convert/ElasticsearchDateConverter.java#L90-L94) Is it better to set the timezone during initialization or to set the timezone during formatting?
