### ISSUE TITLE
How is Spring Data Elasticsearch compatible with previous versions of Elasticsearch?

### ISSUE THREAD

**Issue by arnauldvm** [spring-projects/spring-data-elasticsearch#2184]
I'm not sure how I should interpret the information in the compatibility matrix: https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#preface.versions

For example, SD ES 4.2.x is associated with ES 7.12.0.
Does that mean that it requires:

- (A) exactly that version of ES?
- or (B) at least that version of ES?
- or (C) a most that version of ES?

Assuming I have a cluster with an older version of ES (e.g. 7.6.2), and that for some reason I can't upgrade yet.

- If (A), I should use SD ES 4.0.x
- If (B), I should use SD ES 4.0.x or earlier
- If (C), I should use SD ES 4.0.x or later (so I could use 4.2.x too)

**Comment by sothawo** [comment]
It means that SDE 4.2.x is built against the client libraries of Elasticsearch  in version 7.12.0 and was tested against an Elasticsearch instance with that version.

You can always try to overwrite the version of the Elasticsearch client libraries in your maven or gradle configuration or run the application against a different cluster version. 

The thing to do: Test your application thoroughly against the older cluster, it might work if you do not use functionality that was not yet available in the 7.6 cluster.

**Comment by arnauldvm** [comment]
In summary, if I understood correctly:

SD ES 4.2.x:
- will work without problem with ES 7.12.0
- "might" work with an older version, without guarantee (=> extensive testing required)

By extension, for each new version of SD ES, we should:
- either upgrade the ES cluster
- or do extensive testing to qualify the new combination

**Comment by sothawo** [comment]
That is correct. But in my experience the backward "wire compatibility" of new Elasticsearch client library versions to older cluster versions of the same major version should be pretty stable. Whereas for example changing the client library version to something different than what Spring Data Elasticsearch was built against has more chances to break.

In the current project I am working in (not Spring Data Elasticsearch but Spring Data MongoDB) we  have covered our business use cases in integration tests and use [TestContainers](https://www.testcontainers.org/) for the backend. So we can easily test that switching to a new client version works with the running server, and when changing the server version we can test this as well.

**Comment by arnauldvm** [comment]
Thanks for the answers. For my part I don't need extra feedback for now.
