### ISSUE TITLE
Prefix query is not working together with ids query

### ISSUE THREAD

**Issue by stsypanov** [spring-projects/spring-data-elasticsearch#2188]
I'm implementing custom repository based on Spring Data Elasticsearch. Here is the entity:
```java
@Document(indexName = "product", createIndex = false)
public class ProductDocument implements Serializable {

    @Id
    private String id;

    @NotNull
    private String name;
}
```
And here is repository implementation:
```java
public interface ProductRepositoryCustom {
    List<ProductDocument> findByIdsAndName(List<String> productIds, String name);
}

public interface ProductRepository extends ElasticsearchRepository<ProductDocument, String>, ProductRepositoryCustom {
}

public class ProductRepositoryCustomImpl implements ProductRepositoryCustom {
    private final ElasticsearchOperations operations;
    private final IndexCoordinates indexCoordinates;
    private final Class<ProductDocument> clazz;

    public ProductRepositoryCustomImpl(ElasticsearchOperations operations) {
        this.operations = operations;
        this.clazz = ProductDocument.class;
        this.indexCoordinates = operations.getIndexCoordinatesFor(clazz);
    }

@Override
public List<ProductDocument> findByIdsAndName(List<String> productIds, String name) {
    Query query = new NativeSearchQueryBuilder()
            .withIds(productIds)
            .withQuery(QueryBuilders.prefixQuery("name", name))
            .build();

    return operations.search(query, clazz, indexCoordinates)
            .stream()
            .map(SearchHit::getContent)
            .collect(Collectors.toList());
}
}
```
The problem I'm facing is that the query is not working, e.g. I save into ES items like
```java
productRepository.saveAll(Arrays.asList(
                ProductDocument.builder().id("1").name("Pikachu1").build(),
                ProductDocument.builder().id("2").name("Pikachu2").build(),
                ProductDocument.builder().id("3").name("Pikachu3").build(),
                ProductDocument.builder().id("4").name("Pikachu4").build(),
                ProductDocument.builder().id("5").name("Pikachu5").build()
        )
```
and then call the method
```java
assertThat(productRepository.findByIdsAndName(List.of("1", "2"), "Pika")).hasSize(2);
```
repository method returns an empty list and assertion fails. I've also tried to implement query like
```java
Query query = new NativeSearchQueryBuilder()
        .withFilter(QueryBuilders.idsQuery().addIds(productIds.toArray(String[]::new)))
        .withQuery(QueryBuilders.prefixQuery("name", name))
        .build();
```
but it fails either. The problem seems to be about prefixQuery because when I remove it the query works.

**Comment by sothawo** [comment]
comment copied from your SO question:
> The `ids` set on a `Query` are used when that query is an argument to a get or multiget operation. The whole search for me does not make sense: If you have the ids of the documents (which are unique), what do you need a prefix search for? You cannot have two `ProductDocument`s with the same id and different prefix

**Comment by stsypanov** [comment]
Wouldn't ES apply prefix query for the documents filtered by provided ids?

**Comment by stsypanov** [comment]
> when you use the idsQuery() it should; 

Yeah, this was actually the first thing I tried:
```java
@Override
public List<ProductDocument> findByIdsAndName(List<String> productIds, String name) {
    Query query = new NativeSearchQueryBuilder()
            .withIds(productIds)
            .withQuery(QueryBuilders.prefixQuery("name", name))
            .build();

    return operations.search(query, clazz, indexCoordinates)
            .stream()
            .map(SearchHit::getContent)
            .collect(Collectors.toList());
}
```

> does a query only using the prefix value work?

No, it's not working for me.

> Can you try such a query with a REST client like Kibana or Postman to see if Elasticsearch returns anything?

I will try to do it tomorrow, as I run this on testcontainers without Kibana.

Btw, `name` is declared of type `text` in my index declaration. Could it be a reason for prefix query is not working?

**Comment by sothawo** [comment]
What I do in my sample apps - and even when developing on Spring Data Elasticsearch - is to use an intercepting proxy, almost all of the time I use [OWASP ZAP](https://owasp.org/www-project-zap/), but also have used [Burp](https://portswigger.net/burp).

I just start ZAP, which by default listens on port 8080, and reconfigure my spring boot application to use  a different port (9090), and in the configuration I setup the proxy:

```java
ClientConfiguration clientConfiguration = ClientConfiguration.builder()
	.connectedTo("localhost:9200")
	.withProxy("localhost:8080")
	.build();
```

Then you can inspect every request between the application and Elasticsearch

**Comment by sothawo** [comment]
syntax is alright (https://www.elastic.co/guide/en/elasticsearch/reference/8.2/query-dsl-prefix-query.html).

Could it be that in your cluster `search.allow_expensive_queries` has been set to false (https://www.elastic.co/guide/en/elasticsearch/reference/8.2/query-dsl-prefix-query.html#prefix-query-allow-expensive-queries)?

**Comment by stsypanov** [comment]
I'm not sure whether the property is set to `true` or `false` (by default it's `true`), however as it comes from the [doc](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/query-dsl-prefix-query.html#prefix-query-allow-expensive-queries)
> Prefix queries will not be executed if [search.allow_expensive_queries](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/query-dsl.html#query-dsl-allow-expensive-queries) is set to false. However, if [index_prefixes](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/index-prefixes.html) are enabled, an optimised query is built which is not considered slow, and will be executed in spite of this setting.

So I've modified the index as
```json
DELETE product
PUT product
PUT product/_mapping
{
      "dynamic" : "strict",
      "properties" : {
        "_class" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword"
            }
          }
        },
        "id" : {
          "type" : "keyword"
        },
        "name" : {
          "type" : "text",
          "index_prefixes": {
            "min_chars" : 4,
            "max_chars" : 10
          }
        }
      }
}
```
The only way I can make this work is either changing type of `name` field to `keyword` or rewriting the code as:
```java
        BoolQueryBuilder queryBuilder = new BoolQueryBuilder();
        queryBuilder.must(QueryBuilders.idsQuery().addIds(productIds.toArray(String[]::new)));
        queryBuilder.must(QueryBuilders.matchBoolPrefixQuery("name", name));

        Query query = new NativeSearchQueryBuilder().withQuery(queryBuilder).build();

        return operations.search(query, clazz, indexCoordinates)
                .stream()
                .map(SearchHit::getContent)
                .collect(Collectors.toList());
```

**Comment by stsypanov** [comment]
One more example which is not working either:
```java
Query query = new NativeSearchQueryBuilder()
        .withIds(productIds)
        .withQuery(QueryBuilders.matchBoolPrefixQuery("name", name).operator(Operator.AND))
        .build();

return operations.search(query, clazz, indexCoordinates)
        .stream()
        .map(SearchHit::getContent)
        .collect(Collectors.toList());
```
This code fails on assetion
```java
assertThat(productRepository.findByIdsAndName(ids.subList(0, 2), "Pika")).hasSize(2);
```
with 
```
Caused by: java.lang.AssertionError:
Expected size:<2> but was:<5> in:
<[ProductDocument(id=1, name=Pikachu1),
ProductDocument(id=2, name=Pikachu2),
ProductDocument(id=3, name=Pikachu3),
ProductDocument(id=4, name=Pikachu4),
ProductDocument(id=5, name=Pikachu5)]>
```
i.e. it ignores prodived `ids` and respects only prefix.

I've put a breakpoint in `AbstractQuery.getIds()` and realized that it's not called at all.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
