### ISSUE TITLE
RequestFactory#updateByQueryRequest creates request with only the first index from IndexCoordinates

### ISSUE THREAD

**Issue by idemidenko** [spring-projects/spring-data-elasticsearch#2191]
### Version 
spring-data-elasticsearch:4.2.3

### Description
`updateByQueryRequest` takes only the fist index from `IndexCoordinates` and therefore creates an update request with the single index, instead of that the request should contain all indices passed in `IndexCoordinates`

```
public UpdateByQueryRequest updateByQueryRequest(UpdateQuery query, IndexCoordinates index) {

    String indexName = index.getIndexName(); // takes only the fist index from IndexCoordinates
    // String[] indexName = index.getIndexNames(); - should take all index names instead
    final UpdateByQueryRequest updateByQueryRequest = new UpdateByQueryRequest(indexName);
    // ...
}
```

**Comment by sothawo** [comment]
Note: The code in _main_ using the new Elasticsearch client handles this correctly, must be fixed in the deprecated code for the old client there and backported to 4.4 and 4.3 (4.2 is out of maintenance)
