### ISSUE TITLE
Feature request: allow streaming over composite aggregation results

### ISSUE THREAD

**Issue by razine-bensari** [spring-projects/spring-data-elasticsearch#2218]
One of the best features of ES is to be able to make use of aggregations in search queries. 
However, it becomes a bit difficult to iterate over composite aggregation results that spans multiple pages.

The purpose of this issue is to add support to iterate over/stream composite aggregation results.

Currently there is only support for search hits

**Comment by sothawo** [comment]
> composite aggregation results that spans multiple pages.

what do you mean with that?

**Comment by sothawo** [comment]
Ok, I never had paging in aggs, something new for me.

About aggregations in Spring Data Elasticsearch: We do not provide an abstraction of both the classes to build an aggregate into a query and for parsing the result. This is why you need to use a `NativeSearchQuery` in version up to 4.4 or a `NativeQuery` from version 5 on (using the new Elasticsearch client). 

To have something implemented like this would mean that we would need the whole structure of aggregation request and response classes and woul;d have to build a mapping for the classes that were used in the old `RestHighLevelClient` as well as for the classes used in the new `ElasticsearchClient` - even taking into consideration that we wouldn't do that for the deprecated client,  the `co.elastic.clients.elasticsearch._types.aggregations` for the new client contains alone 251 classes. 

So you will need to build the request containing the `after` parameter taken from the `after_key`response by yourself.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
