### ISSUE TITLE
Don't try to write readonly id property after indexing

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#2230]
In `AbstractElasticsearchTemplate.updateIndexedObject()`  the following code is used to set the id property of an entity:

```java
if (indexedObjectInformation.getId() != null && idProperty != null
		&& idProperty.getType().isAssignableFrom(String.class)) {
	propertyAccessor.setProperty(idProperty, indexedObjectInformation.getId());
}
```

Here it must be checked as well if the id property is writeable - check reactive part as well

**Comment by sothawo** [comment]
> If the doc in elasticsearch is {_id: a, _source: {id:b, whatever:xxx}}, the Entity object's properties are all set well after deserializing, like fieldId=a, realId=b, whatever=xxx.

I think there is an error in your example: After reading `fieldId` should be `b` and `realId` should be `a`.

The workaround with adding the `@ReadOnlyProperty` only worked because of the wrong implementation in Spring Data Elasticsearch which wrote a value back into a property although this is marked as being read only. By fixing this behaviour in this issue this does not work any longer. I need to update my answer in SO.

The real problem is, that the id property is not only used as identifier in Elasticsearch but also is written into the source - not into the mapping. The addition to the mapping you see is done by Elasticsearch when the data is written to the source and there is no mapping for the field.

What would be needed here is a possibility to configure Spring Data Elasticsearch to **not** write the id property into the document (I created #2364). 

To get the _id back into your _realId_ in the current version, leave the `@ReadOnlyProperty` on the id property. In addition to that, you need a `AfterConvertCallback`:

```java
#import org.springframework.data.elasticsearch.core.event.AfterConvertCallback;

@Component
public class EntityAfterConvertCallback implements AfterConvertCallback<Entity> {

	@Override
	public Entity onAfterConvert(Entity entity, Document document, IndexCoordinates indexCoordinates) {
		entity.setRealId(document.getId());
		return entity;
	}
}
```

This is invoked after the Entity is set up - and is missing the realId; in this callback you then set the document's id (as returned from Elasticsearch) into the realId property.

**Comment by puppylpg** [comment]
Thanks for the qucik response. I'll try this workaround, and totally agree what expresses in #2364 
As for the example above, yeah i wrote it wrongly,  the realId should be `a`. I'll correct it to avoid misleading.
