### ISSUE TITLE
Add possibility to define runtime fields in a NativeSearchQueryBuilder

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-data-elasticsearch#2259]
We should extend the `NativeSearchQueryBuilder` to be able to add `runtime_mappings` to a search request. See https://www.elastic.co/guide/en/elasticsearch/reference/7.12/runtime-search-request.html

Related: https://github.com/spring-projects/spring-data-elasticsearch/issues/1971

**Comment by sothawo** [comment]
This was implemented a couple of days ago in #2251
