### ISSUE TITLE
InvalidDefinitionException when serializing ElasticsearchAggregations to JSON

### ISSUE THREAD

**Issue by mdgilene** [spring-projects/spring-data-elasticsearch#2262]
Get the following error when attempting to return `SearchHits<>` from a controller endpoint.

```java
@PostMapping("/search")
public SearchHits<MyDocument> search(@Valid @RequestBody SearchQuery query) {
    return searchService.search(query);
}
```

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.springframework.data.elasticsearch.core.ElasticsearchAggregations]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.data.elasticsearch.core.ElasticsearchAggregations and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.data.elasticsearch.core.SearchHitsImpl["aggregations"])] with root cause

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.springframework.data.elasticsearch.core.ElasticsearchAggregations and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.data.elasticsearch.core.SearchHitsImpl["aggregations"])
```

Elasticsearch Version: 7.17.5
Spring Data ES Version: 4.4.1

**Comment by sothawo** [comment]
The concrete type of the <AggregationsContainer> that is contained in the `SearchHits` depends on the client that is used. The old `RestHighLevelClient` returns totally different classes than the new `ElasticsearchClient`, and once there will be support for an Opensearch client, these are different classes then as well.

If Spring Data Elasticsearch were to provide a custom class encapsulating these, this would mean to implement for each client library a mapping logic for more than 100 classes (currently in the new Elasticsearch client) and therefore we just return the original client classes. It is in the responsibility of the application then to process them.

If you want to return this property via a JSON response, this is out of scope for Spring Data Elasticsearch.

You will need to provide a serializer for the class `org.springframework.data.elasticsearch.core.ElasticsearchAggregations` and the `org.elasticsearch.search.aggregations.Aggregations` it contains.

**Comment by mdgilene** [comment]
Ahh I see. I guess my confusion was that this used to work fine a few versions back and I didn't see any notes of a breaking change regarding these classes. I was able to directly return the aggregation results from an endpoint. I guess if now I need to go down the route of writing a custom serializer for these types I might as well just stop returning the response directly and convert it into a custom POJO with a schema of my choosing.
