### ISSUE TITLE
java.lang.NoClassDefFoundError: jakarta/json/stream/JsonParser$Event

### ISSUE THREAD

**Issue by cdalexndr** [spring-projects/spring-data-elasticsearch#2269]
`RuntimeFieldType.Double.jsonValue()` causes the error.

Gradle dependencies shows that jakarta.json-api is downgraded from 2.0.1 to 1.1.6:
```
+--- co.elastic.clients:elasticsearch-java:7.17.3
|    |    +--- org.elasticsearch.client:elasticsearch-rest-client:7.17.3 -> 7.17.4 (*)
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- jakarta.json:jakarta.json-api:2.0.1 -> 1.1.6
|    |    \--- org.eclipse.parsson:parsson:1.0.0
|    |         \--- jakarta.json:jakarta.json-api:2.0.1 -> 1.1.6
```

Sample project: https://github.com/cdalexndr/spring-data-elasticsearch-2269

**Comment by sothawo** [comment]
Spring Data Elasticsearch doe not use gradle. How do you set up the dependencies in ypur project? Which version of Spring Data Elasticsearch do you use?

The main branch uses elasticsearch-java:8.3.3. When you are using Spring Data Elasticsearch 4.4.x and want to integrate the new client, check the documentation at https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch-migration-guide-4.3-4.4.new-clients especially the information about setting the version of `jakarta-json`
