### ISSUE TITLE
Incorrect Update API Path

### ISSUE THREAD

**Issue by tenaciousprevailer** [spring-projects/spring-data-elasticsearch#2276]
Spring Boot Version: 2.7.3 (Issue exists in 2.7.2, tried in that)
Elasticsearch Server Version: 8.1.2
The update path that spring data elastic search uses is:
POST /index/_doc/{docId}/_update
which gives error: no handler found for uri

Instead the path should be:
POST /index/_update/{docId}

Please fix this. I've to do a lot of workarounds to fix it.

**Comment by sothawo** [comment]
Please provide a runnable code/ minimal project that demonstrates this error.

**Comment by tenaciousprevailer** [comment]
From org.springframework.data.elasticsearch.client.util.RequestConverters.update(UpdateRequest updateRequest)

Below is the code snippet.
public static Request update(UpdateRequest updateRequest) {
		String endpoint = endpoint(updateRequest.index(), updateRequest.type(), updateRequest.id(), "_update");

This is causing the error, the endpoint generated is incorrect.
Refer the article on what the endpoint should be: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-update.html

Code FIX (Suggestion, Please review & test before accepting) :P:
String endpoint = endpoint(updateRequest.index(), "_update", updateRequest.id());

**Comment by sothawo** [comment]
Seems no one else up to now used _update_ with the reactive implementation, thanks for bringing this
 up. 

For the reactive client implementation up to version 4.4 we needed to copy code from the Elasticsearch library (it was still allowed at that time). This copied code was not adapted when in version 7 the `type` parameter was removed.

**Comment by tenaciousprevailer** [comment]
@sothawo 
can you please provide release version, the fix will be part of ?

**Comment by sothawo** [comment]
It will be in the next major release as well in the next bugfix releases for 4.4 and 4.3.
