### ISSUE TITLE
spring data elasticsearch can't deserialize "single or array" object field

### ISSUE THREAD

**Issue by puppylpg** [spring-projects/spring-data-elasticsearch#2280]
The problem is posted [here](https://stackoverflow.com/questions/73437162/spring-data-elasticsearch-cant-deserialize-array-of-objects) at first time.

[Here](https://github.com/puppylpg/spring-data-elasticsearch-deserialize-array-or-object-field) is the repo i created by spring boot to reproduce it:
1. start a elasticsearch of version 7.12, maybe with docker - `docker run --name es01-test --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e ES_JAVA_OPTS="-Xms1024m -Xmx1024m" docker.elastic.co/elasticsearch/elasticsearch:7.12.1`;
2. see `resources/insert.txt`: add 4 docs manually;
3. just click and run the project(or through maven: `mvn clean spring-boot:run`);

Errors will be logged into `logs/log`.

I'll also try to sovle it(if free this weekend, not guaranteed :D)

Thanks for your efforts.

**Comment by sothawo** [comment]
Interesting finding while working on this: Your _one-hobby_ case only works because Lombok is providing an all-args constructor. Using a normal POJO it fails.

Glad I removed all that lombok stuff over a year ago

**Comment by sothawo** [comment]
Implemented in _main_ and backported to _4.4.x_ and _4.3.x_.

**Comment by rishiraj88** [comment]
@sothawo , please give me a resource link to read how backporting is implemented.

**Comment by sothawo** [comment]
check the branches 4.4.x and 4.3.x
