### ISSUE TITLE
Path query

### ISSUE THREAD

**Issue by zhouixi** [spring-projects/spring-data-elasticsearch#2291]
GET test_index/_doc/3/_termvectors?  fields=name

Is there any API support for this query

**Comment by sothawo** [comment]
Do you mean the _TermVectors_ API? This is curremtly not supported.

Btw, the syntax for this call according to the docs (https://www.elastic.co/guide/en/elasticsearch/reference/8.4/docs-termvectors.html#docs-termvectors) would be

    GET /<index>/_termvectors/<_id>

**Comment by zhouixi** [comment]
> 
There is no API package in Spring Boot

**Comment by zhouixi** [comment]
> 你是说_TermVectors_ API 吗？目前不支持此功能。
> 
> 顺便说一句，根据文档（https://www.elastic.co/guide/en/elasticsearch/reference/8.4/docs-termvectors.html#docs-termvectors），此调用的语法将是
> 
> ```
> GET /<index>/_termvectors/<_id>
> ```

ok
