### ISSUE TITLE
spring data elasticsearch official doc catalog mismatch with content

### ISSUE THREAD

**Issue by puppylpg** [spring-projects/spring-data-elasticsearch#2299]
I don't know this official doc is managed by you or spring data team, but it's official doc about spring data elasticsearch, so i just post the issue here:
- https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.repositories.annotations

chapter 8.4 will be showed in catalog as chapter 5.3.1 :(

and chapter 8.2.3 retargets the url to `#`

**Comment by sothawo** [comment]
This seems not to be an issue in the current milestone (https://docs.spring.io/spring-data/elasticsearch/docs/5.0.0-M6/reference/html/#elasticsearch.annotation) anymore. Though I don't know when this was fixed.

**Comment by puppylpg** [comment]
that's interesting :smile_cat: 

but chapter 8.2.3 still retargets the url to `#`

**Comment by sothawo** [comment]
Thanks for the hint, I found quite some more of these.
