### ISSUE TITLE
@Id field is stored twice

### ISSUE THREAD

**Issue by maxsidorov** [spring-projects/spring-data-elasticsearch#23]
Hello, I noticed that @Id field is stored twice in ES in "_id" and "id" fields. Is there any reason of it? It seems like an additional unnecessary storing and might be confusing.

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

The value in `_id` is Elasticsearch's way of storing the id information, no way to change that. That the id is as well stored in the `_source.id` field comes from the fact, that it is part of the entity. If you do not want to have it in the `_source` in ES, you can specify it like this:

```java
@Id
@ReadOnlyProperty
private String id;
```
