### ISSUE TITLE
update document partially by specified entity

### ISSUE THREAD

**Issue by puppylpg** [spring-projects/spring-data-elasticsearch#2304]
Now if we wanna update a document, a UpdateQuery must be constructed manually, but this is a little unnecessary. Especially for the condation that:
1. get a document from index;
2. update some field of the document;
3. write the doc back;

Problems are:
1. if write the doc back using `save(ENTITY)`, values of fields which are unmapped in the entity will be discarded;
2. if write the doc back using `update(UpdateQuery, IndexCoordinates)`, a UpdateQuery and a IndexCoordinates must be constructed manually;

So i think `update(T entity)` is necessary, and spring-data-elasticsearch can construct the UpdateQuery and IndexCoordinates automatically, which is very handy.

**Comment by sothawo** [comment]
Have to reopen; I noticed, that the PR was targeting the wrong branch. Can you please create a new PR with the changes - then with what I commented and target the `main` branch?

**Comment by puppylpg** [comment]
> 

Sorry for the wrong branch, and i'll polish and reopen a PR for `main`

**Comment by puppylpg** [comment]
submited: #2310
