### ISSUE TITLE
I can't find the searchQuery(Query) method 

### ISSUE THREAD

**Issue by lihengcn** [spring-projects/spring-data-elasticsearch#2309]
```
/**
* @deprecated since 4.0, use {@link #searchQuery(Query)}, standard repository method naming or @{@link Query}
*             annotated methods, or {@link org.springframework.data.elasticsearch.core.ElasticsearchOperations}.
*/
@Deprecated
Page<T> search(QueryBuilder query, Pageable pageable);
```
search method show deprecated, but I did not find the recommended searchQuery(Query) method 

How should I implement dynamic conditional pagination?

**Comment by sothawo** [comment]
From which class in which version is that code snippet?

**Comment by lihengcn** [comment]
> From which class in which version is that code snippet?

spring-boot:2.4.5
spring-data-elasticsearch:4.1.8

**Comment by sothawo** [comment]
Still don't know in which class this was.

If you want to do paging you can do it easily:

### Using repository methods:

Define a method that returns a `SearchPage` and pass in a `Pageable`, see for example https://github.com/spring-projects/spring-data-elasticsearch/blob/4.4.3/src/test/java/org/springframework/data/elasticsearch/repositories/custommethod/CustomMethodRepositoryIntegrationTests.java#L1601-L1615 and the other tests there as well.

### Using `ElasticsearchOperations`:

Use any of the `SearchOperatons.search()` method that takes a `Query` and set the `Pageable` on the query itself. You can then wrap the returned `SearchHits` with a call like this:
```
SearchPage<T> page = SearchHitSupport.searchPageFor(searchHits, query.getPageable());
```

**Comment by lihengcn** [comment]
I'm sorry, I didn't make that clear
[Which class is here](https://github.com/spring-projects/spring-data-elasticsearch/blob/4.1.x/src/main/java/org/springframework/data/elasticsearch/repository/ElasticsearchRepository.java)
I didn't find a recommendation for the search method, Where is the searchQuery(Query) method?

The way I wrote it before was this， How should I write the new version？
```
    @Test
    public void search() {
        String name = "phone";
        Long age = null;
        BoolQueryBuilder boolQueryBuilder = QueryBuilders.boolQuery();
        if (StringUtils.hasText(name)) {
            boolQueryBuilder.must(QueryBuilders.termQuery("name", name));
        }
        if (age != null) {
            boolQueryBuilder.must(QueryBuilders.termQuery("age", age));
        }
        Page<Product> page = productRepository.search(boolQueryBuilder, PageRequest.of(0, 10));
    }
```

**Comment by sothawo** [comment]
Just define a repository method
```
SearchPage<Product> findByNameAndAge(String name, Long age, Pageable pageable);
```
or -as I already wrote - use the `ElasticsearchOperations`.

**Comment by lihengcn** [comment]
I decided to go with ElasticsearchOperations, thanks for your help
