### ISSUE TITLE
Can I implement Multi terms?

### ISSUE THREAD

**Issue by cglcl** [spring-projects/spring-data-elasticsearch#2311]
Can I use spring-data-elasticsearch to implement [Multi Terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-aggregations-bucket-multi-terms-aggregation.html) this? I read it doesn't seem to support it, is there any way for me to implement it through this library?
Like it
```
{
	"size": 1000,
	"aggs": {
		"msp_quotas": {
			"multi_terms": {
				"terms": [{
					"field": "namespace"
				}, {
					"field": "resource"
				}, {
					"field": "provider"
				}]
			}
		},
		"aggs": {
			"product_stats": {
				"stats": {
					"field": "duration",
					"missing": "0"
				}
			}
		}
	}
}
```

**Comment by sothawo** [comment]
You can use everything that the original Elasticsearch client libraries offer to build your aggregations and parse the results. Spring Data Elasticsearch does not have an own implementation for this. To integrate it with Spring Data Elasticsearch you use for the versions up to the current 4.4 the `NativeSearchQueryBuilder` with its `withAggregations()` methods.

From the next version on - that uses the new Elasticsearch client - that will be the `NativeQueryBuilder` that has a `withAggregation()` method for this.

**Comment by cglcl** [comment]
Yes, this should be provided by the Elasticsearch client libraries. I see that the code is just a layer of encapsulation, and its original functions are provided.
