### ISSUE TITLE
How can I get the real response data of Elastic using NativeSearchQueryBuilder and ElasticsearchRestTemplate instead of encapsulated?

### ISSUE THREAD

**Issue by cglcl** [spring-projects/spring-data-elasticsearch#2317]
Recently, I am using ElasticsearchRestTemplate to query. I have a scenario where I need to get the original response data, but all the encapsulated data is returned to me. Since I am using NativeSearchQueryBuilder, how can I get the raw response data in this case?

I have tried subclassing ElasticsearchRestTemplate, but RequestFactory is protected and I cannot get the original response data unless I no longer use NativeSearchQueryBuilder.

At the same time, I also found a situation, but I haven't verified it yet, that is, Elastic will return _shards, but I looked at ElasticsearchRestTemplate, it doesn't seem to verify this `_shards _shards.successful+_shards.skipped == _shards.total` . When there is a problem with Elastic's shard, is it currently invisible?

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not give direct access to the response from Elasticsearch. If you want to get the direct response you have to build the ElasticsearchRequest request and parse the response by yourself. You can do the actual call by using the `execute` method of the `ElastcisearcghRestTemplate`:

```java
// cast the normal ElasticsearchOperations interface to the implementation
ElasticsearchRestTemplate template = (ElasticsearchRestTemplate) operations;

// build an Elasticsearch search request
SearchRequest searchRequest = new SearchRequest("index");
searchRequest.source().query(QueryBuilders.matchAllQuery());

// execute the request and get the Elasticsearch response
SearchResponse searchResponse = template.execute(client -> client.search(searchRequest, RequestOptions.DEFAULT));
```

As for the returned shard information: This is not processed by Spring Data Elasticsearch.

**Comment by cglcl** [comment]
But I think getting the raw response data in Spring Data Elasticsearch should support choosing this, which should be considered an optimization term.

**Comment by sothawo** [comment]
>should support choosing this,

Choosing what exactly? 

The purpose of Spring Data Elasticsearch is encapsulating and abstracting away store specific data handling. If you need to get to the low level response you can do so by using the `execute()` method.

Or, if you kind of want to intercept/ process every call you can setup a `ElasticsearchOperations` instance where the `execute()` method is overwritten, we do this for example  in the setup for the integration tests (https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/test/java/org/springframework/data/elasticsearch/junit/jupiter/ElasticsearchRestTemplateConfiguration.java#L89-L109) where we implement a retry when the `execute` throws a `DataAccessResourceFailureException`.

**Comment by cglcl** [comment]
ok
