### ISSUE TITLE
Trying to upgrade to 5.0.0, ElasticsearchRepositoryConfigExtension duplicated

### ISSUE THREAD

**Issue by sweiss435** [spring-projects/spring-data-elasticsearch#2375]
Am trying to upgrade our search api
Spring 7.5.0
`<dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>8.5.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-elasticsearch</artifactId>
            <version>5.0.0</version>
        </dependency>`
get

The following method did not exist:

    'java.lang.String org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension.getModuleIdentifier()'

The calling method's class, org.springframework.data.elasticsearch.repository.config.ElasticsearchRepositoryConfigExtension, was loaded from the following location:

    jar:file:/Users/.../.m2/repository/org/springframework/data/spring-data-elasticsearch/5.0.0/spring-data-elasticsearch-5.0.0.jar!/org/springframework/data/elasticsearch/repository/config/ElasticsearchRepositoryConfigExtension.class

doesn't make sense, all I did was update to 5.0.0.

**Comment by sothawo** [comment]
The method that is not found was introduced in spring-data-commons 3.0 that Spring Data Elasticsearch 5.0 is built on. Probably your setup does not pull in the correct version for that.
