### ISSUE TITLE
Nested sort seems to be missing

### ISSUE THREAD

**Issue by sweiss435** [spring-projects/spring-data-elasticsearch#2376]
before we used to be able to do 

`GeoDistanceSortBuilder geoDistanceSortBuilder = SortBuilders
                .geoDistanceSort(locationFieldName, poi.getFirst(), poi.getSecond())
                .unit(DistanceUnit.MILES)
                .order(SortOrder.ASC);
 queryBuilder.withSort(geoDistanceSortBuilder);
`
now all I can do is 
`queryBuilder.withSort(Sort.by(Sort.Order.asc(locationField)));`
just pass in a field, but need to do a nested query to generate a geo_distance field from which to sort on

**Comment by sothawo** [comment]
For implementing nested sort there is a ticket #1783 

Which version of Spring Data Elasticsearch are you referring to?

`GeoDistanceSortBuilder` was coming from Elasticsearch 7 libraries, what was the type of the `queryBuilder` you use in your code? Spring Data Elasticsearch has the `org.springframework.data.elasticsearch.core.query.GeoDistanceOrder` since version 4.0.

**Comment by sweiss435** [comment]
I can't imagine we are the only ones that need to do a lat/lon nested query to sort by distance.  #1783 looks pretty old and stale, how are we suppose to use elastic 8.x if it lack this?

**Comment by sothawo** [comment]
When you use `NativeQueryBuilder` you can do:

1. Use the Elasticsearch classes:

```java
var sortOptions = new SortOptions.Builder()
	.geoDistance(gd -> gd
		.field("locationFieldName")
		.location(loc -> loc
			.latlon(latlon -> latlon
				.lat(12.34)
				.lon(23.45)
			)
		)
		.unit(DistanceUnit.Miles)
	)
	.build();

var query = NativeQuery.builder().withSort(sortOptions).build();
```
or just:
```java
var query = NativeQuery.builder()
	.withSort(sob -> sob
		.geoDistance(gd -> gd
			.field("locationFieldName")
			.location(loc -> loc
				.latlon(latlon -> latlon
					.lat(12.34)
					.lon(23.45)
				)
			)
			.unit(DistanceUnit.Miles)
		)
	)
	.build();
```

2. Use the Spring Data Elasticsearch class for geo distance order:
```java
var order = new GeoDistanceOrder("locationFieldname", new GeoPoint(12.34, 23.45)).withUnit("miles");
var query = NativeQuery.builder().withSort(Sort.by(order)).build();
```

**Comment by sweiss435** [comment]
Thanks!  That seems to get me a lot closer.
It does still fail due to "query_shard_exception","reason":"it is mandatory to set the [nested] context on the nested sort field: [associatedLocations.location].

From what I can see in the elastic documentation, there's suppose to be a 'path' in the nested query.  At least I think that is the issue, any idea how I set that?

**Comment by sothawo** [comment]
The nested sort only seems available in the `co.elastic.clients.elasticsearch._types.FieldSort` and it's builder, the API documentation has this for field sorts as well (https://www.elastic.co/guide/en/elasticsearch/reference/8.5/sort-search-results.html#nested-sorting).

The `co.elastic.clients.elasticsearch._types.GeoDistanceSort` does not have this, but I cannot find it in the API docs either (https://www.elastic.co/guide/en/elasticsearch/reference/8.5/sort-search-results.html#geo-sorting).

But that's an Elasticsearch topic, not Spring Data Elasticsearch then. You might want to open an issue in Elastic's repository for the client at https://github.com/elastic/elasticsearch-java/issues
