### ISSUE TITLE
No way to set units on GeoDistanceQuery

### ISSUE THREAD

**Issue by sweiss435** [spring-projects/spring-data-elasticsearch#2377]
We have a query like 
Query query = QueryBuilders
                    .geoDistance()
                    .location(q -> q.latlon(geoLocation))
                    .distanceType(GeoDistanceType.Plane)
                    .field(locationField)
                    .distance("100000000")
                    .build()._toQuery();
            additionalFiltersQueryBuilder.must(query);
            
 The distance field before upgrading to elastic 8 was numerical, now it's a string.  Want to use miles, but playing around with strings it almost seems like it's in meters or something.  At 200, I get few or no results, then moving it up to 10000, 100000, etc, I get more and more results.  It's strange it a string first of all, but there is zero info on what that string is by default.  If I knew it was meters I could convert our miles param to feed it.  There is no .unit() method on the GeoDistanceQuery.Builder, which seems like the sort of this needed here.

**Comment by sothawo** [comment]
You'll most likely find information about these parameters in the API documentation, for the `geo_distance` query this is https://www.elastic.co/guide/en/elasticsearch/reference/8.5/query-dsl-geo-distance-query.html From that page you can get to the definition of distance unit at https://www.elastic.co/guide/en/elasticsearch/reference/8.5/api-conventions.html#distance-units. So a distance of 100 miles would be `"100mi" or "100miles"

**Comment by sweiss435** [comment]
Thanks
