### ISSUE TITLE
Is there a reason why creating a RestClient is so "hard"?

### ISSUE THREAD

**Issue by riba2101** [spring-projects/spring-data-elasticsearch#2384]
Hi,

`RestClientBuilderConfiguration` is package private and the builder creation is happening as a bean?  would it make more sense to actually use the builder as a builder - on spring side or an class that can be simply instantiated using props and dumps out a builder/client? Something as RestClientBuilderBuilder (yeah i know the name is quite funny - not)

The problem: 
if you have a multi-cluster setup and want to provide a lib that uses something on specific props path(outside springs) to use for example repos  its basically impossible without a lot of c/p

**Comment by sothawo** [comment]
We don't have a `RestClientBuilderConfiguration` in Spring Data Elasticsearch.

**Comment by riba2101** [comment]
yeah its in spring boot, the same as `Datasource` has a builder, this could come in handy the same way?

**Comment by sothawo** [comment]
This should be an issue for Spring Boot then https://github.com/spring-projects/spring-boot/issues

**Comment by riba2101** [comment]
even providing simpler ways to create the necessary classes and reducing the boilerplate?
i think spring boot and users of this project would benefit from this?
