### ISSUE TITLE
Allow `StringQuery` or `CriteriaQuery` to be added as query into a `NativeQuery`.

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#2391]
This would allow the easy way to build the query and then add additional things that are only available in the `NativeQuery` like aggregations.

**Comment by AlexandreClose** [comment]
Hello,
I currently build complex queries that mix several filters and aggregations. Some of the filters can be built with the Criteria api; and some of them can be built only with NativeQuery (complex geoshape filter, and aggregations). 
The only way i found to mix both of them il to copy the private class CriteriaQueryProcessor, to call the createQuery(Criteria criteria) method.

Is it possible to change the visibility of the CriteraQueryProcessor; and, maybe, add a createQuery( criteriaQuery) method?

**Comment by sothawo** [comment]
This is what this issue is about, being able to add a `CriteriaQuery` (or a `StringQuery` for example) as query to a `NativeQuery`.
