### ISSUE TITLE
Spring Data Reactive Elasticsearch

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-data-elasticsearch#2395]
Hello Team,

This is my first post here. First of all, big thanks for this project.
A year back, we migrated to reactive webflux web application, and paired it with Spring Data Elasticsearch, and saw great performance increase compared to a blocking one.

One question remains, may I ask what was the design decision behind keeping everything (reactive vs blocking) within one single repo please?

The reason why I am asking is because for other data sources, there is a clean separation between the reactive vs the non reactive packages. 
I.e. Spring Data Redis // Spring Data Reactive Redis 
Spring Data MongoDB // Spring Data Reactive MongoDB
Spring Data for Apache Cassandra // Spring Data Reactive for Apache Cassandra
Spring Data Couchbase // Spring Data Reactive Couchbase

With that, at the pom level for instance, it is very easy and clear to understand the access to the data will be via a reactive repository or not.

Yet, for Elastic, one repo is enough. This is in no case a challenge on the design (to be honest, I kinda like this idea of only having one dependency to remember for blocking vs non blocking apps) but I was very curious about the design decision here.

Hope the question make sense.

Thank you!

**Comment by sothawo** [comment]
As far as I see the Spring Data projects only provide one artefact each that contains both the reactive and imperative code.

There are different artefacts for the spring-boot starters; why? I don't know, that's a decision from the spring-boot team, and not from spring-data.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
