### ISSUE TITLE
Elasticsearch 7.10 BuildFlavor "oss"

### ISSUE THREAD

**Issue by mykel33** [spring-projects/spring-data-elasticsearch#2406]
Elasticsearch 7.10 return oss build_flavor rather than "default"

RestHighLevelClient getVersionValidation validate the build_flavor of the elasticsearch 7.10
but the version 7.10 return "oss" value 

example of response:
 ```
org.apache.http.wire.wire - http-outgoing-0 << "  "name" : "m-0.5abaa1d3-e43f-4daa-ba34-dd77c91eddfb.74c378a8d33e4dd383c36a220bbe9809.bslrp32b0pfiksegjfog.databases.appdomain.cloud",[\n]"
26-12-2022 01:10:23.150 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "  "cluster_name" : "5abaa1d3-e43f-4daa-ba34-dd77c91eddfb",[\n]"
26-12-2022 01:10:23.151 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "  "cluster_uuid" : "YKwNMG3eQ2CU_7zjULolmA",[\n]"
26-12-2022 01:10:23.151 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "  "version" : {[\n]"
26-12-2022 01:10:23.151 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "number" : "7.10.2",[\n]"
26-12-2022 01:10:23.151 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "build_flavor" : "oss",[\n]"
26-12-2022 01:10:23.151 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "build_type" : "tar",[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "build_date" : "2021-01-13T00:42:12.435326Z",[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "build_snapshot" : false,[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "lucene_version" : "8.7.0",[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "minimum_wire_compatibility_version" : "6.8.0",[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "    "minimum_index_compatibility_version" : "6.0.0-beta1"[\n]"
26-12-2022 01:10:23.152 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "  },[\n]"
26-12-2022 01:10:23.153 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "  "tagline" : "You Know, for Search"[\n]"
26-12-2022 01:10:23.153 [STDOUT] DEBUG org.apache.http.wire.wire - http-outgoing-0 << "}[\n]"
```

example of the issue error:
`Caused by: org.elasticsearch.ElasticsearchException: Invalid or missing build flavor [oss]
	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2076)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1724)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1709)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
	at org.springframework.data.elasticsearch.core.DefaultIndexOperations.lambda$doExists$2(DefaultIndexOperations.java:107)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:383)
	... 37 common frames omitted`

if we can updade the elasticsearch from 7.10 to 7.12 it is ok, but if we cannot we are bloqued

solution: override all the classe RestHighLevelClient and add "oss" to the list authrorized 

can you fix this bug please

**Comment by sothawo** [comment]
This is nothing in the scope of Spring Data Elasticsearch. The `RestHighLevelClient` is a class from the Elasticsearch's libraries. This changes  were made by Elasticsearch more than 1.5 years ago. The `RestHighLevelClient` itself was deprecated in December 2021.
