### ISSUE TITLE
Add Query by Example feature

### ISSUE THREAD

**Issue by ezequielantunez** [spring-projects/spring-data-elasticsearch#2418]
Hi spring-data-elasticsearch team.

I'd like to contribute to this project implementing [Query by Example](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example) feature from Spring Data.

I found this feature extremely useful in the past. The use case is to avoid custom repositories method explosion for queries based  on nullable fields filter models.

My initial approach is to create the following implementations:
- `public class QueryByExampleElasticsearchExecutor<T> implements QueryByExampleExecutor<T>`
- `public class ReactiveQueryByExampleElasticsearchExecutor<T> implements ReactiveQueryByExampleExecutor<T>`

and use them as fragments in repository factories.

I have an initial working version based on CriteriaQuery, for simplicity, but missing of the following features:
- [ExampleMatcher.StringMatcher.REGEX](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/domain/ExampleMatcher.java#L585) which I think is not supported by Criteria API
- [findByBy with Fluent query function](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/query/QueryByExampleExecutor.java#L104) method. I would need some support here or spend more time investigating about it.

**Comment by sothawo** [comment]
Interesting topic, I never used or needed that so I never had a look at it, but it would be a nice addition.

I just had a look how Spring Data Mongodb uses this, but they have the luck that the mongo db itself supports an example query. For Spring Data Elasticsearch we'd need to build a query from the example, and I think that using a `CriteriaQuery` as you did would be the right way.

As for the regex match: You are right, this is not yet supported. This could be added either in this issue or as a separate issue to be done before that. Elasticsearch has a [regexp term query](https://www.elastic.co/guide/en/elasticsearch/reference/8.5/query-dsl-regexp-query.html) that should be used for that.

Fluent query - just had a first look at it myself - is not directly related or a prerequisite to the query by example topic, rather something that can be used for that as well. Adding this would probably be a separate issue.

One thing I noticed about the `QueryByExampleExecutor`: This returns the simple entity types, in Spring Data Elasticsearch we mostly return the `SearchHit(s)<T>`, but that should be no big problem.

If you have code which you'd like to add, you're welcome to provide this as a PR, so I can have a look at that to see how it fits into the existing codebase.

**Comment by sothawo** [comment]
Thanks again, I rarely get such such nice written contributions.
