### ISSUE TITLE
SDE 4.x, 5.x  How to use custom similarity？

### ISSUE THREAD

**Issue by wuxiansen** [spring-projects/spring-data-elasticsearch#2424]
Similarity is defined by index，now I don't know how to use it. 
Similarity now defines Enum， not String.

```json
{
  "index": {
    "similarity": {
      "my_similarity": {
        "type": "DFR",
        "basic_model": "g",
        "after_effect": "l",
        "normalization": "h2",
        "normalization.h2.c": "3.0"
      }
    }
  }
}
```

```java
public enum Similarity {
	Default("default"), BM25("BM25"), classic("classic"), Boolean("boolean");
         ...
}

// use

class Entity {

    @Field(type = FieldType.Text, similarity = Similarity.xxx)
    private String message;

}

/**
* @since 4.0
*/
Similarity similarity() default Similarity.Default;

// MappingParameters.java
if (similarity != Similarity.Default) {
	objectNode.put(FIELD_PARAM_SIMILARITY, similarity.toString());
}
```

I tried specifying the default similarity index.similarity.default.type: my_similarity in elasticsearch.yml, but that became global

Or instead of using Field annotations, use Mapping altogether.

If Similarity defines String, wouldn't it be easier to extend?

eg:
```java
class Entity {

    //     @Field(type = FieldType.Text, similarity = "BM25" or "boolean" )
    @Field(type = FieldType.Text, similarity = "my_similarity")
    private String message;

}
```

If think this suggestion is good, I'd be happy to optimize this issue for this. 🧑‍💻

**Comment by sothawo** [comment]
No, we won't change to String, because that would be a breaking change for existing users. I got a vague idea of how this can be solved, have to think about it.

**Comment by sothawo** [comment]
Seems we have to do the breaking change to a String, as we cannot have interfaces as annotation properties.

**Comment by wuxiansen** [comment]
I've tried to change similarity to an interface to reduce the impact on users. But the value of the annotation mode attribute must be a constant.

> Seems we have to do the breaking change to a String, as we cannot have interfaces as annotation properties.

I've tried to change similarity to an interface to reduce the impact on users. But the value of the annotation mode attribute must be a constant.
