### ISSUE TITLE
ElasticsearchRestTemplate End of Life Dates 

### ISSUE THREAD

**Issue by azazadev** [spring-projects/spring-data-elasticsearch#2428]
We are updating regulatory to latest spring-boot and spring-data-elasticsearch version

today we are on spring-boot 2.7.5 and spring-data-elasticsearch 4.4.5 and Elasticsearch 7.17.6

the plan is to migrate to latest spring-boot 3.0.1 and spring-data-elastic 5.0.0 and Elasticsearch 8.x

in our projects all queries implementation are based on ElasticsearchRestTemplate and RestHighLevelClient with the help of NativeSearchQueryBuilder and the plan is to migrate to ElasticsearchTemplate and use the new implementation of NativeQueryBuilder

as ElasticsearchRestTemplate is today deprecated in 4.4.5 and also deprecated in latest version 5.0.0 my question is :

What is the approximate end of life date of ElasticsearchRestTemplate ? are you plan to support this in all 5.X version ? 

we need this to define our priorities and if we should start migrations from ElasticsearchRestTemplate to ElasticsearchTemplate

Thanks

**Comment by sothawo** [comment]
It will be removed in 5.2 which according to the normal schedule will be in November 2023, but there will be no more development for this deprecated client.
