### ISSUE TITLE
InvalidDefinitionException: No serializer found for class org.springframework.data.elasticsearch.client.elc.ElasticsearchAggregations

### ISSUE THREAD

**Issue by AIRahimi** [spring-projects/spring-data-elasticsearch#2437]
ElasticsearchAggregations are not deserialized for SearchHits<?>.

**Comment by sothawo** [comment]
Serialized by what? The error _InvalidDefinitionException: No serializer found for class_  seems to come from Jackson trying to serialize this class. So this probably occurs when you send a `SearchHits` object somewhere else - this is out of scope of Spring Data Elasticsearch.

The returned Aggregations are client dependent, they were different classes in the implementation using the old `RestHighLevelClient` and in the current implementationusing the `ElasticsearchClient`. This is the reason, why in the `SearchHits` class there only is the `AggregationsContainer<?> getAggregations();` method, this returns something specific to the used client. We don't put explicit Elasticsearch classes in the API of Spring Data Elasticsearch.

In theory it might be possible to define a class hierarchy in Spring Data Elasticsearch for the different classes used in aggregations and do a mapping from the data returned by Elasticsearch to this classes. But the package `co.elastic.clients.elasticsearch._types.aggregations` from the Elasticsearch library alone contains currently 255 classes; the effort to write something like that would be pretty high. As a library we would not know which of these would really be needed.

You as a user know what aggregations you expect and so should be able convert the returned data in some internal format of your application which then can be sent somewhere else.

**Comment by AIRahimi** [comment]
Thank you for the explanation. I just thought it was in the scope since everything went well during serialization of SearchHits, but I started receiving after adding aggregations in to the mix. 

I'll close it now, thanks again.
