### ISSUE TITLE
ReactiveIndicesTemplate: Refresh not called on bound indices

### ISSUE THREAD

**Issue by ls-urs-keller** [spring-projects/spring-data-elasticsearch#2441]
https://github.com/spring-projects/spring-data-elasticsearch/blob/b75d2eb01fde1bfab0913f683f70ad617771f945/src/main/java/org/springframework/data/elasticsearch/client/elc/ReactiveIndicesTemplate.java#L156

Shouldn't this be 
```
	@Override
	public Mono<Void> refresh() {
		RefreshRequest refreshRequest = requestConverter.indicesRefreshRequest(getIndexCoordinates());
		return Mono.from(execute(reactiveOpenSearchIndicesClient -> reactiveOpenSearchIndicesClient.refresh(
				refreshRequest))).then();
	}
```

I can PR just would like to have a confirmation that this is a bug.

**Comment by sothawo** [comment]
Thank you for that finding, indeed that's a bug. Please provide a PR for the _main_ branch, I'll backport it then to the 5.0.x as well.

**Comment by ls-urs-keller** [comment]
@sothawo Thank for your quick reply, pull request added. Thank you.
