### ISSUE TITLE
Allow dynamic_template field in indicesPutMappingRequest

### ISSUE THREAD

**Issue by dmalipie** [spring-projects/spring-data-elasticsearch#2447]
When i use **ElasticsearchOperations** to create an index mapping I'm not allowed to set its **dynamic_template** part, because this is ignored by the _addPropertiesToMapping_ method in _RequestConvert_ class:

```java
private void addPropertiesToMapping(PutMappingRequest.Builder builder, Document mapping) {
	Object properties = mapping.get("properties");
	if (properties != null) {
		if (properties instanceof Map) {
			Map<String, Property> propertiesMap = new HashMap<>();
			// noinspection unchecked
			((Map<String, Object>) properties).forEach((key, value) -> {
				Property property = getProperty(value);
				propertiesMap.put(key, property);
			});
			builder.properties(propertiesMap);
		}
	}
}

```

**Comment by edovac** [comment]
Hi, any news on resolution date for this issue?

Thanks

**Comment by sothawo** [comment]
Spring Data Elasticsearch is a community driven project, there is no dedicated team anywhere working on it. I as a project lead manage / review contributions and as a maintainer add code myself. But I'm doing this in my spare time. 
So issues have to wait until either someone from the community contributes or I find the time to implement them.

**Comment by sothawo** [comment]
Just having a look at this issue. The code shown above is from the initial incomplete implementation using the new Elasticsearch client, it does not exist in this form anymore. In the current version the request is built this way:

```java
public PutMappingRequest indicesPutMappingRequest(IndexCoordinates indexCoordinates, Document mapping) {

	Assert.notNull(indexCoordinates, "indexCoordinates must not be null");
	Assert.notNull(mapping, "mapping must not be null");

	PutMappingRequest request = new PutMappingRequest.Builder() //
			.withJson(new StringReader(mapping.toJson())) //
			.index(Arrays.asList(indexCoordinates.getIndexNames())) //
			.build();

	return request;
}
```
So it is possible to add any property you like to the `mapping` socument before calling `putMapping()` with it.

So for me this is no issue anymore.

**Comment by edovac** [comment]
Hi, thanks for the update.
We checked in our integration and we can confirm that will work with us.

Thanks again.
