### ISSUE TITLE
Elastic Search compatibile headers not working

### ISSUE THREAD

**Issue by anmol8118** [spring-projects/spring-data-elasticsearch#2448]
Hi all,
I tried setting compatible headers in my existing rest high-level client, but unfortunately, I'm still getting the following error:

"java.lang.IllegalStateException: Unsupported Content-Type: application/vnd.elasticsearch+json;compatible-with=7"

Can you please help me here?

Elastic Search cluster: 8.5.3v
HLRC: 7.6.2v

**Comment by sothawo** [comment]
First, please refrain from adding this to every issue you may find that had this topic.

Provide the code how you set the header or better a runnable example that shows this error and show a complete stacktrace.

Which version of Spring Data Elasticsearch do you use? Why not upgrade to the current version that is built wit the Elasticsearch client in version 8?

This is by the way a problem between the Elasticsearch client library and the Elasticsearch server and not a problem odf Spring Data Elasticsearch.

**Comment by anmol8118** [comment]
Hi @sothawo ,
I'm sorry for my previous mistake.

Please find my code snippet below:

  RestClientBuilder builder = RestClient.builder(new HttpHost(("HOST_NAME"), 9090))
                .setPathPrefix("PATH_PREFIX")
                .setDefaultHeaders(compatibilityHeaders());
        return new RestHighLevelClient(builder);
    }

    private Header[] compatibilityHeaders() {
        return new Header[]
                {
                        new BasicHeader(HttpHeaders.ACCEPT, "application/vnd.elasticsearch+json; compatible-with=7"),
                        new BasicHeader(HttpHeaders.CONTENT_TYPE, "application/vnd.elasticsearch+json; compatible-with=7")};
    }

And, I'm using Spring-data-elasticsearch:4.0.5.RELEASE
Spring Boot: 2.3.6.RELEASE

Could you please guide me here?

I really appreciate any help you can provide.

**Comment by sothawo** [comment]
Spring Data Elasticsearch 4.0.5 was released in October 2020 and has reached end of lifecycle and support in May 2021.
The Elasticsearch client that was used at that time (7.6.2 if I see this correctly) does not accept that header, because at that time the compatibility issue that these headers address did not even exist.

You should migrate your application to current versions especially when you want to access Elasticsearch version 8.

**Comment by anmol8118** [comment]
Hi @sothawo ,
Thanks for guiding me. 

As per your advice, I've upgraded my application to the following versions:
Spring-boot: 3.0.2
Spring framework: 6.0.4
Elastic search: 8.5.3
Spring data elastic search: 5.0.1

I'm unable to create the Custom Repository in my application, getting the Error:
creating bean with name '***Repository' defined in com.***.repository.***Repository defined in @EnableElasticsearchRepositories declared on ElasticConfiguration: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exceptionerror: 

And I'm configuring the client as follows:

@Configuration
@EnableElasticsearchRepositories(basePackages = "***.repository")
public class ElasticConfiguration extends ElasticsearchConfiguration {
    
@Override
    public ClientConfiguration clientConfiguration() {
return ClientConfiguration.builder()
                .connectedTo(connectionUrl)
                .usingSsl()
                .build();
    }
}

Could you please correct me on what I'm doing here?

Thank you so much for your attention and participation.

Regards,
Anmol Arora

**Comment by sothawo** [comment]
what's the error?

**Comment by anmol8118** [comment]
Here it is:

error creating bean with name 'Repository' defined in com..repository.***Repository defined in @EnableElasticsearchRepositories declared on ElasticConfiguration: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exceptionerror
