### ISSUE TITLE
kotlin.Long not permitted for version field

### ISSUE THREAD

**Issue by sp-llminc** [spring-projects/spring-data-elasticsearch#2459]
`SimpleElasticsearchPersistentProperty` requires the \@Version property [to be a `java.lang.Long`](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/mapping/SimpleElasticsearchPersistentProperty.java#L98) and throws a `MappingException` ("Version property version must be of type Long!") for the following (Kotlin) document type:

```kotlin
@Document(dynamic = Dynamic.STRICT, createIndex = false, versionType = Document.VersionType.EXTERNAL)
data class SearchDocumentEntity (
    @Id
    var id: String,

    @Version
    var version: Long,

// ... etc ...
```

**Comment by sothawo** [comment]
Spring Data Elasticsearch expects a `java.lang.Long` object for a version property. The Kotlin compiler maps `kotlin.Long` to the Java `long` primitive type.

Two possibilities:

1. Use a nullable object
```kotlin
var version: Long?
```
This will be mapped to a nullable `java.lang.Long`.

2. Use the java class:
```kotlin
var version: java.lang.Long
```
