### ISSUE TITLE
Avoid including @Id and @Version in the document source

### ISSUE THREAD

**Issue by anton-johansson** [spring-projects/spring-data-elasticsearch#2466]
Hey! I have a document type which has an `@Id` field and a `@Version` field. When I save this, it looks like Spring Boot Elasticsearch tries to set these on the document source **in addition** to the native Elasticsearch fields. Why is this? You can find the code here:
https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/convert/MappingElasticsearchConverter.java#L1440

Feels very redundant to have these two properties on the document body as well.

Thoughts? Would it be possible to include some configuration to avoid this behavior?

**Comment by sothawo** [comment]
The possibility to not add the id to the document source was added in #2438 and is available in the latest milestone release from yesterday (5.1.0-M2).

For the version this would need to be added.

**Comment by anton-johansson** [comment]
Oh, that is great! I'll try the release whenever it's released via `spring-boot-starter-parent`. :partying_face: 

It would be awesome with a similar option for the version.
