### ISSUE TITLE
Error management on data integrity errors

### ISSUE THREAD

**Issue by anton-johansson** [spring-projects/spring-data-elasticsearch#2467]
I'm trying to do atomic updates, utilizing the `_version` (`@Version`) field. I'm trying to properly handle 409 Conflict, and I see that we get a `DataAccessResourceFailureException` that only has a message:

```
method [PUT], host [http://localhost:9200], URI [/my-index/_doc/abc123?refresh=false&version_type=external&version=3], status line [HTTP/1.1 409 Conflict]
{"error":{"root_cause":[{"type":"version_conflict_engine_exception","reason":"[abc123]: version conflict, current version [4] is higher or equal to the one provided [3]","index_uuid":"czrIO6l-Tl-A4qvlM27RyA","shard":"0","index":"my-index"}],"typ
e":"version_conflict_engine_exception","reason":"[abc123]: version conflict, current version [4] is higher or equal to the one provided [3]","index_uuid":"czrIO6l-Tl-A4qvlM27RyA","shard":"0","index":"my-index"},"status":409}
```

This is really hard to work with. Could we not extend `DataAccessResourceFailureException` (maybe `ElasticsearchResourceFailureException`?) that has more information about the failure?

```java
catch (ElasticsearchResourceFailureException e) {
    System.out.println(e.getStatusCode());
    System.out.println(e.getResponseBody());
    System.out.println(e.getError()); // <- could be a parsed Error object or a Map<String, Object>?
}
```

**Comment by sothawo** [comment]
I think it would be better to check the response for a 409 code and then either throw a `org.springframework.dao.DataIntegrityViolationException` or better a custom class that derives from that an contains the detailed error message (like "_[test-id]: version conflict, current version [1] is higher or equal to the one provided [1]"_).

**Comment by anton-johansson** [comment]
Yeah, that would probably be nice too. As long as I can check specifically for this error without having to do magic string lookups, I'll be happy. :D `DataIntegrityViolationException` doesn't necessarily feel specific enough?
