### ISSUE TITLE
Why SimpleElasticsearchMappingContext caused cycle dependencies?

### ISSUE THREAD

**Issue by Manjiz** [spring-projects/spring-data-elasticsearch#2476]
Maven: spring-boot-starter-data-elasticsearch v2.6.6

![image](https://user-images.githubusercontent.com/13447336/220539993-3258573d-9e02-49ec-9660-bbb005d319fd.png)

Source code of mappingContext:

```java
        @Bean
        @ConditionalOnMissingBean
        SimpleElasticsearchMappingContext mappingContext(ApplicationContext applicationContext, ElasticsearchCustomConversions elasticsearchCustomConversions) throws ClassNotFoundException {
            SimpleElasticsearchMappingContext mappingContext = new SimpleElasticsearchMappingContext();
            mappingContext.setInitialEntitySet((new EntityScanner(applicationContext)).scan(new Class[]{Document.class}));
            mappingContext.setSimpleTypeHolder(elasticsearchCustomConversions.getSimpleTypeHolder());
            return mappingContext;
        }
```

**Comment by sothawo** [comment]
Can you please provide an example project (preferable on Github) demonstrating this issue? Otherwise I cannot reproduce that.

**Comment by Manjiz** [comment]
@sothawo I had already solved this problem by using `@Lazy` to broke this cycle.

The reason of this problem is `ApplicationListener `. The `provider-xxx` register an ApplicationListener.
