### ISSUE TITLE
[Documentation enhancement request] https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.reactive

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-data-elasticsearch#2493]
Hello team,

Just wanted to start an enhancement request on documentation (which is well written by the way, thanks) https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.reactive

One can read:

```
5.4. Reactive Client (deprecated)

This was the first reactive implementation Spring Data Elasticsearch provided, but now is deprecated in favour of the org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient which uses the functionality offered by the new Elasticsearch client libraries.
```

With this, we find plethora of good examples online, in github and stackoverflow on how to use the deprecated version ```import org.springframework.data.elasticsearch.client.erhlc.ReactiveElasticsearchClient;``` (this is deprecated) of the client:
(one example out of many)
https://stackoverflow.com/questions/61827249/spring-data-elasticsearch-cannot-convert-from-fluxsearchhitsugestao-to-flux
(please see screenshot)

![Screenshot 2023-03-16 161307](https://user-images.githubusercontent.com/43899031/225555171-42bed7d5-e2f7-4c32-961b-a06a6f08ba12.png)

As the documentation is stating is it deprecated, the code itself suggests a non deprecated version.
```import org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient;``` (good)
```import org.springframework.data.elasticsearch.client.erhlc.ReactiveElasticsearchClient;``` (this is deprecated)

I gave it a try, but unfortunately, could not manage to build a non deprecated version successfully.

```
    @Bean
    public org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient reactiveElasticsearchClient() {
        final ClientConfiguration clientConfiguration = ClientConfiguration.builder()
                .connectedTo("localhost:9200")
                .build();
        return ReactiveRestClients.create(clientConfiguration); //conflict here
    }
```

May I ask if it is possible to provide in the official documentation, an example on how to build the org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient please?

Thank you

**Comment by sothawo** [comment]
What is missing from https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.reactiverestclient?
<img width="997" alt="grafik" src="https://user-images.githubusercontent.com/8456476/225648889-a36aa383-043c-40f4-a445-71c1f6eb0c54.png">

**Comment by patpatpat123** [comment]
Apologies @sothawo if I am not clear.

I am using ``` import org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient; ``` and ``` import org.springframework.data.elasticsearch.client.ClientConfiguration; ```

But here is what I am seeing:


![Screenshot 2023-03-16 161307](https://user-images.githubusercontent.com/43899031/225827820-ce017b71-329c-4a05-8c33-5ed179bbace9.png)

```
package com.elastic.demo.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.elasticsearch.client.ClientConfiguration;
import org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient;
import org.springframework.data.elasticsearch.client.erhlc.ReactiveRestClients;

@Configuration
public class ElasticsearchConfig {

    @Bean
    public ReactiveElasticsearchClient reactiveElasticsearchClient() {
        ClientConfiguration clientConfiguration = ClientConfiguration.builder()
                .connectedTo("myhost.com").build();

        return ReactiveRestClients.create(clientConfiguration);
    }
}

```

Is there a doc explaining ``` import org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchClient; ``` please? 

(not ReactiveElasticsearchConfiguration , not ClientConfiguration)

**Comment by sothawo** [comment]
I already provided the link to the documentation.

This documentation shows that you need to derive from `org.springframework.data.elasticsearch.client.elc.ReactiveElasticsearchConfiguration`, but in your code you derive from `org.springframework.data.elasticsearch.client.erhlc.AbstractReactiveElasticsearchConfiguration` which is deprecated and using the old deprecated client; in the code you posted your configuration derives from nothing in contrast to the screenshot.

Second, in your code example you explicitly import the deprecated class:
```
import org.springframework.data.elasticsearch.client.erhlc.ReactiveRestClients;
```
and create an instance of this using the deprecated `org.springframework.data.elasticsearch.client.erhlc.ReactiveRestClients` class to create this.

If you are using the configuration like documented, you just can have a `ReactiveElasticsearchClient` injected, that's it. That's described in the docs as well, see my screenshot I added above.

Read the docs, you just provide the configuration, there's no need to create the client in your code, just inject it where you need it.
