### ISSUE TITLE
spring-boot 2.7.9 and elasticsearch server 7.9.3

### ISSUE THREAD

**Issue by azazadev** [spring-projects/spring-data-elasticsearch#2509]
we are upgrading to spring-boot 2.7.9

when I check the maven dependency tree we have :

spring-boot : 2.7.9
spring-data-elasticsearch : 4.4.8
elasticsearch-rest-high-level-client : **7.17.9**

all customer are on elasticsearch server **7.9.3** and we are planning to migrate all to **7.17.9** but not before end of this year :(

we did test of compatibility between spring boot applications based on spring-boot 2.7.9 and elasticsearch-rest-high-level-client **7.17.9** and the elasticsearch server **7.9.3** and all GET/DELETE/UPDATE ... queries are working fine, create / delete index working fine also ... 

NOTE : we are using ElasticsearchRestTemplate for all queries

my question : can we use spring-boot 2.7.9 and elasticsearch-rest-high-level-client **7.17.9** with elasticsearch server **7.9.3** ? as according to documentation there may be incompatibility issues when communicating with a previous Elasticsearch node version ...

if this is not possible/recommended can someone suggest if possible to keep spring-boot 2.7.9 and downgrade the elasticsearch-rest-high-level-client to 7.9.3 ?

Thanks

**Comment by sothawo** [comment]
Spring Data Elasticsearch 4.4.8 is developed and tested with Elasticsearch client library 7.17.9 against Elasticsearch server 7.17.9.
It may work, but it's untested, and as I remember it was in 7.10 that changes in the protocol were made to check versions. So no guarantees. Test your code thoroughly/
