### ISSUE TITLE
Issue with .getWebClientConfigurer().apply(getMyCustomWebClient()); not taking effect

### ISSUE THREAD

**Issue by patpatpat123** [spring-projects/spring-data-elasticsearch#2511]
Hello Spring Data Elastic,

We would like to achieve something very simple, using Spring Data Elastic to interact with our Elastic cluster, but passing our custom Spring Webflux WebClient.

Our WebClient has been tested, and optimized, alongside the underlying Netty HTTP client.
Therefore, I believe it is fair to wish to pass our custom WebClient to Spring Data Elastic. We went to try:

```
@Configuration
public class ElasticConfiguration extends ReactiveElasticsearchConfiguration {

    @Override
    public ClientConfiguration clientConfiguration() {

        ClientConfiguration clientConfigurationWithCustomWebClient = ClientConfiguration.builder().connectedToLocalhost().build();
        clientConfigurationWithCustomWebClient.getWebClientConfigurer().apply(getMyCustomWebClient());
        return clientConfigurationWithCustomWebClient;
    }

    public WebClient getMyCustomWebClient() {
        return //the custom webclient
    }
```

Please note the ```clientConfigurationWithCustomWebClient.getWebClientConfigurer().apply(getMyCustomWebClient());```

Expected: Our custom Webflux WebClient has many features, such as wiretap logging, custom metrics, etc. What we expect was Spring Data Elastic to pick it up, and perform repository interaction (findById, save, etc) with our custom client.

Actual: it seems there is an issue where custom WebClient is not being taken into account, even after configuration. I.e, none of the wiretap logs, none of the metrics, none of the other custom optimization we implemented in our WebClient could be noticed

Could you please help with this issue?

Thank you

**Comment by sothawo** [comment]
Since version 5.0 Spring Data Elasticsearch does not use reactive implementations based on WebClient anymore, but uses the Java Client from Elasticsearch  for both imperative and reactive implementations.

**Comment by patpatpat123** [comment]
Thank you @sothawo for the clarificaiton.

May I understand the background for this choice (not supporting WebClient directly) please?

Technical analysis between the apache http client vs the netty Webclient, I am just going to chose couple of points from our report:

Performance: the overall speed of Netty client is superior to Apache http client (benchmark made on millions of requests, I am sure there will be some gurus on one side that will say one can always be faster than the other, but this is the result we found)

Reliability: the Netty client, since integrated natively with Micrometer, offers direct metrics and tracing out of the box. Those are required production features in most companies.

Support: Spring team actively supports Netty / WebFlux webclient over recent years. While the apache http client has less support and community involvement (I did not say no support)

Design: Spring Webflux WebClient offers native out of the box reactive features. The rest client used in elasticsearch-java library is not reactive. I had a conversation with Sylvain, even he said the client used in his library is not yet reactive. That argument is actually a good candidate enough.

Would it be possible to start an enhancement request for Spring Data Elasticsearch to offer the choice between elastic-java http client and spring webflux webclient please?

**Comment by sothawo** [comment]
We had the WebClient for the initial implementation of reactive support back some years ago. This client needed a lot of code copied and adapted from the Elasticsearch core libraries for request and response mapping. After the licensing change in Elasticsearch 7.10  it was no longer possible to copy and adapt the code from Elasticsearch's core libraries. This license change as well was what drove Elasticsearch to develop the new Java client which does not rely on the core libraries and is Apache 2 licensed.

So from Spring Data Elasticsearch 5.0 on we stick to the official Java client libraries that are appropriate licensed and are using the underlying asycnc methods from the Elasticsearch Java client to implement reactive.

You could implement your own implementation of a client, but that means reimplementing the request/response mapping for all the different endpoints and classes from the Elasticsearch Java client, it might be possible to copy/adapt this from the Transport class. But in addition it would be necessary to reimplement the functionality that the low level Elasticsearch RestClient provides (which is used by the Elasticsearch-Java client, and was used by the old RestHighLevelClient as well) in a reactive way.

This is nothing where I see the need to have it done actually. Feel free to create an implementation that can be plugged in and provide it as a contribution.

**Comment by patpatpat123** [comment]
Thank you for the explanation
