### ISSUE TITLE
elasticsearchOperations doesn't consider 'with Ids' from NativeQuery 

### ISSUE THREAD

**Issue by nelyodev** [spring-projects/spring-data-elasticsearch#2514]
** Describe the bug**
When using the native query builder (org.springframework.data.elasticsearch.client.elc.NativeQuery)
withIds() method

elasticsearchOperations.search (org.springframework.data.elasticsearch.core.SearchOperations) should use this property. But it is skipped entirely.

** Environment **
org.springframework.data:spring-data-elasticsearch:5.0.4
co.elastic.clients:elasticsearch-java:8.5.3
org.springframework.boot:spring-boot:3.0.5

** To Reproduce **
1.  query = NativeQuery.builder().withIds(someIds).build()
2. elasticsearchOperations.search(query, CustomDocument.class);
3. logging.level.org.springframework.data.elasticsearch.client.WIRE: TRACE
4. read log

** Expected  behavior **
the query contains the 'query' field

** Workaround **
query = NativeQuery.builder().withQuery(q -> q.ids(i -> i.values(ids)))
works as expected

**Comment by sothawo** [comment]
* A `NativeQuery` never creates a query on itself, it uses the query set in the `NativeQueryBuilder.setQuery()` method.
* the `withIds()` method  on a query builder sets a list of ids for the `Query`. If you look at the documentation for `BaseQuery.setIds()` you see that these ids are only used for mget calls using the query and not for other calls. This information was missing on the `withIds()` method in the builder, I updated that.

So the correct way to create a ids query is what you have as a workaround.

Or you use the `ElasticsearchOperations#idsQuery()` method to create a query - which in [the current implementation](https://github.com/spring-projects/spring-data-elasticsearch/blob/5.0.4/src/main/java/org/springframework/data/elasticsearch/client/elc/ElasticsearchTemplate.java#L551-L554) does exactly that:
```java
public Query idsQuery(List<String> ids) {
  return NativeQuery.builder().withQuery(qb -> qb.ids(iq -> iq.values(ids))).build();
}
```
