### ISSUE TITLE
why my analyzer setting failed?

### ISSUE THREAD

**Issue by CaiyingH** [spring-projects/spring-data-elasticsearch#2529]
spring-data-elasticsearch 2.7.5
code of analyzer setting as follow:
![image](https://user-images.githubusercontent.com/58588363/232207309-f4d17dd3-8af2-4a0f-b510-7060d53f6dcc.png)
when the index build successfully, the analyzer don't exist in the mapping
ElasticsearchRestTemplate is the create Index util.
what I can do to make the analyzer set succefully?

**Comment by sothawo** [comment]
What is failing? What is not working?

There was no version 2.7.5 of Spring Data Elasticsearch, I suppose you mean Spring Boot 2.7.5, that would mean you are using Spring Data Elasticsearch 4.4.5?

Please don't paste images in issues but code snippets.

I tested your `@Field` setup and Spring Data Elasticsearch is writing the correct mapping for the document.

So check:

* the analyzer is defined (see https://www.elastic.co/guide/en/elasticsearch/reference/8.7/analysis-analyzers.html and and https://www.elastic.co/guide/en/elasticsearch/reference/8.7/analysis-custom-analyzer.html)
* You are using Spring Data repositories and the index does not yet exist on application startup
* You are not using repositories, then you need to call `IndexOperations.putMapping()` to have the mapping wrigtten

**Comment by CaiyingH** [comment]
Thank you for your answer, the issue has been resolved.

**Comment by CaiyingH** [comment]
https://github.com/spring-projects/spring-data-elasticsearch/issues/2529#issuecomment-1510454588
Thank you! the issue has been resolved.
