### ISSUE TITLE
Does it now support es8.7.3 in version 5.0.5?

### ISSUE THREAD

**Issue by Greenjiao** [spring-projects/spring-data-elasticsearch#2533]
Thank you very much for the developer's efforts,
I have a problem using es8.7.3 in my project, 
I want to check whether it is caused by version conflicts, 
I see that spring-data's documentation only mentions version 5.0.1 support for version 8.5.3, 
but did not see the version of 5.0.5 version corresponding to the instructions, 
now the latest version comparison table should go where to see,thanks

**Comment by Greenjiao** [comment]
I further tested my project , and version 5.0.5 supports es8.7.3, sorry to bother you

**Comment by sothawo** [comment]
The latest version of Elasticsearch I know of is 8.7.0

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/8456476/232705551-9da7db26-3c87-4887-976f-6a68d02f3135.png">

Spring Data Elasticsearch 5.0.x was released with the 8.5.x branch of Elasticsearch and will only get  patch level updates. We are not changing dependencies for released versions in major or minor version updates, only on patch level updates.

**Comment by Greenjiao** [comment]
> The latest version of Elasticsearch I know of is 8.7.0
> 
> <img alt="image" width="1272" src="https://user-images.githubusercontent.com/8456476/232705551-9da7db26-3c87-4887-976f-6a68d02f3135.png">
> 
> Spring Data Elasticsearch 5.0.x was released with the 8.5.x branch of Elasticsearch and will only get patch level updates. We are not changing dependencies for released versions in major or minor version updates, only on patch level updates.

Yes, I typed the wrong version，thanks
