### ISSUE TITLE
Pageable should allow size = 0 to get only aggregates

### ISSUE THREAD

**Issue by nhajratw** [spring-projects/spring-data-elasticsearch#2538]
we would like to build a query to get back *only* the aggregates:
```json
{
  "aggregations" : {
    "some_ids" : {
      "terms" : {
        "field" : "some_ids"
      }
    }
  },
  "from" : 0,
  "query" : {
    "multi_match" : {
      "fields" : [ "title", "description" ],
      "query" : "corvette"
    }
  },
  "size" : 0,
  "sort" : [ ],
  "track_scores" : false,
  "version" : true
}
```

However, when setting up the query:

```kotlin
val searchQuery = NativeQueryBuilder()
    .withQuery(
        QueryBuilders.multiMatch()
            .query(lotSearchTerm)
            .fields("title", "description")
            .build()._toQuery()
    )
    .withAggregation(
        "some_ids",
        Aggregation(TermsAggregation.Builder().field("some_ids").build())
    )
    .withPageable(Pageable.ofSize(0))
    .build()
```

`Pageable` is required to have size > 0 . As a result, I end up getting back at least 1 document result, when I want none. Setting size = 0 in a raw query via curl works fine.

**Comment by sothawo** [comment]
The purpose of `Pageable` is to split the returned entities into several pages/chunks, not for setting or limiting the number of returned data. For this, you need to use the `withMaxResults(Integer maxResults)` method of the query builders.

**Comment by nhajratw** [comment]
@sothawo ah - thank you for that insight. Worked like a charm.
