### ISSUE TITLE
Connect with Elasticsearch 8 with https enabled

### ISSUE THREAD

**Issue by hafza7869** [spring-projects/spring-data-elasticsearch#2539]
Can you please guide how to connect with elasticsearch with https enabled. As with elasticsearch starting with version 8 autoconfigurations automatically enable the security. After lots of research on internet and documentation I am unable to find any soluiton about how to connect spring boot - spring data elasticsearch with elasticsearch version 8.7 with https enabled. Any guidance will be appreciated.
Regards,
Hafza

**Comment by sothawo** [comment]
The Elasticsearch documentation shows 2 different ways to create a `SSLContext` that can be used to access the cluster (this is nothing that can be done from Spring Data Elasticsearch):

1. https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/connecting.html#_verifying_https_with_a_certificate_fingerprint
2. https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/connecting.html#_verifying_https_with_a_ca_certificate


This `SSLContext` can then be passed to the [Spring Data Elasticsearch configuration](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.configuration) - there's an overload method `usingSsl(SSLContext)`.

**Comment by hafza7869** [comment]
Well thanks my savior, after trying to resolve just this issue for two three days, I am able to connect elasticsearch with spring project

**Comment by sothawo** [comment]
I'm having a look if or how best to add this to the configuration class, maybe something like `usingSsl(String certificateFingerprint)` which then will be used when building an Elasticsearch 8 client.

**Comment by sothawo** [comment]
Reopening this issue to reference it from my pull request adding this to the configuration

**Comment by jesussaad** [comment]
> Well thanks my savior, after trying to resolve just this issue for two three days, I am able to connect elasticsearch with spring project

Could you please share the solution?
