### ISSUE TITLE
DeleteByQuery implementation is confusing

### ISSUE THREAD

**Issue by blacar** [spring-projects/spring-data-elasticsearch#2544]
In Elastic REST API the operations `_update_by_query` and `_delete_by_query` are very similar: 
They both accept a query, they have similar properties and similar behavior.

However, the implementation in spring-data-elasticsearch is nothing like that:

`_update_by_query` on spring-data-elasticsearch is model by
`org.springframework.data.elasticsearch.core.query.UpdateQuery`

e.g. something like this:

```
    final BoolQueryBuilder boolQuery = QueryBuilders.boolQuery()
      .filter(QueryBuilders.rangeQuery(STATUS_SEARCH_FIELD).lt(EsMessage.STATUS))
    final NativeSearchQuery nsq = new NativeSearchQuery(boolQuery);
    final UpdateQuery updateQuery = UpdateQuery.builder(nsq)
      .withScriptType(ScriptType.INLINE)
      .withScript(UPDATE_SCRIPT)
      .withParams(UPDATE_PARAMS)
      .build();
    final ByQueryResponse response = esRestTemplate.updateByQuery(
      updateQuery, IndexCoordinates.of(INDEX_ALIAS)
    );
```

Now on `_delete_by_query` EVERYTHING is different (!!)
- There is no UpdateQuery object
- There is no updateByQuery method on ElasticsearchRestTemplate

Is there any reason for this? ... it's annoying.
What would be the right way to execute a `_delete_by_query` operation?
Is that I am doing something wrong or unexpected?

I would suggest making these two operations more similar since they are similar on the Elasticsearch API.

**Comment by sothawo** [comment]
> There is no UpdateQuery object

Why should there be an  `UpdateQuery` object in a delete request? In order to delete by query, we just need a query and the index to use, `ElasticsearchOperations` has these methods:
```
ByQueryResponse delete(Query query, IndexCoordinates index);
ByQueryResponse delete(Query query, Class<?> clazz, IndexCoordinates index);
```
The second method is needed to do proper field name mapping when `CriteriaQuery` is used.

For an update, much more information is needed than just the query, Therefore there is an `UpdateQuery` object that contains the `Query` and this additional information.

> There is no updateByQuery method on ElasticsearchRestTemplate

```
ByQueryResponse updateByQuery(UpdateQuery updateQuery, IndexCoordinates index);
```
was introduced in April 2021 with Spring Data Elasticsearch version 4.2 (which itself is out of support for one year now).

**Comment by blacar** [comment]
I agree that a update_by_query much more information is needed.

I have never said that a `UpdateQuery` object should be required for a delete operation
I am just pointing out that the lack of symmetry between these two operations makes the library more confusing IMO. 

| ByQueryResponse updateByQuery(UpdateQuery updateQuery, IndexCoordinates index);

Sorry about this mistake in my initial post. My intention was to point out that there IS a `updateByQuery` method on ElasticsearchRestTemplate but there is NOT a `deleteByQuery`. The name for the delete operation is "delete" and the inputs are different. Again this lack of symmetry makes things more difficult to understand IMO.


In order to make those two operations
