### ISSUE TITLE
[illegal_argument_exception] cannot set [search_type] when using [knn] search

### ISSUE THREAD

**Issue by invokerbyxv** [spring-projects/spring-data-elasticsearch#2569]
dependencies：
org.springframework.boot:spring-boot-starter-data-elasticsearch:3.1.0
org.springframework.boot;spring-boot-starter:3.1.0

search code：

`public List<RetrieverDoc> queryByEmbedding(String queryString, int topK) throws Exception {`
    `    float[] predict = textFeatureExtractionService.predict(queryString, true);`
    `    List<Float> vector = new ArrayList<>();`
    `    for (float v : predict) {`
    `        vector.add(v);`
    `    }`
    `    KnnQuery.Builder knnBuilder = new KnnQuery.Builder();`
    `    knnBuilder.field("embedding");`
    `    knnBuilder.queryVector(vector);`
    `    knnBuilder.numCandidates(topK);`
    `    knnBuilder.k(topK);`
    `    NativeQuery nativeQuery = NativeQuery.builder()`
    `            .withKnnQuery(knnBuilder.build())`
    `            .build();`
    `    SearchHits<RetrieverDoc> search = elasticsearchOperations.search(nativeQuery, RetrieverDoc.class);`
    `    List<RetrieverDoc> result = new ArrayList<>();`
    `    for (SearchHit<RetrieverDoc> retrieverDocSearchHit : search) {`
    `        RetrieverDoc content = retrieverDocSearchHit.getContent();`
    `        content.setScore(retrieverDocSearchHit.getScore());`
    `        result.add(content);`
    `    }`
    `    return result;`
    `}`

exception ：

`[es/search] failed: [illegal_argument_exception] cannot set [search_type] when using [knn] search, since the search type is determined automatically`
`org.springframework.data.elasticsearch.UncategorizedElasticsearchException: [es/search] failed: [illegal_argument_exception] cannot set [search_type] when using [knn] search, since the search type is determined automatically`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:102)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchExceptionTranslator.translateException(ElasticsearchExceptionTranslator.java:63)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.execute(ElasticsearchTemplate.java:625)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.doSearch(ElasticsearchTemplate.java:341)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.search(ElasticsearchTemplate.java:334)`
`	at app//org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:492)`
`	at app//com.longrise.nlp.service.ElasticsearchService.queryByEmbedding(ElasticsearchService.java:64)`
`	at app//com.longrise.nlp.NlpApplicationTests.testQueryDoc(NlpApplicationTests.java:52)`
`	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)`
`	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)`
`	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)`
`	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)`
`	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)`
`	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)`
`	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)`
`	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)`
`	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)`
`	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)`
`	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)`
`	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)`
`	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)`
`	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)`
`	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)`
`	at app//org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)`
`	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)`
`	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)`
`	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)`
`	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)`
`	at java.base@17.0.7/java.util.ArrayList.forEach(ArrayList.java:1511)`
`	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)`
`	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)`
`	at java.base@17.0.7/java.util.ArrayList.forEach(ArrayList.java:1511)`
`	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)`
`	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)`
`	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)`
`	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)`
`	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)`
`	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)`
`	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)`
`	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)`
`	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)`
`	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)`
`	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)`
`	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)`
`	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)`
`	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)`
`	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)`
`	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)`
`	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)`
`	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)`
`	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)`
`	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)`
`	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)`
`	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)`
`	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)`
`	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)`
`	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)`
`	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)`
`	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)`
`	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)`
`	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)`
`	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)`
`	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)`
`	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)`
`	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)`
`	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)`
`	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)`
`	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`
`Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [illegal_argument_exception] cannot set [search_type] when using [knn] search, since the search type is determined automatically`
`	at app//co.elastic.clients.transport.rest_client.RestClientTransport.getHighLevelResponse(RestClientTransport.java:334)`
`	at app//co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:154)`
`	at app//co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1882)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.lambda$doSearch$14(ElasticsearchTemplate.java:341)`
`	at app//org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate.execute(ElasticsearchTemplate.java:623)`
`	... 90 more`

**Comment by sothawo** [comment]
As a first workaround you can call `withSearchType(null)`  on the `NativeQueryBuilder`, although that parameter is not marked as `@Nullable`.

I will 
* make this value nullable
* set it to null when a knnQuery is set in the builder
