### ISSUE TITLE
spring-data-elasticsearch breaks opensearch client with private field

### ISSUE THREAD

**Issue by ptourneur** [spring-projects/spring-data-elasticsearch#2574]
Hello,

I have just updated my project to spring-boot 3.1 which brings spring-data 2023.0 which brings spring-data-elasticsearch:5.1.0. 
In this [PR](https://github.com/spring-projects/spring-data-elasticsearch/pull/2410) fields of BaseQueryBuilder have been changed from protected to private and it breaks [NativeSearchQueryBuilder](https://github.com/opensearch-project/spring-data-opensearch/blob/main/spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/NativeSearchQueryBuilder.java) from opensearch-project which extends it because it tries to access indicesOptions.

This is my first issue on an opensource project so maybe I'm wrong or it's opensearch-project which should adapt but for me this fields of BaseQueryBuilder should stay protected.

**Comment by sothawo** [comment]
When I look at https://github.com/opensearch-project/spring-data-opensearch#about-opensearch-versions-and-clients, the compatible version of Spring Data Elasticsearch is 5.0. So spring-data-opensearch would need to bed adapted for the new version and this change.

Every implementation of ` Query` should extend `BaseQuery` and have a builder that extends `BaseQueryBuilder`. It then should have a constructor taking it own builder and pass that on to the super constructor where the fields from the `BaseQueryBuilder` are set on the `BaseQuery` properties. I do not see the need to make this builder properties protected. A derived builder has the `with...()` methods to set these and there are set on the query in the base constructor then.
