### ISSUE TITLE
Configuration classes are not public

### ISSUE THREAD

**Issue by noam-shoef** [spring-projects/spring-data-elasticsearch#2578]
I was trying to turn off the sniffer functionality but found it impossible.
I was trying to extend the configuration or import only those I wanted but for some reason OpenSearchRestClientConfigurations is not public which make it difficult/impossible to extend or even import if you want to use only some of the configurations.

One of the great aspect of spring is it's extensibility so please make this classes public so that it would be easy to extend.

**Comment by sothawo** [comment]
There is no class `OpenSearchRestClientConfigurations` in Spring Data Elasticsearch. You probably want to address this issue in the [OpenSearch spring data project](https://github.com/opensearch-project/spring-data-opensearch/issues)

**Comment by noam-shoef** [comment]
You are very correct, I open the spring project to compare and end up opening the issue here.
Apologies for wasting your time.
