### ISSUE TITLE
Stored @Document field, but exclude it via Spring Boot REST API

### ISSUE THREAD

**Issue by anton-johansson** [spring-projects/spring-data-elasticsearch#2591]
Is it possible to have a field on my `@Document` class that is saved properly in Elasticsearch, but excluded via the regular Spring Boot REST API?

I would love to avoid re-mapping the data to another class before sending it out from the REST API. :smiley: 

I've tried the regular ones, like `@JsonIgnore` and such, but it seems it's excluded when saving to Elasticsearch as well (which kind of makes sense, since both use JSON).

Does anyone have any good suggestions? Is there some hidden Spring Boot annotation specifically for the REST API that I can use, or do I need to create some kind of custom mapper for the REST API that ignores those specific fields?

**Comment by anton-johansson** [comment]
Ok, I found a solution as soon as I wrote this, of course...

I'm now utilizing `@JsonView` for this.

**Comment by sothawo** [comment]
> I've tried the regular ones, like @JsonIgnore and such, but it seems it's excluded when saving to Elasticsearch as well 

Spring Data Elasticsearch does not make use of jackson annotations and totally ignores them (since Spring Data Elasticsearch version 4.0)

**Comment by anton-johansson** [comment]
> > I've tried the regular ones, like `@JsonIgnore` and such, but it seems it's excluded when saving to Elasticsearch as well
> 
> Spring Data Elasticsearch does not make use of jackson annotations and totally ignores them (since Spring Data Elasticsearch version 4.0)

Hmm, odd... But yeah, I see that in the documentation now. Also, `@JsonView` works fine when I want to reduce what is leaving my service via the API. But I have a case where I want to have a value transform into different outputs depending on if it's via API or if it's to Elasticsearch. For example:

```java
private @Field(type = Integer) Integer myValue;

@JsonProperty("myValue")
@JsonView(Views.Internal.class)
public int getMyValueInternally()
{
    return defaultIfNull(myValue, -1);
}

@JsonProperty("myValue")
@JsonView(Views.External.class)
public int getMyValueExternally()
{
    return myValue;
}
```

In other words, I want to store `-1` in Elasticsearch (it makes it easier to perform filters rather than `null`), but I want to expose `null` via the API.

Do you know how I can achieve this with the "newer" (4.0+) management in Spring Boot Elasticsearch?

**Comment by anton-johansson** [comment]
Ok, this worked pretty well for me, so I'll stick with this:

```java
    private int myValue;

    @JsonProperty("myValue")
    public Integer getMyValueExternally()
    {
        return myValue < 1 ? null : myValue;
    }

    @Field(name = "myValue", type = Integer)
    public int getMyValue()
    {
        return myValue;
    }

    public void setMyValue(int myValue)
    {
        this.myValue = myValue;
    }
```
