### ISSUE TITLE
Set alias for an index with annotation upon creation.

### ISSUE THREAD

**Issue by AIRahimi** [spring-projects/spring-data-elasticsearch#2599]
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html 

The request body for index creation takes a mapping object, a setting object and an alias object. Today we can define the mapping and setting by annotation upon index creation.

It would be nice to be able to do this for alias as well. 

@Alias annotation to define aliases when creating index.

**Comment by sothawo** [comment]
That would be possible. 

How would you define the attributes in the `@Alias` annotation that are possible, especially the `filter`? One possibility I see here would be to set this as a String property of the annotation and then pass this in wrapped in a wrapper string.

**Comment by AIRahimi** [comment]
I am on a 3 weeks vacation and have not been able to look any closer at it, but yes that could be a good solution.
