### ISSUE TITLE
Feature Request: Support for new aggregation framework

### ISSUE THREAD

**Issue by pmanvi** [spring-projects/spring-data-elasticsearch#26]
Is there any plan to support new aggregation framework from elastic search as part of spring data.Apparently the existing facet framework is getting deprecated in favor of new framework.

https://github.com/elasticsearch/elasticsearch/issues/3300 - Looks promising.

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

Aggregations are supported with `NativeSearchQuery` and returned in the `SearchHits` object.
