### ISSUE TITLE
Unable to access scrollId

### ISSUE THREAD

**Issue by StijnVdd** [spring-projects/spring-data-elasticsearch#2617]
Hi,

I'm using Spring boot 2.7.13 which includes version 4.4.13 of spring-data-elasticsearch.

The docs explain how to access the scrollId while implmenting like documented it became clear the method searchScrollStart has protected access on the AbstractElasticsearchTemplate.

It looks like it is no longer possible to access the scrollId or am I missing something?
Can someone guide me in the correct dirrection on how to access the scrollId?

Thanks

**Comment by sothawo** [comment]
The comments in the code mark these as 

> internal use only, not for public API

That was changed back in December 2020. Apparently the documentation was not adapted.

 But the method in the `ElasticsearchRestTemplate` is public, so you can do
```java
var searchScrollHits = ((ElasticsearchRestTemplate) operations).searchScrollStart(50, Query.findAll(), Foo.class, IndexCoordinates.of("foo"));
var scrollId = searchScrollHits.getScrollId();
```

It was changed back to public in version 5.0
