### ISSUE TITLE
ElasticsearchRestTemplate's updateByQuery API does not worked

### ISSUE THREAD

**Issue by ilwyiworld** [spring-projects/spring-data-elasticsearch#2620]
Here is a "_update_by_query" request:

<img width="849" alt="query" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/1a98443f-b1ef-47c1-a568-f22648b79fcf">

When I use Postman or other tool to send request, it does worked correct, update 1 doc successfully, but when i use "updateByQuery" API of _ElasticsearchRestTemplate_, it does not work, the response show some error such as "**Elasticsearch exception [type=version_conflict_engine_exception, reason=[6g3G04gBubNcp_z6mdqn]: version conflict, required seqNo [123433034], primary term [3]. current document has seqNo [217531583] and primary term [4]]**":

<img width="1743" alt="error" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/0fbc5ac7-cf87-42b3-aac6-45f424f39d91">

In an odd way,when I use "updateByQuery" API of _RestHighLevelClient_,it does worked correct again:
<img width="1792" alt="success" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/08a65ac9-d750-4878-a192-fc19498be763">

**Comment by ilwyiworld** [comment]
version: 4.2.5

**Comment by sothawo** [comment]
Please provide a compilable and runnable sample project that illlustrates this issue.

**Comment by ilwyiworld** [comment]
In this repo:[https://github.com/ilwyiworld/demo/tree/main](url)

I test just now,it does not worked again,but not "not update",it update all data,not Filtered:

<img width="1543" alt="1" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/abc42640-9c07-4785-93fb-2772afe13ae3">

<img width="1530" alt="2" src="https://github.com/spring-projects/spring-data-elasticsearch/assets/7789175/5f5e3d94-d4e5-4fd7-9740-03c03a0b0347">

**Comment by sothawo** [comment]
You are using an outdated version of Spring Data Elasticsearch, 4.2.5 is out of maintenance since April 2022.

As for the different result in your two tests: When the `RestHighLevelClient.updateByQuery` is used, the following is sent to Elasticsearch as body of the request:
```
{"script":{"source":"ctx._source['createTime'] = ctx._source['operationTime'];ctx._source['operationTime']=1","lang":"painless"},"size":1000,"query":{"bool":{"must":[{"ids":{"values":["53IUU4kBGi67gbSue89K"],"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}}}
```
So the `RestHighLevelClient` sends the filter as a normal query.

In order for Spring Data Elasticsearch to do this, you need to define the query as query and not as filter:
```java
NativeSearchQueryBuilder queryBuilder = new NativeSearchQueryBuilder();
BoolQueryBuilder filter = QueryBuilders.boolQuery();
filter.must(QueryBuilders.idsQuery().addIds("53IUU4kBGi67gbSue89K"));

queryBuilder.withQuery(filter);   // <== withQuery() instead of withFilter()

String script = "ctx._source['createTime'] = ctx._source['operationTime'];ctx._source['operationTime']=0";
UpdateQuery updateQuery = UpdateQuery.builder(queryBuilder.build()).withScriptType(ScriptType.INLINE).withScript(script).build();
// use elasticsearchRestTemplate
ByQueryResponse templateResponse = elasticsearchRestTemplate.updateByQuery(updateQuery, elasticsearchRestTemplate.getIndexCoordinatesFor(UserOperationEntity.class));
System.out.println();
```
As for the error you first posted: version conflict means, that some other process updated the entities defined by your query while the update was running.

**Comment by ilwyiworld** [comment]
tks,I define the query as query in **ElasticsearchRestTemplate**,it update correct.

> As for the error you first posted: version conflict means, that some other process updated the entities defined by your query while the update was running.

In my first test, I tried many times when I made certain that no other process updated the entities,it all not work, maybe it solved again when using **query** instead of **filter**.

I need test more times to verify this solution.
