### ISSUE TITLE
Add support for highlight queries in highlighting

### ISSUE THREAD

**Issue by rportab** [spring-projects/spring-data-elasticsearch#2636]
### Problem
I want to replace ElasticSearchRestTemplate for ElasticSearchTemplate in order to get rid of deprecated RestHighLevelClient.

There's a use case where a highlight query is needed.
Elasticsearch allows to specify a highlight query as explained in [Elasticseach documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#specify-highlight-query
)
### Version
Spring Data Elasticsearch 4.4.5

### Issue
`NativeSearchQueryBuilder` allowed using it like this:
`new NativeSearchQueryBuilder().withHighlightBuilder(new HighlightBuilder().highlightQuery(_here_comes_the_query_));`

But `NativeQueryBuilder` does not allow it, as `withHighlight` method from `BaseQueryBuilder` accepts a `Highlight` and a class instead of a `HighlightBuilder`

Is there something I didn't see or is the possibility to add a highlight query really missing?

Please note Elasticsearch provides a `Hightlight.Builder` class that could be used as a replacement for `HighlightBuilder`

**Comment by sothawo** [comment]
We provide our own highlight definition on the base query in order to be able to have hightlighting not only for a native query, but for other query implementations as well.

What functionality or definition possibility is missing in this implementation that you need to use the native variant? It might make sense to add this to the highlight implementation of Spring Data Elasticsearch to have it generally available.

**Comment by rportab** [comment]
The issue from my point of view is that the highlighting provided in the base query does not fulfill all possible use cases, in particular it does not address the use case of providing a highlight query.

Let's illustrate with an example:
```
new NativeSearchQueryBuilder().withHighlightBuilder(new HighlightBuilder()
                .highlightQuery(QueryBuilders.boolQuery()
                        .should(QueryBuilders.matchQuery("field 1", "value 1"))
                        .should(QueryBuilders.matchQuery("field 2", "value 2"))));
```

If I'm not wrong this code would search for `value 1` in `field 1` and `value 2` in `field 2` and highlight them.

The corresponding Elasticsearch query would be:
```
{
  "highlight_query" : {
    "bool" : {
      "should" : [
        {
          "match" : {
            "field 1" : {
              "query" : "value 1",
              "operator" : "OR",
              "prefix_length" : 0,
              "max_expansions" : 50,
              "fuzzy_transpositions" : true,
              "lenient" : false,
              "zero_terms_query" : "NONE",
              "auto_generate_synonyms_phrase_query" : true,
              "boost" : 1.0
            }
          }
        },
        {
          "match" : {
            "field 2" : {
              "query" : "value 2",
              "operator" : "OR",
              "prefix_length" : 0,
              "max_expansions" : 50,
              "fuzzy_transpositions" : true,
              "lenient" : false,
              "zero_terms_query" : "NONE",
              "auto_generate_synonyms_phrase_query" : true,
              "boost" : 1.0
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  }
}

```

I understand `NativeQueryBuilder` is to replace `NativeSearchQueryBuilder`, but the highlight definition in the base query, if I'm not wrong, doesn't allow to specify the values to search for, just the fields.

**Comment by sothawo** [comment]
So the correct thing to do is to add the support for the highlight_query to Spring Data Elasticsearch's `org.springframework.data.elasticsearch.core.query.highlight.Highlight` class. This will enable the use of this not only in `NativeQuery`, but in other `Query` implementations as well.

**Comment by edovac** [comment]
Hi, any news on resolution date for this issue?

Thanks

**Comment by sothawo** [comment]
Spring Data Elasticsearch is a community driven project, there is no dedicated team anywhere working on it. I as a project lead manage / review contributions and as a maintainer add code myself. But I'm doing this in my spare time. 
So issues have to wait until either someone from the community contributes or I find the time to implement them.
