### ISSUE TITLE
No way to ignore unavailable indices after upgrade from 4.x

### ISSUE THREAD

**Issue by virtual-machinist** [spring-projects/spring-data-elasticsearch#2639]
Since the new API doesn't support the old indices options, I have no practical way to tell the server to ignore a missing index when doing a search in multiple indices. So when I do a search with an index missing, I get an error instead of no results for that particular index (a totally acceptable service degradation).

However `co.elastic.clients.elasticsearch.core.SearchRequest.Builder` _does_ allow setting `ignoreUnavailable` and it works for both older (7.17.x) and newer (8.8.x) ES servers I tested it on when setting the option via debugger.

Is there a way to expose this option somewhere if not in `BaseQueryBuilder` then at least `NativeQueryBuilder` I use in conjunction with `ElasticsearchTemplate`? Or some workaround other than preemptively fetching and caching the available indices.

**Comment by sothawo** [comment]
`Query` can have an `IndicesOptions` property. The Elasticsearch client did not have the possibility to add this when the first integration was done, so this query property was skipped in building the request. Even now it seems that not all of the previously available values are supported, but I'll add whatever can be done now. This includes `ignoreUnavailable`.  I created #2641 for this issue.
