### ISSUE TITLE
Why does ElasticsearchRestTemplate with Aggregations return a response value without an aggregation function

### ISSUE THREAD

**Issue by wangyandong1994** [spring-projects/spring-data-elasticsearch#2646]
version：jdk11、gradle6.8.2、elasticsearch7.17.6(need Ik word splitter)、spring data elasticsearch4.4.5、springboot2.7.5

`@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
@Accessors(chain = true)
@Document(indexName = "company_index_test")
@Setting(shards = 1, replicas = 0)
public class CompanyPo implements Serializable {
    static final long serialVersionUID = -7852649991589478518L;

    /**
     * 企业id
     */
    @Id
    Integer id;

    /**
     * 企业名称
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word")
    String companyName;

    @Field(type = FieldType.Keyword)
    String companyNameKeyword;

    @Field(type = FieldType.Keyword)
    String companyOrgCode;

}
`
code:
`@Test
    void testGroup4(){
        TermsAggregationBuilder aggregationBuilder = 
        AggregationBuilders.terms("group_by_companyOrgCode").field("companyOrgCode").size(10);
        NativeSearchQuery query = new NativeSearchQueryBuilder()
                .withAggregations(aggregationBuilder).build();
        query.setMaxResults(0);
        System.out.println("===dsl:" + JSON.toJSONString(query.getAggregations().toString()));
        SearchHits<CompanyPo> searchHits = elasticsearchRestTemplate.search(query, CompanyPo.class);
        System.out.println("---结果：" + JSON.toJSONString(searchHits));
    }`

code response:
`===dsl:"[{\"group_by_companyOrgCode\":{\"terms\":{\"field\":\"companyOrgCode\",\"size\":10,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}]"

---结果：{"aggregations":{},"empty":false,"maxScore":1.0,"searchHits":[{"content":{"address":"地址1","cityId":1,"companyName":"wyd企业心","companyNameKeyword":"2323232","companyOrgCode":"1111111111111","createTime":"2023-07-23 13:10:13","disId":1,"id":1,"provinceId":1},"highlightFields":{},"id":"1","index":"company_index_test","innerHits":{},"matchedQueries":[],"score":1.0,"sortValues":[]},{"content":{"address":"地址1","cityId":1,"companyName":"wyd企业心","companyOrgCode":"1111111111111","createTime":"2023-07-23 13:10:13","disId":1,"id":2,"provinceId":1},"highlightFields":{},"id":"2","index":"company_index_test","innerHits":{},"matchedQueries":[],"score":1.0,"sortValues":[]},{"content":{"address":"地址3","cityId":2,"companyName":"欣欣企业2222wyd222","companyOrgCode":"欣欣企业2222wyd222","createTime":"2023-07-23 13:10:13","disId":2,"id":3,"provinceId":2},"highlightFields":{},"id":"3","index":"company_index_test","innerHits":{},"matchedQueries":[],"score":1.0,"sortValues":[]},{"content":{"address":"地址3","cityId":2,"companyName":"心欣欣企业2222Wyd222","companyOrgCode":"心欣欣企业2222Wyd222","createTime":"2023-07-23 13:10:13","disId":2,"id":4,"provinceId":2},"highlightFields":{},"id":"4","index":"company_index_test","innerHits":{},"matchedQueries":[],"score":1.0,"sortValues":[]}],"totalHits":4,"totalHitsRelation":"EQUAL_TO"}

`

kibana dsl:
`GET /company_index_test/_search
{
  "size":0,
  "aggs": {
    "group_by_companyOrgCode":
     {"terms":
     {
       "field":"companyOrgCode",
       "size":10,
       "min_doc_count":1,
       "shard_min_doc_count":0,
       "show_term_doc_count_error":false,
       "order":[{
         "_count":"desc"
         
       },{
         "_key":
         "asc"
         
       }]}}
    }
  }
}

[The java code result is inconsistent with Kibana's result. What is the value of the data under the grouping aggregation you want to take](https://github.com/spring-projects/spring-data-elasticsearch/issues/2646#issue-1817043003)
java:
![1690101853269](https://github.com/spring-projects/spring-data-elasticsearch/assets/113082331/2cdc5663-06e4-4dad-902c-10d9e460361b)
kibana:
![1690101896304](https://github.com/spring-projects/spring-data-elasticsearch/assets/113082331/4dd55b49-fe64-4219-b982-769844a2c768)

Could you please advise me? Thank you

**Comment by sothawo** [comment]
Did you debug your code and check what the returned `SearchHits` object contains instead of relying on the output of some JSON conversion? 

I just tried that on a test application and get aggregations in the result. But note that Spring Data Elasticsearch is out of maintenance.

**Comment by wangyandong1994** [comment]
searchHits.getAggregations().aggregations()
Unable to obtain buckets in the future
Can you paste the code you tested？

**Comment by wangyandong1994** [comment]
![b8e2ae4d5116bff56fe80a5a63dea2e](https://github.com/spring-projects/spring-data-elasticsearch/assets/113082331/68bf14e0-0593-4141-9bef-f18fd983b2d5)

**Comment by wangyandong1994** [comment]
![1690123386438](https://github.com/spring-projects/spring-data-elasticsearch/assets/113082331/f503ed64-c8b7-4d88-bc86-03136191b98c)
The problem has been resolved, thank you

**Comment by sothawo** [comment]
So you are getting a result back. The classes you see in this data (`ParsedStringTerms` or the `ParsedStringTerms@ParsedBucket`) are the native classes from the used Elasticsearch library, in your case the deprecated rest high level client.

The current code of Spring Data Elasticsearch will return the aggregations results from the new Elasticsearch client library in this place. To analyse this in your code, you need to read through these returned values by yourself, there is no abstraction provided by Spring Data Elasticsearch for this. 

- Just while writing this comment, I saw your latest answer, so I'll close this.

**Comment by wangyandong1994** [comment]
spring data elasticsearch4.4.5推荐的客户端是哪个，麻烦告知

**Comment by wangyandong1994** [comment]
Which client is recommended for spring data elastic search 4.4.5? Could you please let me know

**Comment by sothawo** [comment]
Spring Data Elasticsearch  4.4 uses the old rest high level client as default, but optionally could be configured to use the new client (in the version that was available at that time).

Since 5.0 the new client is the default, but that is built against the Elasticsearch libraries in version 8, is based on Spring 6 that in turn needs JDK 17. So you should see to migrate your application and setup to use current versions.

**Comment by wangyandong1994** [comment]
So I am currently using ElasticsearchRestTemplate in Spring Data Elasticsearch4.4.5, which corresponds to the official version and is correct. It's just that I didn't use the latest 5.0 client, right?

**Comment by sothawo** [comment]
It's the official client for that version of Spring Data Elasticsearch, yes. But as I said, this version is out of maintenance and will not get any further updates and fixes.

**Comment by wangyandong1994** [comment]
Thank you for your reply. thanks
