### ISSUE TITLE
@Field annotation Ignored When Index Creation is Not Done on Bootstrap Stage

### ISSUE THREAD

**Issue by rjma30** [spring-projects/spring-data-elasticsearch#2660]
Spring Boot 2.7.9
Spring Data Elasticsearch 4.4

Hello, I'm using reactive elasticsearch repository and using a sample entity below.

```@Getter
@Setter
@Document(indexName = "test", createIndex = false)
public class TestEntity {

  @Id
  private String id = UUID.randomUUID().toString();

  @Field(type = FieldType.Ip)
  private String ip;

  @Field(type = FieldType.Date, format = DateFormat.basic_date_time)
  private ZonedDateTime firstSeen;
}

public interface TestRepository extends ReactiveSortingRepository<TestEntity, String> {}
```

Since createIndex is set to false, index will only be created when you save an entity. As I understand it, the mappings will be based on the `@Field` annotations you set in you entity but I'm not sure why both fields `ip` and `firstSeen` become Text when the index is created.

```
        "ip": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "first_seen": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
```

Also, it is fine when index is created during bootstrap (when createdIndex is true).

Thanks in advance!

**Comment by sothawo** [comment]
When `createIndex` is set to false, Spring Data Elasticsearch will neither create the index, nor write the mapping.

The index is created **automatically by Elasticsearch** when a document is stored. Elasticsearch does not know about the values from the `@Field` annotations, and so does dynamic mapping, see the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/dynamic-mapping.html) about that.

If you want to have a mapping written without automatic index creation, you can use the `IndexOperations.putMapping()` method, but beware that mappings already existent in an index cannot be updated.

**Comment by rjma30** [comment]
Thanks a lot for your feedback @sothawo ! Appreciate it. I just misunderstood the statement written [here](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.repositories.autocreation).
