### ISSUE TITLE
Support for nanoseconds in DateFormat

### ISSUE THREAD

**Issue by GewuerzRegal** [spring-projects/spring-data-elasticsearch#2676]
Elasticsearch supports dateformats with nanoseconds, but spring data elasticsearch doesn't support this:
https://docs.spring.io/spring-data/elasticsearch/docs/current/api/org/springframework/data/elasticsearch/annotations/DateFormat.html
Could that be supported in the near future?
We need this to sort realtime events, there multiple events are inbound during the same millisecond.

**Comment by sothawo** [comment]
Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/date_nanos.html
