### ISSUE TITLE
spring-data-elasticsearch doesn't support elasticsearch sql

### ISSUE THREAD

**Issue by zzy444626905** [spring-projects/spring-data-elasticsearch#2683]
elasticsearch sql like this:

select count(1) from "indexPrefix*"

**Comment by sothawo** [comment]
That's right, would need to check if the Elasticsearch Java client supports this.

**Comment by sothawo** [comment]
ok, the Java client has a `co.elastic.clients.elasticsearch.sql.ElasticsearchSqlClient`, so support for this could be implemented.

**Comment by zzy444626905** [comment]
> ok, the Java client has a `co.elastic.clients.elasticsearch.sql.ElasticsearchSqlClient`, so support for this could be implemented.

Thank big boss for supporting for this,  make me stand on the shoulders of giants.

**Comment by sothawo** [comment]
I had a deeper look today. Althoug integrating the query part is quite easy, it is way harder to find a good way to parse the response returned from an Elasticsearch SQL query into the entities that Spring Data Elasticsearch uses.

For the time being, I wrote a short post (https://www.sothawo.com/post/2023/11/14/use-elasticsearch-sql-with-spring-data-elasticsearch/) about this can currently be integrated int an application, but you need to do the response processing by yourself.
