### ISSUE TITLE
[FEATURE] Support Multi search template API

### ISSUE THREAD

**Issue by gquintillan** [spring-projects/spring-data-elasticsearch#2704]
It would be nice if `org.springframework.data.elasticsearch.core.SearchOperations#multiSearch(java.util.List<? extends org.springframework.data.elasticsearch.core.query.Query>, java.lang.Class<T>)` supports [Multi Search Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-search-template.html#multi-search-template).

At the moment It is possible to use `org.springframework.data.elasticsearch.core.query.SearchTemplateQuery` like this:

```
private final ElasticsearchOperations elasticsearchOperations;

[...]

SearchTemplateQuery searchQueryA = SearchTemplateQuery.builder()
                .withId("search_query_template_id")
                .withParams(
                        Map.of(
                                "param_a", "value")))
                .build();
elasticsearchOperations.search(searchQueryA, CustomDoc.class);
```

But it would be nice to also be able to run [Multi Search Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-search-template.html#multi-search-template) like this:

```
private final ElasticsearchOperations elasticsearchOperations;

[...]

SearchTemplateQuery searchQueryA = SearchTemplateQuery.builder()
                .withId("search_query_template_id_a")
                .withParams(
                        Map.of(
                                "param_a", "value")))
                .build();

SearchTemplateQuery searchQueryB = SearchTemplateQuery.builder()
                .withId("search_query_template_id_b")
                .withParams(
                        Map.of(
                                "param_a", "value")))
                .build();

elasticsearchOperations.multiSearch(List.of(searchQueryA, searchQueryB), CustomDoc.class);
```

More info: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-search-template.html

**Comment by gquintillan** [comment]
I tried this alternative:

```
private final ElasticsearchClient elasticsearchClient;
[...]

final MsearchTemplateRequest msearchTemplateRequest = MsearchTemplateRequest.of([...]);

[...]

elasticsearchClient.msearchTemplate(msearchTemplateRequest, CustomDoc.class);

```

But the annotation`@Document` is not taken into account (it does not map the document to the POJO as expected) and we lose very useful features that are included with `ElasticsearchOperations`.

**Comment by sothawo** [comment]
> elasticsearchOperations.multiSearch(List.of(searchQueryA, searchQueryB), CustomDoc.class);

would probably be not enought, each of the queries could target a different index and might have a different entity class as it's return value. So we'd need a list of entity classes as second argument.
Basically the same emthod variants as we have for `ElasticsearchOperations.multiSearch()`.
