### ISSUE TITLE
Unable to implement subaggregation

### ISSUE THREAD

**Issue by abhinav-08** [spring-projects/spring-data-elasticsearch#2711]
I am using spring-data-elasticseach v5.1.2 and i am not able to add a subaggregation to my Terms-aggregation.
Can anyone help me with some resource that can help me with this.
Thanks.

**Comment by sothawo** [comment]
This is not a Spring Data Elasticsearch issue, but a question concerning the [Elasticsearch Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html), but that documentation seems not to cover questions like that.

The best you can do is to have a look at the [API docs](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html) for the desired info, this will map pretty straight to the API of the Elasticsearch client.

For your question this then leads to code like this:

```java
NativeQuery.builder()
  .withQuery(qb -> qb.matchAll(mab -> mab))
  .withAggregation("my-agg-1", Aggregation.of(ab -> ab
    .terms(tab -> tab.field("termsfield"))
    .aggregations("my-sub-aggregation", sab -> sab
      .avg(aab -> aab.field("avgfield")))
    ))
  .build();
```

**Comment by abhinav-08** [comment]
thanks for the very quick response, I will look into the resources.
just one more thing, I am not able to find sub aggregation in spring-data-elastic as well, So is it pending to get released or what's the case ?

**Comment by sothawo** [comment]
To use aggregations, you need to use a `NativeQuery` from Spring Data Elasticsearch like shown above. Everything you pass into the `withAggregation()` method is data built using the code from the Elasticsearch client library (Spring Data Elasticsearch  is not Elasticsearch, it just uses it). There are no aggregation classes in Spring Data Elasticsearch and no sub-aggregation classes.

**Comment by abhinav-08** [comment]
Thanks a lot Peter for the help, I was stuck on this issue for a long time.
thanks a lot.
