### ISSUE TITLE
Connect to multiple ES instances from same Spring Boot App

### ISSUE THREAD

**Issue by pieterjd** [spring-projects/spring-data-elasticsearch#2738]
I'm currently working on a migration project where I need to connect to 2 different ES instances. As such I would like to have two ElasticSearchRepository beans, one for each instance.

As far as I can tell based on the documentation, this is currently not possible, so I'm looking for workaround. Can you provide me with some tips on how to tackle this particular issue?

Thanks!
Pieter-Jan

**Comment by sothawo** [comment]
I hope I find the time to write something about this today or tomorrow

**Comment by pieterjd** [comment]
I think I'm actually onto something: I noticed the [``EnableElasticsearchRepositories``](https://javadoc.io/doc/org.springframework.data/spring-data-elasticsearch/latest/org/springframework/data/elasticsearch/repository/config/EnableElasticsearchRepositories.html) annotation has the ``elasticsearchTemplateRef`` attribute, that is then used in  the``ElasticSearchRepository`` bean. So you create a  template bean with the client connecting to 1 ES instance, and autowire it in the  ``ElasticSearchRepository`` bean. 

I think the next step is to use the ``[basePackages](https://javadoc.io/static/org.springframework.data/spring-data-elasticsearch/5.1.5/org/springframework/data/elasticsearch/repository/config/EnableElasticsearchRepositories.html#basePackages()) attribute to specify in which package the config for the ES instance resides in.

If this works, next step is to repeat this pattern for ES instance number 2 and see if I can connect to both instances.

I'll keep you posted.

**Comment by sothawo** [comment]
yes, basically:
* disable all autoconfiguration for Elasticsearch/Spring Data Elasticsearch from Spring Boot
* provide two different `ElasticsearchOperations` beans with different names
* separate the repositories into different packages
* for each of these packages use an `@EnableElasticsearchRepositories` specifiying the corresponding `elasticsearchTemplateRef` - and eventually the base package

**Comment by pieterjd** [comment]
I got it working, it's a mix of what I tried and what @sothawo described. Thans for the help!

**Comment by sothawo** [comment]
in case someone stumbles upon this issue: I wrote a short article about one way to do this: https://www.sothawo.com/post/2023/11/18/use-two-different-elasticsearch-clusters-with-spring-data-elasticsearch/
