### ISSUE TITLE
Elasticsearch classes annotated with JsonpDeserializable are not deserialized properly

### ISSUE THREAD

**Issue by maxio89** [spring-projects/spring-data-elasticsearch#2747]
We have a `@RestController` which returns `co.elastic.clients.elasticsearch.cluster.HealthResponse `that is annotated with `@JsonpDeserializable`, but the response is empty. 

I tried to add
```xml
<dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jakarta-jsonp</artifactId>
        <version>2.15.3</version>
</dependency>
```

and

```java
    @Bean
    public Jackson2ObjectMapperBuilderCustomizer customizeObjectMapper() {
        return builder -> builder.modules(new JSONPModule());
    }
```
but with no luck.

**Comment by sothawo** [comment]
What has this to do with Spring Data Elasticsearch?

**Comment by maxio89** [comment]
Where do you think is the best place to ask this question?
I think that if Spring Data Elasticsearch integrates Spring with Elasticsearch library may provide also a way to deserialize response from Elasticsearch.

**Comment by sothawo** [comment]
First without any code it's hard to say. But you are using a class from an Elasticsearch librray to be returned by a Spring RestController. Spring Data Elasticsearch does not use a Jackson object mapper, so this is either a Spring or a Spring Boot problem.
