### ISSUE TITLE
Springboot integration Elasticsearch @Filed fails

### ISSUE THREAD

**Issue by wuwei0727** [spring-projects/spring-data-elasticsearch#2748]
The springboot version is 2.3.12.RELEASE, the Elasticsearch client uses 7.6.2, and the corresponding spring data Elasticsearch is 4.0.9
![278556373-6545f51f-affa-4c4d-854a-c56703540f49](https://github.com/spring-projects/spring-data-elasticsearch/assets/100761249/d9af4f28-a344-4e2f-a7b6-b58dafc5dcbe)

Now when using the officially provided ElasticsearchRepository interface to save data, there is an ESInfraredOriginal class. This class has the @document (indexName = "infrared-original") annotation, and each attribute has the @field annotation.
![278556484-e8de6873-6db5-4e52-9237-e95e013fbabf](https://github.com/spring-projects/spring-data-elasticsearch/assets/100761249/282a85aa-7127-4963-a3a9-12a6d991d406)

My interface inherits the official ElasticsearchRepository：
![278556541-d7815b5c-3bc1-4055-b9bf-58a2c20eeb33](https://github.com/spring-projects/spring-data-elasticsearch/assets/100761249/57fb190a-b189-4af7-8ad0-aac99be66bf0)

I used the controller to test and the index was created, but why is the type different? My annotation@field specifies type, why does it not take effect? Why are the types of Elasticsearch different?
![278557008-ce74d987-76e1-44c9-a95e-33c0768fb29c](https://github.com/spring-projects/spring-data-elasticsearch/assets/100761249/fc8dbd4a-e8ee-4b6b-a9dc-b793703d2008)

**GET /infrared-original1/_mapping：**
![278557293-89dac8dd-b94e-4a73-be08-990a26b968d1](https://github.com/spring-projects/spring-data-elasticsearch/assets/100761249/a26dcc93-78d6-458e-a0ab-3aa5fe640672)

**Comment by sothawo** [comment]
1. the versions you use are really outdated and out of maintenance.
2. Provide code and such as formatted text and not as images
3. When a string value in a mapping in Elasticsearch has a type of _text_ and a subfield of type _keyword_ with _ignore_above_ this is a sign that data was inserted into the index before the mapping was defined and so that entry was created by Elasticsearch automatically.
4. Spring Data Elasticsearch only writes the mapping when an index is newly created. When it already exists, for example because some other application already data into the index, the then existing mapping is not updated.

**Comment by wuwei0727** [comment]
Hello! How can I solve this problem? Need to provide code etc formatted as text?

> 1. 您使用的版本确实已经过时并且不再维护。
> 2. 提供代码等格式化文本而不是图像
> 3. _当 Elasticsearch 中的映射中的字符串值具有文本_类型和带有_ignore_above类型__关键字_的子字段时，这表明数据在定义映射之前已插入到索引中，因此 Elasticsearch 会自动创建该条目。__
> 4. Spring Data Elasticsearch 仅在新创建索引时写入映射。当它已经存在时，例如因为某些其他应用程序已经将数据写入索引，则不会更新现有的映射。

Hello! How can I solve this problem? Need to provide code etc formatted as text?

**Comment by sothawo** [comment]
In order for the `@Field` values to be used, make sure that the index does not exist when starting the application, so that the repository will create it with the correct mapping definitions

**Comment by wuwei0727** [comment]
> 为了`@Field`使用这些值，请确保启动应用程序时索引不存在，以便存储库将使用正确的映射定义创建它

There is no index created before my application starts. Elasticsearch does not have an index. The picture above was created by spring-data-elasticsearch. I use the one provided by spring-data-elasticsearch: org.springframework.data.elasticsearch.repository. Created by the ElasticsearchRepository interface. But when it was created, it was not created according to the type declared by my @Field annotation.

**Comment by sothawo** [comment]
Provide a reproducer - a minimal, compilable, runnable project that shows this error, but for this use a version of Spring Data Elasticsearch that is still supported (5.0 or 5.1). 4.0 had end of maintanenance and support in May 2021.

**Comment by wuwei0727** [comment]
> Provide a reproducer - a minimal, compilable, runnable project that shows this error, but for this use a version of Spring Data Elasticsearch that is still supported (5.0 or 5.1). 4.0 had end of maintanenance and support in May 2021.

I can provide you with one of my github warehouses with my code: https://github.com/wuwei0727/ElasticsearchDemo.

**Comment by sothawo** [comment]
Sorry, that project is not using a supported version of Spring Data Elasticsearch. Upgrade to a version that is still maintained.

**Comment by sothawo** [comment]
Had a short look, you need `@EnableElasticsearchRepositories` on a configuration class (`@SpringBootApplication` is a `@Configuration` as well)

```java
@SpringBootApplication
@EnableElasticsearchRepositories
public class ElasticsearchDemoApplication {
```

**Comment by wuwei0727** [comment]
> 看简单一点，您需要`@EnableElasticsearchRepositories`一个配置类（`@SpringBootApplication`也是一个`@Configuration`）
> 
> ```java
> @SpringBootApplication
> @EnableElasticsearchRepositories
> public class ElasticsearchDemoApplication {
> ```



> Had a short look, you need `@EnableElasticsearchRepositories` on a configuration class (`@SpringBootApplication` is a `@Configuration` as well)
> 
> ```java
> @SpringBootApplication
> @EnableElasticsearchRepositories
> public class ElasticsearchDemoApplication {
> ```

Solved my problem! Thank you very much for your patient answer! thank you very much!
