### ISSUE TITLE
ReactiveElasticsearchClient missing simple count() method

### ISSUE THREAD

**Issue by maxio89** [spring-projects/spring-data-elasticsearch#2749]
Is there a way to send a CountRequest without having an entity and repository?
What if I want to count number of documents in some index when having only index name?

**Comment by maryantocinn** [comment]
Hi @sothawo, I noticed the count() method is still not implemented yet, and was wondering if it’s still needed. If so, I’d be happy to contribute.

**Comment by sothawo** [comment]
Feel free to implement this, I think this should be 2 methods then, `public Mono<CountResponse> count(CountRequest request)` and the variant taking a `Function<CountRequest.Builder, ObjectBuilder<CountRequest>> fn` as parameter.
