### ISSUE TITLE
Why do you need to create both @Document and Repository classes to automatically create an index?

### ISSUE THREAD

**Issue by SsSs2020** [spring-projects/spring-data-elasticsearch#2750]
I want to automatically create an index. When the service starts, why do I need to create the @ Document and Repository classes instead of just using @ Document? Why do I need to do this?

Elasticsearch version 7.10.0
spring-boot-starter-data-elasticsearch:2.6.7

**Comment by sothawo** [comment]
`@Document` does not create anything. This annotation marks a class as entity class and provides the information about the different properties and their types (by using the `@Field` annotation on a property. Putting the `@Document` annotation on a class also puts the class into the mapping context which is used when mapping entities to the representation in Elasticsearch and back. 

The basic concept of Spring Data is the repository which stores entity types. The repository is responsible to create an index (in the case of Spring Data Elasticsearch) if needed and intialize this index with the settings and mappings defined on the entity.

If you want to have an index autocreated without using a repository you need to provide some method that is automatically invoked on startup after the Spring context is initialized (an `@Autowired` method or some `@PostConstruct` or an application listener) and in this method check if the index exists and if not create it (with the settings and mappings); the necessary methods are available in the `IndexOperations` class which you can obtain from an injected `ElasticsearchOperations`.

**Comment by SsSs2020** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到来信，尽快给您回复。

**Comment by SsSs2020** [comment]
Thanks for your response.
