### ISSUE TITLE
SimpleElasticsearchRepository - delete no longers supports routing?

### ISSUE THREAD

**Issue by whalewired** [spring-projects/spring-data-elasticsearch#2754]
We use Routing on a Document.

When upgrading from 4 to 5 we now get exception when calling delete using ElasticsearchRepository:

`
org.springframework.data.elasticsearch.UncategorizedElasticsearchException: [es/delete] failed: [routing_missing_exception] routing is required for
`

As far as I can tell the routing support has been removed in

https://github.com/spring-projects/spring-data-elasticsearch/blame/main/src/main/java/org/springframework/data/elasticsearch/repository/support/SimpleElasticsearchRepository.java

Version 5.1.5

```
	public void delete(T entity) {
		Assert.notNull(entity, "Cannot delete 'null' entity.");
		doDelete(extractIdFromBean(entity), getIndexCoordinates());
	}

```
Version 4.4.6 

```
	public void delete(T entity) {
		Assert.notNull(entity, "Cannot delete 'null' entity.");
		doDelete(extractIdFromBean(entity), operations.getEntityRouting(entity), getIndexCoordinates());
	}

```
Is there another way delete is supposed to be used when routing is involved?

**Comment by sothawo** [comment]
That shouldn't have been removed (was already in 5.0). UP to now nobody noticed. Thanks for bringing this up. Will try to fix it later today.
