### ISSUE TITLE
Why does spring-data-elasticsearch use the PUT method to perform a SAVE instead of the POST method?

### ISSUE THREAD

**Issue by Jakentop** [spring-projects/spring-data-elasticsearch#2758]
I am using spring-boot version 3.2.0-RC2,elasticsearh is using version 8.10.2.I created a new entity and tried to save him via save method. But the execution failed I got the following error:

org.springframework.data.elasticsearch.UncategorisedElasticsearchException: [es/index] failed: [null] Incorrect HTTP method for uri [/test- index/_doc/?refresh=false] and method [PUT], allowed: [POST]

here is code：

``` java
@Document(indexName = "test-index", createIndex = true)
@Data
public class Test {
    @Id
    private String id;
    private String name;
    private LocalDateTime time;
    private Integer age;
}
public interface TestRepository extends ElasticsearchRepository<Test, String> {
}
@Service
public class Test{

  @Resource
  TestRepository testRepository;
  
  public void test(){
   Test t=new Test();
   t.setName("123");
    testRepository.save(t);
    }
}

```
The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/docs-index_.html) for elasticsearch indicates that [PUT] /test-index/_doc is not supported, so if you need to update the document, you need to add the id. Of course, I'm just trying to insert the document here, which should generate [POST] /test-index/_doc.

**Comment by sothawo** [comment]
I saw and answered this recently in a [StackOverflow post](https://stackoverflow.com/a/77247283/4393565).

Can it be that the `id` of your class is somehow initialized to an empty String `""`? What happens if you explicitly do a call `t.setId(null)`?

**Comment by Jakentop** [comment]
Thank you very much, indeed I configured the id as an empty string, now it works

> I saw and answered this recently in a [StackOverflow post](https://stackoverflow.com/a/77247283/4393565).
> 
> Can it be that the `id` of your class is somehow initialized to an empty String `""`? What happens if you explicitly do a call `t.setId(null)`?
