### ISSUE TITLE
 [nested] nested object under path [attributerelations] is not of nested type

### ISSUE THREAD

**Issue by wangyandong1994** [spring-projects/spring-data-elasticsearch#2759]
version:JDK11、Gradle6.8.2、Elasticearch7.17.6、Spring Data Elasticsearch 4.4.5
When creating an index,the code is as follows:
The first step:
`@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
@Accessors(chain = true)
@Document(indexName = "company_test")
public class CompanyDataEsPo implements Serializable {
    /**
	 * 企业id
	 */
	@Id
    Integer id;

    @Field(type = FieldType.Nested, name = "attributerelations")
    List<CompanyAttributeRelationEsPo> attributerelations;
}

public interface CompanyDataRepository extends ElasticsearchRepository<CompanyDataEsPo, Integer> {
	
}

CompanyDataEsPo esPo = new CompanyDataEsPo();
List<Integer> attributeList = companyRootService.findType(company.getId());
List<CompanyAttributeRelationEsPo> roleAttributeList = new ArrayList<>();
if(CollectionUtils.isNotEmpty(attributeList)) {
    roleAttributeList = attributeList.stream().map(o -> new CompanyAttributeRelationEsPo().setAttribute(o).setType(1)).collect(Collectors.toList());
}
esPo.setAttributerelations(roleAttributeList);
companyDataRepository.save(esPo);`
View Index Structure：
`{
  "company_test" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "_class" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "attributerelations" : {
          "type" : "nested",
          "properties" : {
            "_class" : {
              "type" : "keyword",
              "index" : false,
              "doc_values" : false
            },
            "attribute" : {
              "type" : "integer"
            },
            "type" : {
              "type" : "integer"
            }
          }
        },
        "id" : {
          "type" : "long"
        }
      }
    },
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "company",
        "creation_date" : "1699929391112",
        "number_of_replicas" : "1",
        "uuid" : "3ppQlIVMTpqFjPjufuyzxg",
        "version" : {
          "created" : "7170699"
        }
      }
    }
  }
}`
Step 2:
`elasticsearchRestTemplate.indexOps(IndexCoordinates.of("company_test")).delete()`

Step 3
repeat step 1 to create the index

View Index Structure：
`{
  "company_test" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "_class" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "attributerelations" : {
          "properties" : {
            "attribute" : {
              "type" : "long"
            },
            "type" : {
              "type" : "long"
            }
          }
        },
        "id" : {
          "type" : "long"
        }
      }
    },
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "company",
        "creation_date" : "1699929391112",
        "number_of_replicas" : "1",
        "uuid" : "3ppQlIVMTpqFjPjufuyzxg",
        "version" : {
          "created" : "7170699"
        }
      }
    }
  }
}`

Delete the index and create another index with the same name. The FieldType. Tested field cannot be created successfully, resulting in an error during the query: failed to create query: [nested] nested object under path [attributerelations] is not of nested type

Is this normal, only new index names can be used?

**Comment by sothawo** [comment]
I cannot see what your step 1 is, can you format you code properly please. Besides that:
1. Repository support only creates an index if it does not yet exist
2. the versions you use are out of maintenance, if you want us to look at this issue, provide a reproducer with the current version.
