### ISSUE TITLE
Missing ElasticsearchCatAsyncClient reactive implementation

### ISSUE THREAD

**Issue by maxio89** [spring-projects/spring-data-elasticsearch#2761]
Operations like `catClient.indices()` or `catClient.aliases()` might have their implementations in reactive version of `ElasticsearchCatAsyncClient`.

**Comment by sothawo** [comment]
The `ReactiveElasticsearchClient` does not have all the methods that its imperative counterpart from the Elasticsearch library has. It has basically the methods that were needed to implement the current functionality of Spring Data Elasticsearch.

Feel free to implement functionality and provide this with a Pull Request.
