### ISSUE TITLE
DocumentAdapters converts sort values to string

### ISSUE THREAD

**Issue by whalewired** [spring-projects/spring-data-elasticsearch#2777]
When upgrading from 4.2.12 to 5.1.5 search_after on sorted date fields, that does not specify pattern, no longer works. 

In 4.2.12 the returned sort value was Long (epoch_millis).

In 5.1.5 it is converted to a String.

It happens her: 

org.springframework.data.elasticsearch.client.elc.DocumentAdapters

```
return new SearchDocumentAdapter(document, score, hit.sort().stream().map(TypeUtils::toString).toArray(),
				documentFields, highlightFields, innerHits, nestedMetaData, explanation, matchedQueries, hit.routing());

```
If that String is used in search_after Elasticsearch fails with "failed to parse date field". 

When it stays as a Long it works fine.

One could add "format" pattern to the sort part to fix this so it uses that pattern consistently, but the use of Long also worked, so my question is, why are these converted to string?

**Comment by sothawo** [comment]
I have to check into this one. I remember that the new Elasticsearch client in the beginning used to always return the sort values in a String array, but they may have changed this in the meantime.

**Comment by whalewired** [comment]
Will this go into 5.1.7?

**Comment by sothawo** [comment]
> Will this go into 5.1.7?

yes
