### ISSUE TITLE
@Field Type Date does not match default format -> strict date formats missing

### ISSUE THREAD

**Issue by DKlaper** [spring-projects/spring-data-elasticsearch#2779]
Short version: I did not manage to map the date format "strict_date_optional_time||epoch_millis" with the provided annotations.

Extended explanation: 
- I have an existing Elasticsearch index with a date field. The date field was created without specifying a format so it has the elasticsearch default of "strict_date_optional_time||epoch_millis" (see here https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html)
- I then created a @Document-annotated class where I annotate the date field with just @Field(type = FieldType.Date).
- Then I try to put the mapping of the document to the index and get the Exception: "Mapper for XXX conflicts with existing mapper: Cannot update parameter [format] from [strict_date_optional_time||epoch_millis] to [date_optional_time||epoch_millis]"
- I then also had to find out that I cannot provide the existing format to the annotation @Field(type =  FieldType.Date, format = ???) because DateFormat does not contain the strict formats. 

So I could not find a way to have a strict date format (besides the one with nanos that was added in this issue https://github.com/spring-projects/spring-data-elasticsearch/issues/2676).

In my opinion annotating @Field(type = FieldType.Date) should have the same effect as specifying a date in the mapping without format so should lead implicitely to "strict_date_optional_time||epoch_millis". In addition I think it would make sense for the DateFormat Enum to contain all Elasticsearch supplied values including the strict versions even if from a parsing perspective they are very similar.

**Comment by sothawo** [comment]
> Then I try to put the mapping of the document to the index

One cannot update the mapping for an existing field in Elasticsearch.

Besides not being able to change the mapping, do you get errors when writing or reading data with Spring Data Elasticsearch?

**Comment by DKlaper** [comment]
> > Then I try to put the mapping of the document to the index
> 
> One cannot update the mapping for an existing field in Elasticsearch.
> 
> Besides not being able to change the mapping, do you get errors when writing or reading data with Spring Data Elasticsearch?

I do not want to change the mapping! I only execute PutMapping to ensure that the mapping I have in code is up to date  with the index. 
The only thing that I want is to use spring data elasticsearch with the existing index. However, I do not see a way in which I can annotate my DTO with @Field in a way that the mapping generated is the same as the existing mapping.

Maybe I was a bit unclear. Asked differently. I have the following existing property in my mapping:
`"dueDate" :{"type":"date" }`
which is equivalent to:
`"dueDate" :{"type":"date","format":"strict_date_optional_time||epoch_millis" }`

How can I annotate my DTO with @Field to comply to this mapping? 

There is no field type for strict_date_optional_time so the closest I could get was this: 
`"dueDate" :{"type":"date","format":"date_optional_time||epoch_millis"}`
Which is what happens if I don't put the format parameter in the @field annotation
