### ISSUE TITLE
Save from elasticsearch repository always does a refresh

### ISSUE THREAD

**Issue by on-delete** [spring-projects/spring-data-elasticsearch#2787]
We recently had to debug a performance issue, where multiple concurrent bulk save requests on one index had the affect, that one save operation took around 1 minute, where it usually would take around some milliseconds.

Upon investigating we found out, that if we do the saveAll call with a ElasticsearchRepository, the save also does trigger a refresh on the index on every call. As this was performed for every concurrent save call, the index was under a lot of stress, as this seems to be a costly operation, and should be done by the Elasticsearch periodically instead.

Can this behaviour be changed? Is this somehow documented? We ended up using the bulkIndex method from the ElasticsearchTemplate, where this refresh is not triggered.

**Comment by sothawo** [comment]
Which version of Spring Data Elasticsearch do you use. How is your client configured?

**Comment by on-delete** [comment]
Spring Data Elasticsearch v4.4.8. 

``` 
RestHighLevelClient client = new RestHighLevelClient(RestClient
    .builder(createHostsArray(elasticSearchConfig.getHostUrls()))
    .setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder
        .setConnectionRequestTimeout(elasticSearchConfig.getConnectionRequestTimeout())
        .setConnectTimeout(elasticSearchConfig.getConnectTimeout())
        .setSocketTimeout(elasticSearchConfig.getSocketTimeout()))
    .setHttpClientConfigCallback(new HttpClientConfigCallback() {
        @Override
        public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
            return httpClientBuilder
                .setMaxConnPerRoute(elasticSearchConfig.getMaxConnectionsPerRoute())
                .setMaxConnTotal(elasticSearchConfig.getMaxConnections())
                .setDefaultIOReactorConfig(
                    IOReactorConfig.custom()
                        .setIoThreadCount(elasticSearchConfig.getDispatcherThreadCount()).build())
                .setSSLContext(createDummySslContext())
                .setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE)
                .setDefaultCredentialsProvider(credentialsProvider);
        }
    })); 
```

**Comment by sothawo** [comment]
Spring Data Elasticsearch 4.4.8 is out of maintenance.

You only showed the configuration of the `RestHighLevelClient`; when you have a configuration class like shown in https://docs.spring.io/spring-data/elasticsearch/docs/4.4.18/reference/html/#elasticsearch.clients.rest you can override the `refreshPolicy()` method to set a default value, setting it to `NONE` should help.
