### ISSUE TITLE
Chain operation failure of Criteria

### ISSUE THREAD

**Issue by twelvet-s** [spring-projects/spring-data-elasticsearch#2837]
version：Spring Boot 3.2.2
The effect of these two pieces of code should be the same, but surprisingly, the writing of the second one invalidated the condition.

normal code：
```java
Criteria criteria = new Criteria("isDeleted").is("Y").and("isOnline").is("N");
```

Invalid code:
```java
Criteria criteria = new Criteria("isDeleted").is("Y"); // normal 
criteria.and("isOnline").is("N"); // Invalid 
```

**Comment by twelvet-s** [comment]
I looked at the code and found that a new object was returned during and, but I did not receive the resulting invalidation. But in terms of habitual use, these two methods are generally supported. Is it because of some reason that it needs to be written like this.

**Comment by puppylpg** [comment]
> I looked at the code and found that a new object was returned during and

A new `Criteria` is created but the previous `CriteriaChain` is kept in new criteria.

I tried the queries and both of them work well and behave the same:
```java
// query1
new Criteria("keywords").contains(expectedWord).and("date").greaterThanEqual(expectedDate);

// query2
Criteria criteria = new Criteria("keywords").contains(expectedWord);
criteria.and("date").greaterThanEqual(expectedDate)
```
Could you please provide a sample project to reproduce the error?

**Comment by twelvet-s** [comment]
> > I looked at the code and found that a new object was returned during and
> 
> A new `Criteria` is created but the previous `CriteriaChain` is kept in new criteria.
> 
> I tried the queries and both of them work well and behave the same:
> 
> ```java
> // query1
> new Criteria("keywords").contains(expectedWord).and("date").greaterThanEqual(expectedDate);
> 
> // query2
> Criteria criteria = new Criteria("keywords").contains(expectedWord);
> criteria.and("date").greaterThanEqual(expectedDate)
> ```
> 
> Could you please provide a sample project to reproduce the error?

// query2 repair plan
```java
Criteria criteria = new Criteria("keywords").contains(expectedWord);
criteria = criteria.and("date").greaterThanEqual(expectedDate); // Redirect to a new object
```
Because a new object has been created, I need to receive it again to prevent it from becoming invalid.

It shouldn't be said that this is a bug, it's just because it's not quite in line with normal usage.

**Comment by puppylpg** [comment]
Seems I understand what you mean:
```java
		Criteria criteria = new Criteria("keywords").contains(expectedWord);
		// the 'and' clause will be ignored because it'll return a new object
		criteria.and("date").greaterThanEqual(expectedDate);

		// but the criteria passed into the query is still the old
		var query = new CriteriaQuery(criteria);
```
Something like this?

**Comment by twelvet-s** [comment]
> Seems I understand what you mean:
> 
> ```java
> 		Criteria criteria = new Criteria("keywords").contains(expectedWord);
> 		// the 'and' clause will be ignored because it'll return a new object
> 		criteria.and("date").greaterThanEqual(expectedDate);
> 
> 		// but the criteria passed into the query is still the old
> 		var query = new CriteriaQuery(criteria);
> ```
> 
> Something like this?

Yes, I have become accustomed to this writing style in my usual use, but unfortunately it is not currently supported.

**Comment by puppylpg** [comment]
I looked the API again, and found that the `and()` APIs in `Criteria` behave not the same:
- The `and(String)` or `and(Field)` will create and return a new object and will cause the problem as what you described
- however, the `and(Criteria)` will merge the new criteria into the old one.

In current version, to solve your problem you can use something like this:
```java
		Criteria criteria = new Criteria("keywords").contains(expectedWord);
		// the new criteria will be merged into the old one
		criteria.and(new Criteria("date").greaterThanEqual(expectedDate));

		var query = new CriteriaQuery(criteria);
```
And maybe the `and` APIs should behave the same in my opinion.

**Comment by twelvet-s** [comment]
> I looked the API again, and found that the `and()` APIs in `Criteria` behave not the same:
> 
> * The `and(String)` or `and(Field)` will create and return a new object and will cause the problem as what you described
> * however, the `and(Criteria)` will merge the new criteria into the old one.
> 
> In current version, to solve your problem you can use something like this:
> 
> ```java
> 		Criteria criteria = new Criteria("keywords").contains(expectedWord);
> 		// the new criteria will be merged into the old one
> 		criteria.and(new Criteria("date").greaterThanEqual(expectedDate));
> 
> 		var query = new CriteriaQuery(criteria);
> ```
> 
> And maybe the `and` APIs should behave the same in my opinion.

Thank you for your reminder. I have observed the API of this writing method and it returns the current object, which can solve my problem.

But these two different types of attendees have this problem, and we still hope that the two types of attendees can support this writing method

**Comment by sothawo** [comment]
It's documented in the API that the methods taking `Criteria` as parameter add this to the existing object and return this existing object wheres athe other two methods create new `Criteria` objects:
```
	/**
	 * Chain a new and-Criteria
	 *
	 * @param field the field for the new Criteria
	 * @return the new chained Criteria
	 */
	public Criteria and(Field field) {
		return new Criteria(criteriaChain, field);
	}

	/**
	 * Chain a new and- Criteria
	 *
	 * @param fieldName the field for the new Criteria
	 * @return the new chained Criteria
	 */
	public Criteria and(String fieldName) {
		return new Criteria(criteriaChain, fieldName);
	}

	/**
	 * Chain a Criteria to this object.
	 *
	 * @param criteria the Criteria to add
	 * @return this object
	 */
	public Criteria and(Criteria criteria) {

		Assert.notNull(criteria, "Cannot chain 'null' criteria.");

		this.criteriaChain.add(criteria);
		return this;
	}

	/**
	 * Chain an array of Criteria to this object.
	 *
	 * @param criterias the Criteria to add
	 * @return this object
	 */
	public Criteria and(Criteria... criterias) {

		Assert.notNull(criterias, "Cannot chain 'null' criterias.");

		this.criteriaChain.addAll(Arrays.asList(criterias));
		return this;
	}
```
In any case you should use the returned object.

what you describe as _invalid_ is just incorrect use:
```
Criteria criteria = new Criteria("isDeleted").is("Y"); // normal 
criteria.and("isOnline").is("N"); // Invalid 
```
In the second line the `and("isOnline")` creates a new object, which is then used for the `is("N")`. You should from then on use what's returned from the 'is()` call, but that object is discarded.

This is not a "Chain operation failure of Criteria" but you do not use the object returned from the chaining operation.
