### ISSUE TITLE
Add SpEL support for highlight query and source filter

### ISSUE THREAD

**Issue by puppylpg** [spring-projects/spring-data-elasticsearch#2852]
Since SpEL support has been added to `@Query` in addition to the old placeholder replacement(`?0`, `?1`, ...), we can now combine both of them together and apply to where the placeholder replacement was used. For example:
- `@Query` in `@Highlight`;
- `@SourceFilters`;

This will provide users with an identital experience in these similar situations.

**Comment by sothawo** [comment]
Haven't forgot to check this, but I'm quite busy currently. Hopefully will find the next week.
