### ISSUE TITLE
Move the filter part of a `CriteriaQuery` from post_filter into the created bool query.

### ISSUE THREAD

**Issue by sothawo** [spring-projects/spring-data-elasticsearch#2857]

**Comment by bernhardkern** [comment]
Hi @sothawo,

thx for creating this task. Can I provide any further information / support to help with this topic? For other participants working on this topic:

[Github example with failing test](https://github.com/bernhardkern/mix-native-query-with-criteria-query-bug-spring-data-elasticsearch/blob/main/src/main/kotlin/kern/elasticsearchplayground/NativeQueryWithCriteriaQueryWithLocationBug.kt)

Anytime we add an Aggregation, the CriteriaGeoQuery as base of NativeQuery the filter only works for the searchHits, but not for the aggregation.

**Comment by sothawo** [comment]
I don't think there's more information needed about what to do. I just did not yet have the time to look into this.
