### ISSUE TITLE
Got ClassNotFoundException using spring-data-aerospike 7.2.0 

### ISSUE THREAD

**Issue by netizenp** [spring-projects/spring-data-elasticsearch#2860]
I want to upgrade to java 17 in which i'm including the dependency of aerospike client spring-data-aerospike 7.2.0.

getting error : Factory method 'aerospikeTemplate' threw exception with message: org/springframework/data/convert/EntityInstantiators

`@Bean
    public AerospikeTemplate aerospikeTemplate() {
        CustomConversions conversions = new CustomConversions(Arrays.asList(AerospikeClientConfigConvertor.StringToJava8LocalDateConverter.INSTANCE,
                AerospikeClientConfigConvertor.LocalDateToStringConverter.INSTANCE,
                AerospikeClientConfigConvertor.ZonedDateTimeToStringConverter.INSTANCE,
                AerospikeClientConfigConvertor.StringToZonedDateTimeConverter.INSTANCE),
                AerospikeSimpleTypes.HOLDER);
        AerospikeMappingContext mappingContext = new AerospikeMappingContext();
        mappingContext.setDefaultNameSpace(aerospikeNamespace);
        MappingAerospikeConverter converter = new MappingAerospikeConverter(mappingContext,
                conversions, new AerospikeTypeAliasAccessor("type"));
        converter.afterPropertiesSet();
        return new AerospikeTemplate(aerospikeClient(), aerospikeNamespace, converter, mappingContext, new DefaultAerospikeExceptionTranslator());
    }`

**Comment by netizenp** [comment]
Im getting this error while working with aerospike.

**Comment by sothawo** [comment]
no visible relationship to Spring Data Elasticsearch
