### ISSUE TITLE
Settings of an index outside thé entity annotation

### ISSUE THREAD

**Issue by bameline** [spring-projects/spring-data-elasticsearch#2886]
I tried to find a wat to put settings on my index beside using @setting annotation.
I want to set a refreshinterval before indexation and another After.
IS there a way to do that?

**Comment by sothawo** [comment]
You can always get or set index settings by using the methods from `IndexOperations` (https://docs.spring.io/spring-data/elasticsearch/docs/current/api/org/springframework/data/elasticsearch/core/IndexOperations.html).

So you could read the current settings, set a different refresh intervall, do the indexing and after that reset to the original value.
