### ISSUE TITLE
ElasticsearchPersistentEntity isReadable method removed from the interface causing compilation error in 5.2.0

### ISSUE THREAD

**Issue by mukeshj13** [spring-projects/spring-data-elasticsearch#2887]
I am not seeing isReadable() method in the ElasticsearchPersistentEntity interface, although this is still being used in EntityOperations in the same module. I have seen this compilation error in 5.2.0 and it is present in 5.2.1 as well.

**Comment by sothawo** [comment]
There is no and never was a method 'isReadable()` in `ElasticsearchPersistentEntity`.

Such a method exists for a `ElasticsearchPersistentProperty`. Up until version 5.2 this was defined in the interface `ElasticsearchPersistentProperty`. From version 5.2 on, this is defined in the `PersistentProperty` from spring-data-commons 3.2 which `ElasticsearchPersistentProperty` extends.

If you run into an error about this method not being available anymore means that you changed the version of spring-data-elasticsearch to 5.2 but did not update the spring-data-commons dependency.
