### ISSUE TITLE
Configuring Spring Data Elasticsearch to Connect to Two Clusters

### ISSUE THREAD

**Issue by jayashri112830** [spring-projects/spring-data-elasticsearch#2909]
In our application, we need to maintain connections to two Elasticsearch clusters. According to the Spring Data Elasticsearch documentation, it's possible to connect to only one cluster by default. Is there a way to connect to two clusters in the same application? If so, how can we configure it?

**Comment by sothawo** [comment]
There was #2738, in that issue I linked to a post I wrote: https://www.sothawo.com/post/2023/10/18/use-two-different-elasticsearch-clusters-with-spring-data-elasticsearch/
