### ISSUE TITLE
How to test my improved nested queries

### ISSUE THREAD

**Issue by yxhwxn** [spring-projects/spring-data-elasticsearch#2921]
Currently, I am an undergraduate student in the Department of Computer Science at Kyung Hee University, South Korea. 

I found a code improvement in the process of generating nested query from nested data model in Spring data elasticsearch. And we've made some improvements to the nested query creation process.

I want to evaluate the performance of nested query.

Do you have any recommendations on how to test the query?

**Comment by sothawo** [comment]
> code improvement in the process of generating nested query 

what exactly do you mean here? 
* A different way to produce the same nested query from a `CriteriaQuery` as the current code? This should be measurable by running the query creation multiple times with probably different queries for each of the imlementations and measuring execution time.
* Producing a different nested query that is sent to Elasticsearch that returns the same results as the existing implementation? This is more difficult ads this culd only be tested with an integration test using a real Elasticsearch instance. For both implementations the same setup would be needed, same queries, same data. In both cases the Elasticsearch instance should be in the same warm-up state to make results comparable.

**Comment by yxhwxn** [comment]
> what exactly do you mean here?

I'll raise a new issue with my improved code, and I'll politely ask you more about testing methods at that time. Thank you for your response.
