### ISSUE TITLE
How to new object DeleteQuery

### ISSUE THREAD

**Issue by tungmr** [spring-projects/spring-data-elasticsearch#2925]
Hi, [DeleteQuery](https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/main/java/org/springframework/data/elasticsearch/core/query/DeleteQuery.java) and its Builder are private constructors, How can I create a new DeleteQuery object?

**Comment by sothawo** [comment]
The function to create a bulder is public:

https://github.com/spring-projects/spring-data-elasticsearch/blob/5.3.x/src/main/java/org/springframework/data/elasticsearch/core/query/DeleteQuery.java#L191-L193

```java
public static Builder builder(Query query) {
		return new Builder(query);
}
```

**Comment by tungmr** [comment]
Oh, sorry, my mistake. Thank you very much
