### ISSUE TITLE
Fix missing `elementType` when using elasticsearch-java 8.14.x

### ISSUE THREAD

**Issue by puppylpg** [spring-projects/spring-data-elasticsearch#2927]
`elementType ` is left out in elasticsearch-specification and is fixed in https://github.com/elastic/elasticsearch-java/pull/800. Adding `elementType = FieldElementType.FLOAT` is possible now.

**Comment by sothawo** [comment]
you mean 8.14.x, not 7.14.x?

**Comment by puppylpg** [comment]
My fault, should be 8.14.x
