### ISSUE TITLE
Cannot use `search_after` with field collapse

### ISSUE THREAD

**Issue by jorge-marques** [spring-projects/spring-data-elasticsearch#2935]
The elasticsearch documentation indicates that it is possible to use `search_after` with field collapse, as long the results are sorted exclusively by the collapsing field.

Is this possible with `spring-data-elasticsearch`? A cursory look at the code suggests it's not possible as `_shard_doc` is always added to the sort criteria as a tiebreaker

**Comment by sothawo** [comment]
I assume you are talking about calls to `ReactiveSearchOperations.search(Query,...)` as this is the only place where in the implementation _search_after_ is used?

So you are setting a `FieldCollapse` on a `NativeQuery` and want to add a `Sort` for that same field and that fails then?

The solution would probably be to not add the _shard_doc_ when there is a `FieldCollapse` set with a field name being the same as the one in the only `Sort` passed in.

**Comment by jorge-marques** [comment]
That's exactly right, the elasticsearch returns the following error:

`Cannot use [collapse] in conjunction with [search_after] unless the search is sorted on the same field. Multiple sort fields are not allowed`

I believe your proposed solution would work well.

**Comment by sothawo** [comment]
Implemented on _main_ branch and backported to current _5.3.x_.
