### ISSUE TITLE
Unable to covert my existing NativeSearchQueryBuilder into NativeQueryBuilder

### ISSUE THREAD

**Issue by naidusana** [spring-projects/spring-data-elasticsearch#2962]
How can I convert  below code using NativeQuery?

               BoolQueryBuilder bQB = QueryBuilders.boolQuery();
		bQB.must(QueryBuilders.termQuery("INDEX_NAME", "testindex"));
		bQB.must(QueryBuilders.termsQuery("STATUS", "INPROGRESS", "PUBLISHED"));
		bQB.must(QueryBuilders.termQuery("DATA_LOAD_TYPE", "INCR"));
		NativeSearchQueryBuilder nsqb = new NativeSearchQueryBuilder()
			.withQuery(bQB);

**Comment by sothawo** [comment]
Check the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/searching.html) for the use of the Java client, these are the queries passed in to `NativeQueryBuilder`. Elasticsearch modeled their Java API along the REST API, so the best probably is to build your query like you'd be sending it via REST and then transfer this to the Java code.
