### ISSUE TITLE
Replacement for Deprecated NativeSearchQueryBuilder in Spring Data Elasticsearch 5.3

### ISSUE THREAD

**Issue by stoneLee81** [spring-projects/spring-data-elasticsearch#2972]
I upgraded from Spring Data Elasticsearch 3.2.6 to Spring Data Elasticsearch 5.3 and found that the NativeSearchQueryBuilder class has been deprecated. I would like to ask which class replaces it?

**Comment by sothawo** [comment]
This was changed in 5.0 with the switch to the new Elasticsearch client library. The new class to use is the `NativeQuery` which is built using `NativeQueryBuilder`; as for the syntax to build these native queries you have to check out the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/searching.html)
