### ISSUE TITLE
``DeleteQuery > refresh`` field is unused

### ISSUE THREAD

**Issue by tuguri8** [spring-projects/spring-data-elasticsearch#2973]
Hello,

I saw that [refresh field](https://github.com/spring-projects/spring-data-elasticsearch/blob/6ad98bf5000b6d1cd585ed0c9bad5ce4dc223927/src/main/java/org/springframework/data/elasticsearch/core/query/DeleteQuery.java#L120) on DeleteQuery is unused.

It seems to work differently than described in the [javadoc](https://github.com/spring-projects/spring-data-elasticsearch/blob/6ad98bf5000b6d1cd585ed0c9bad5ce4dc223927/src/main/java/org/springframework/data/elasticsearch/core/query/DeleteQuery.java#L116-L119) (setting refresh=true doesn't seem to trigger refresh)

I think we should set the refresh based on the ``DeleteQuery > refresh`` field in [documentDeleteByQueryRequest](https://github.com/spring-projects/spring-data-elasticsearch/blob/6ad98bf5000b6d1cd585ed0c9bad5ce4dc223927/src/main/java/org/springframework/data/elasticsearch/client/elc/RequestConverter.java#L1002) method, I'll open PR if you agree!

**Comment by sothawo** [comment]
fell free to implement this
