### ISSUE TITLE
Add "took" attribute to SearchHits/ReactiveSearchHits

### ISSUE THREAD

**Issue by ELHARROUGUI** [spring-projects/spring-data-elasticsearch#2986]
I am working on a Spring API that integrates with Elasticsearch, and my current task involves migrating from the **Elasticsearch Java API Client** to **Spring Data Elasticsearch**. While doing so, I noticed that the response body in the Elasticsearch Java API Client includes a valuable attribute called **"took"**, which shows the time (in milliseconds) it took to complete the request. However, this attribute is not accessible in the **SearchHits** (or **ReactiveSearchHits**) body in Spring Data Elasticsearch.

This feature is important for performance monitoring and debugging, as it allows developers to measure the responsiveness of Elasticsearch queries.

I propose adding support for retrieving the **"took"** attribute from **SearchHits** objects in **Spring Data Elasticsearch**, ensuring **feature parity** with the **Elasticsearch Java API Client**. This enhancement would improve the developer experience by providing essential timing information for queries.

I would be happy to contribute to this feature by submitting a PR if accepted. Thank you!

**Comment by sothawo** [comment]
Fell free to add it; just a thought: I think we should use a better name than `took`, perhaps something like `executionDuration` and instead of using an `int` or `long` use a `java.time.Duration`

**Comment by ELHARROUGUI** [comment]
Thank you, @sothawo ! I can't think of a better name than executionDuration either :)

I just wanted to point out that in the Elasticsearch Java API, the attribute is declared as `tookInMillis` (as a `private long`), but they use `getTook()` as the getter. The getter returns a `TimeValue` object (`org.elasticsearch.core.TimeValue`), which encapsulates the duration.

Following a similar approach, we could retrieve the `long` value from the `TimeValue` object like this:
`long executionDurationInMillis = searchDocumentResponse.getTook().millis();`
Then, we could return a `java.time.Duration` object instead of a `long`:
`Duration executionDuration = Duration.ofMillis(executionDurationInMillis);`

P.S.: java.time.Duration is not currently used in the org.elasticsearch.core.TimeValue class.

Does this approach sound good to you?
