### ISSUE TITLE
index = true not working

### ISSUE THREAD

**Issue by ChiMuYuan** [spring-projects/spring-data-elasticsearch#2987]
Hello Maintainers,

I am encountering an issue while using Elasticsearch and would appreciate your guidance.

I aim to add a DenseVector field to my index and perform KNN (k-nearest neighbors) search on it. Therefore, I need to ensure that the index property for this field is set to true. Below is a code snippet illustrating my approach:

```java
@Field(name = "vectors", type = FieldType.Dense_Vector, index = true, dims = 256)
private List<Float> vectors = new ArrayList<>();
```

However, when I create the mapping using `indexOperations.createMapping()`, the generated mapping does not include the `index=true` setting. Additionally, when I check the index in Elasticsearch, I notice that the `index=true` setting is not applied to this field.

Could you please advise on how to proceed? Is this a potential bug or an expected behavior?

Thank you for your help.

Best regards,

**Comment by ChiMuYuan** [comment]
when i set `similarity` `index=true` working

```java
    @Field(name = "vectors", type = FieldType.Dense_Vector, index = true, dims = 256, similarity = "cosine")
    private List<Float> vectors = new ArrayList<>();
```

**Comment by sothawo** [comment]
From [the Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-index.html):
> The index option controls whether field values are indexed. It accepts true or false and defaults to true.

As `true` is the default, it is not explicitly written.
