### ISSUE TITLE
No doc about using optimistic locking

### ISSUE THREAD

**Issue by TheHett** [spring-projects/spring-data-elasticsearch#3028]
Standart approach to work with `@Version` isn't works for `data-elasticsearch`
For example I have entity

```kotlin

@Document(
    indexName = "item",
    writeTypeHint = WriteTypeHint.FALSE,
    versionType = Document.VersionType.INTERNAL,
)
class Item {

    @Id
    @Field(type = FieldType.Keyword)
    lateinit var id: String

    @Version
    @Field(type = FieldType.Version)
    var version: Long? = null

}
```
But got error: 
> internal versioning can not be used for optimistic concurrency control. Please use `if_seq_no` and `if_primary_term` instead

Using EXTERNAL type lead to
> version conflict, current version [1] is higher or equal to the one provided [1]

How are it need to be correct used to prevent concurrent data modification?
We are need to increment version of entity manually?
For example in another RDBMS this field managed by framework and incrementing internally.

**Comment by sothawo** [comment]
The documentation about the optimistic locking is on [Elasticsearch website, optimistic concurrency control](https://www.elastic.co/guide/en/elasticsearch/reference/current/optimistic-concurrency-control.html). The default way to do this is by using the seq_no and primary_term values. Spring Data Elasticsearch supports this with the [org.springframework.data.elasticsearch.core.query.SeqNoPrimaryTerm] data type.

Using the [_version] field is also documented in the [Elasticsearch docs, versions and version types](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning). The documentation does not mention [internal] any longer, I think we should deprecate and later remove it from Spring Data Elasticsearch. Using the version field for optimistic logging was done in pretty old Elasticsearch versions, it must have been dropped before version 6 I think.

As for your error, you retrieved a version 1 and then should have increased that to 2 before storing your data. External means that your application is responsible for the management of this value. If you need you need the behaviour like it was in older versions with the version field (send the value that you read), you need to switch to use `seq_no` and `primary_term`

**Comment by TheHett** [comment]
@sothawo thank you, very clear
