### ISSUE TITLE
NativeQuery.builder() 方式如何高亮展示

### ISSUE THREAD

**Issue by xh1106** [spring-projects/spring-data-elasticsearch#3029]
public SELF withHighlightQuery(HighlightQuery highlightQuery) {
        this.highlightQuery = highlightQuery;
        return this.self();
    }   只有这个方法，没有lambda的方法呀

**Comment by sothawo** [comment]
The only difference I see with the existing code is that you add a `this.` to the call of `self()` which is not necessary or needed.
