### ISSUE TITLE
Implement @Field(ignored=true) or @Document(ignoredFields="f1,f2")

### ISSUE THREAD

**Issue by manosbatsis** [spring-projects/spring-data-elasticsearch#39]
I have both JPA and elasticsearch annotations in my POJOs so javax.persistence.Transient would mess with my JPA persistence.  AFAIK the only workaround is duplicating my POJOs.

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

I would recommend to use different entities for JP, Elasticsearch and to send/receive via REST. Convert with mappers between them. Using one POJO to rule them all is an accident waiting to happen, as you already noticed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sothawo** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
