### ISSUE TITLE
How to disable numeric detection in an index?

### ISSUE THREAD

**Issue by abennet** [spring-projects/spring-data-elasticsearch#41]
I'd like to configure an index upon creation with elasticsearchTemplate, to have numeric_detection disabled.

I am incurring an issue during dynamic mapping when the xml first stores a date in string format and then a non-numeric string (xml is converted to json before indexing of course)

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

Is this still an unsolved problem?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
