### ISSUE TITLE
Using different field names for Pojo and Elastic Search Type

### ISSUE THREAD

**Issue by gauravbrills** [spring-projects/spring-data-elasticsearch#43]
HI I have small query as I dont know if the same is supported by spring data elasticsearch.The issue is can we have field name of pojo different to that of the elasticsearch index type .

Example 

as of now 

```
@Field(type = FieldType.Long)
private long PRODUCT_ID; 
```

which maps to type PRODUCT_ID in elasticsearch

can I do like this

```
@Field(name = "PRODUCT_ID ",type = FieldType.Long)
private long productId; 
```

like how we do in hibernate jpa annotations.

Not sure whether this will be an enhancement or is currently supported out of the box.

Regards
Gaurav

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

Since Spring Data Elasticsearch 3.2 there is `@Field(name="PRODUCT_ID")`
