### ISSUE TITLE
Is there any example of uisng spring-data-jpa and spring-data-elasticsearch together?

### ISSUE THREAD

**Issue by luisvt** [spring-projects/spring-data-elasticsearch#44]
I would like to know if there is any sample project that use both spring-data-jpa and spring-data-elasticsearch at the same time.

I would like to save data into PostgreSQL and into ElasticSearch at the same time. In that way I could maintain trusted data inside PostgreSQL and make fast reading from ElasticSearch.

**Comment by sothawo** [comment]
This issue surfaced again after switching from Jira issues to GitHub where it obviously was created a long time ago.

As @manosbatsis wrote, use different repositories, one for JPA and one for Elasticsearch. You will need to add all the annotations needed for the to backends to your entity.
