### ISSUE TITLE
JPA query methods in repository return default 10 records from ES [DATAES-58]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#632]
**[Gaurav Rawat](https://jira.spring.io/secure/ViewProfile.jspa?name=gauravbrills)** opened **[DATAES-58](https://jira.spring.io/browse/DATAES-58?redirect=false)** and commented

Hi I am facing a small issue with spring data elasticsearch,the same goes as below :-

1. I try to use the scafollded methods by extending a repository from ElasticSearchRepository class
   method is

```
List<ProductDTO> findByServiceTypeAndCityName(SERVICETYPES servicetypes, String cityName); .
```

2. The issue arrises when we use this method the result is just 10 records ,which I suspect is due to the query fired with the size attrib as default 10

```
{"query":{"bool":{"must":[{"field":{"product.cityName":"singapore"}}]}},"from":0,"size":10,"sort":[],"facets":{}}

```

Is there a way to get all records which actually hit ES rather than paged with size 10 .

Regards
Gaurav

---

**Affects:** 1.0 M1

**Comment by whatthefrog** [comment]
Seems that spring sends `{...,"size":25,...}` now ...
