### ISSUE TITLE
Support Custom/Extension types in @Field mappings [DATAES-95]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#633]
**[Joseph Moore](https://jira.spring.io/secure/ViewProfile.jspa?name=joemoore)** opened **[DATAES-95](https://jira.spring.io/browse/DATAES-95?redirect=false)** and commented

Presently FieldType is a fixed enum for built in elasticsearch datatypes, however extensions can add custom FieldTypes, some of which are even developed by elasticsearch (i.e. attachment, https://github.com/elasticsearch/elasticsearch-mapper-attachments).

Presently, there is no way to support these custom types, I suggest adding a "custom" type to FieldType and an additional "typeName" property on the `@Field` annotation to support supplying the name of the custom type, which will then be used in the mapping when the FieldType is custom

---

**Issue Links:**
- [DATAES-967](https://jira.spring.io/browse/DATAES-967) Provide a way to use custom field types
 (_**"is duplicated by"**_)

1 votes, 3 watchers

**Comment by sothawo** [comment]
As we cannot know all the needed properties in a mapping and put this on the `@Field` annotation, the way to go here is to provide a file with the mapping for the field and annotate that field (not the entity) with `@Mapping`.

As an example check the `MappingEntity`  class in the tests:
https://github.com/spring-projects/spring-data-elasticsearch/blob/main/src/test/java/org/springframework/data/elasticsearch/core/index/MappingBuilderUnitTests.java#L1063-L1073
