### ISSUE TITLE
Ability to enable/disable/control Setting/Mapping updates [DATAES-111]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#684]
**[Jason](https://jira.spring.io/secure/ViewProfile.jspa?name=jeacott)** opened **[DATAES-111](https://jira.spring.io/browse/DATAES-111?redirect=false)** and commented

When I'm using `@Setting`, and `@Mapping`,
its sometimes convenient to have updated mappings applied when the application starts (particularly for testing),
but its also very common to have settings/mappings configured once, sometimes  by external means, and a spring data app should not always overwrite these each time its restarted.
For me this is exactly the same usecase as for example hibernates' hibernate.hbm2ddl.auto setting.

I think its necessary to get some global config options that can be set externally via whatever means makes sense to the developer (properties file, environment variable, mmap  etc) so that this setting (and likely others) can be controlled.

---

1 votes, 2 watchers

**Comment by sothawo** [comment]
Spring Data Elasticsearch does not use or read properties or configurations. To have a logic like this is in the responsibility of an application using Spring Data Elasticsearch.
