### ISSUE TITLE
Define alias for document [DATAES-192]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#767]
**[Tim Schimandle](https://jira.spring.io/secure/ViewProfile.jspa?name=tschiman@gmail.com)** opened **[DATAES-192](https://jira.spring.io/browse/DATAES-192?redirect=false)** and commented

Currently spring data ES documents are defined by an index name that can be set via annotations on the document. This works well for simple cases in which a single index will suffice.

When a user wishes to do something more complex, like swap indexes dynamically, elasticsearch's reccomended way is to define an alias, and associate all operations to the alias. In the background the user can now build a second index with updated information and then direct elasticsearch to use that index by changing the reference in the alias.

Spring data ES does not currently support the definition of an alias on a document that will be used in all JPA default queries or by the elasticsearch template. This makes working with aliases difficult as it requires the user to abandon all of the default queries provided by the JPA implementation.

A solution to this problem would be to expose a property in the Document annotation that would define an aliasName. If present, an alias would be created and the underlying index would be associated with that alias. In all of the searching functions when an indexName is needed, if there is an aliasName the aliasName is used to perform the search. For functions that require access to the index directly the elasticsearch client can get a list of indexes associated with the alias and operate on them. The solution would have to handle the possibility of the alias already being created.

`@Document`(**aliasName = "test-alias"**, indexName = "test", type = "test")

---

**Affects:** 1.2.2 (Fowler SR2)

**Issue Links:**
- [DATAES-864](https://jira.spring.io/browse/DATAES-864) Rework alias management
 (_**"is superseded by"**_)

11 votes, 9 watchers

**Comment by eaudet** [comment]
What if I need thousands of aliases? Better yet, I have no idea how many aliases I need when creating the mapping.
If the number of aliases is unknown at the time you create the mapping, we need something else than you propose. For instance, if you need an alias for each users (to implement multi-tenancy). Then, I would like to see something like: `@Document(aliasKey="user_id") `
Then, you can PUT any document as the following (Spring data could create the alias query if it is not present. 

`PUT /user123/post/1 
{ 
"user_id": "user123", 
"title": "Easy recipe for ginger nuts", 
... } `

**Comment by sothawo** [comment]
routing has nothing to do with aliases. Storing a document with routing _user1_ will not prevent it from being returned by a search that should only be visible to _user2_.
You probably need index templates with aliases.

**Comment by cdalexndr** [comment]
In spring-data-elasticsearch **4.4.1** there is no alias field on `@Document`.
Has this feature been reverted, or was never implemented?
