### ISSUE TITLE
Enable different result classes in same search result [DATAES-222]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#795]
**[Lars Beuster](https://jira.spring.io/secure/ViewProfile.jspa?name=lbeuster)** opened **[DATAES-222](https://jira.spring.io/browse/DATAES-222?redirect=false)** and commented

Currently it's not easy to return objects of different types in the same search response.

My use case: I have different objects in ES and want to search over all objects. (I still have the 1:1 mapping between the ES document type and the result class).

It's possible to overwrite the ResultsMapper to use different result classes depending on the document type of the search hits. Unfortunately the DefaultResultsMapper is not designed to do that in an easy way, so I could not use it as a base class.

I could imagine a method like the one below that is used by all mapXXX methods:
mapEntity(json, documentType, resultClass)

Or have somewhere a registry from document type -> result class that is used by the DefaultResultsMapper.

---

1 votes, 3 watchers

**Comment by sothawo** [comment]
I wrote a [blog post](https://www.sothawo.com/2021/05/reading-different-entities-from-multiple-indices-with-one-call-using-spring-data-elasticsearch/) showing how this can be implemented in an application with the current version of Spring Data Elasticsearch (4.1.8)

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
