### ISSUE TITLE
Add a setting do disable createIndexIfNotCreated [DATAES-273]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#848]
**[Stéphane Daviet](https://jira.spring.io/secure/ViewProfile.jspa?name=stephanedaviet)** opened **[DATAES-273](https://jira.spring.io/browse/DATAES-273?redirect=false)** and commented

When an entity is mapped to an index through `@Document`, the index is created in the targeted ES nodes if not already present ([ElasticsearchTemplate#createIndex](https://github.com/spring-projects/spring-data-elasticsearch/blob/2.0.2.RELEASE/src/main/java/org/springframework/data/elasticsearch/core/ElasticsearchTemplate.java#L152,L154)).

There should be a way to disable this index creation, the same way that in JPA you can disable DDL generation

---

**Affects:** 2.0.2 (Hopper SR2)

**Comment by christophstrobl** [comment]
I'd like to bring up the issue regarding automatic index creation (see: #848) for entities again in the light of conducting application training runs (eg. for CDS) that should in best case work without having to interact with the data store.
Currently this would only work by changing the value for the annotation attribute without an external configuration option that would disable index creation.

**Comment by sothawo** [comment]
Do I understand it correctly, you need a way to disable automatic creation of an index if it does not exist without setting it in the `@Document` annotation? And this should be etxernally configurable? 

Currently SDE does not use or read any configuration, how do you propose to have this done? 

Would this be some "global" setting or something individual per entity? 

And when index creation is disabled and later a document ist saved, this means that the mapping written to ES does not conform to the `@Field` annotations on the properties but be some automatic mapping done by ES>

**Comment by christophstrobl** [comment]
I'm actually looking for an option to create a `SimpleElasticsearchRepository` instance without any immediate interaction with the server. Currently upon creation index creation is triggered. So though the ES Client is lenient about the server being present when it's created, the repository is not. So an application will not be able to start if the server cannot be reached.
If there was an external option to disable the index creation that would help, or delaying the creation till the repo is used for the first time.

**Comment by sothawo** [comment]
Delaying seems the most elegant solution for me; I'll have to check, I think the reactive repositories have this behaviour, but I'm not sure. Will have a look.

**Comment by sothawo** [comment]
I created #2876 for that, as it's related to this issue, but is something new and different.
