### ISSUE TITLE
Possibility to specify an internal type of @Version provided by Elasticsearch [DATAES-295]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-elasticsearch#869]
**[Andrew](https://jira.spring.io/secure/ViewProfile.jspa?name=ausov)** opened **[DATAES-295](https://jira.spring.io/browse/DATAES-295?redirect=false)** and commented

How can we use internal versioning of Elasticsearch?

Elsticsearch has a possibility to choose a type of version to implement optimistic locking (https://www.elastic.co/blog/elasticsearch-versioning-support). Currently, if an entity field marked with
`@Version` the _external_ version type is always used.

On the other hand, the Spring Data Rest also uses `@Version` mechanism to implement `ETag` and `If-Match` headers handling. This means that if we want to use this mechanism, we're forced to use ES optimistic locking and _external_ ES versioning.

So, it would be great if we can specify which version mechanism we want to use.

**Suggestion:**  Introduce a new optional annotation on a version _field_ or, probably more appropriate, on a _repository_ to specify a version type, e.g. `@VersionType(EXTERNAL)`.

**Workaround:** implement a custom repo taking care of version increment.

---

1 votes, 2 watchers

**Comment by sothawo** [comment]
The `@Document` annotation has a property `versionType` since december 2018 which can be set to external
